### ISSUE TITLE
Data table component

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#1607]
# Data table

## Brief description

This epic represents all of the data table extensions that are listed on the [PAL site](https://pages.github.ibm.com/cdai-design/pal/components/data-table/overview).

## Details

[Link to Design](https://pages.github.ibm.com/cdai-design/pal/components/data-table/overview)
[Existing data grid component from WKC](https://github.ibm.com/wdp-gov/wkc-shared-ui/tree/master/src/components/datagrid)

### Links to other materials

e.g. sketch files, icons, images, prototypes

## Design Maintainer(s)

- ~Marion Brülls~ Ashley Bock
- Virginia Nicholson
- ~Mitchell Bernstein~
- Johanna Koval
- Nina Shahriaree

## Tasks

Before starting work on this epic, please review and complete the following.

- [x] Initial review of design/existing code

### Working in Carbon for IBM Products package

- [x] Have you reviewed our
      [contribution guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/.github/CONTRIBUTING.md)?
- [x] Have you noted our
      [code guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/docs/CODE_GUIDELINES.md)?
- [x] Did you use the CLI to scaffold your new component?

```[tasklist]
### Tasks
- [ ] #2499 
- [ ] https://github.com/carbon-design-system/ibm-products/issues/3244
```

**Comment by holmansze** [comment]
Code is still in my fork -
https://github.com/holmansze/ibm-cloud-cognitive/tree/datagrid/packages/cloud-cognitive/src/components/Datagrid

We can create PRs off this fork for the additional work, before I create a PR against master.

**Comment by yumeforever** [comment]
@matthewgallo I see the timeline set for September 26 — Are still in time for this one? Just asking because I want to plan on an announcement for Cloud PAL community that we will retire the support for our Data Table components in favor of the Data Grid.

**Comment by matthewgallo** [comment]
Hey @yumeforever! Yes, that's still our target as of right now. I can keep you updated with there is anything that changes in terms of the timeline

**Comment by elycheea** [comment]
Release strategy is currently in discussion.
