### ISSUE TITLE
DataSpreadsheet epic

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#1653]
# DataSpreadsheet

## Brief description

Used to organize and display large amounts of structured data, separated by columns and rows in a grid-like format.

## Details

[Link to Design](https://ibm.ent.box.com/notes/868637259629?s=qgnn4rzk18s754fh9tpqzktsteueueih)
^^ will update to PAL designs as soon as published

### Links to other materials

[View component on storybook](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-dataspreadsheet-dataspreadsheet-canary--data-spreadsheet)

## Design Maintainer(s)

- @mitchellbernstein

## Tasks

Before starting work on this epic, please review and complete the following.

- [ ] Initial review of design/existing code

### Working in Carbon for IBM Products package

- [X] Have you reviewed our
      [contribution guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/.github/CONTRIBUTING.md)?
- [X] Have you noted our
      [code guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/docs/CODE_GUIDELINES.md)?
- [X] Did you use the CLI to scaffold your new component?
