### ISSUE TITLE
Drag and drop

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#2042]
# Drag and drop

## Brief description

Drag and drop is a common interaction that is widely used for various situations. In Carbon ecosystem, we clarify the use cases, interactions and styles.

## Details

[Link to design](https://pages.github.ibm.com/cdai-design/pal/patterns/drag-and-drop/usage)

### Links to other materials

e.g. sketch files, icons, images, prototypes

## Design Maintainer(s)

- Minji Kim
- Carrie Lloyd

## Tasks

Before starting work on this epic, please review and complete the following.

### Working in Carbon for IBM Products package

- [ ] Have you reviewed our
      [contribution guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/.github/CONTRIBUTING.md)?
- [ ] Have you noted our
      [code guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/docs/CODE_GUIDELINES.md)?
- [ ] Did you use the CLI to scaffold your new component?

```[tasklist]
### Acceptance criteria
- [ ] https://github.com/carbon-design-system/ibm-products/issues/3490
- [ ] https://github.com/carbon-design-system/ibm-products/issues/3478
```

```[tasklist]
### Pattern examples
- [ ] Vertical list
- [ ] Horizontal list
- [ ] Between lists
```

**Comment by elycheea** [comment]
Still relevant. Was blocked by #1869 and will be prioritized once we clean house post #2884

**Comment by elycheea** [comment]
@lee-chase as discussed, I don’t think we’re trying to sign up to become yet another dnd library unless we think that’s the best route forward. But we can start by exploring if we can provide the wrappers/styling for it at least. 👀

**Comment by matthewgallo** [comment]
First iteration of drag and drop examples included [here](https://carbon-for-ibm-products.netlify.app/?path=/docs/ibm-products-patterns-drag-and-drop-draganddrop--docs). Happy to revisit this issue/create enhancement issues as they arise.
