### ISSUE TITLE
Canvas

### ISSUE THREAD

**Issue by quarryboy** [carbon-design-system/ibm-products#2074]
# Canvas/Network diagramming

## Brief description

Canvas pattern should be added to Carbon for IBM Products

## Details

[Current guidance in Carbon for IBM Products](https://pages.github.ibm.com/cdai-design/pal/patterns/canvas/usage/) 
[Current Carbon Charts Storybook](https://charts.carbondesignsystem.com/angular/?path=/story/diagrams--start-here)

### Links to other materials
[Sketch WIP project file](https://sketch.com/s/41f1516e-92c0-402f-80fa-221baba47649)

## Design Maintainer(s)

- Devin O'Bryan
- Diana Stanciulescu 

## Tasks

Before starting work on this epic, please review and complete the following.

- [X] Initial review of design/existing code

### Working in Carbon for IBM Products package

- [X] Have you reviewed our
      [contribution guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/.github/CONTRIBUTING.md)?
- [ ] Have you noted our
      [code guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/docs/CODE_GUIDELINES.md)?
- [ ] Did you use the CLI to scaffold your new component?

**Comment by elycheea** [comment]
@quarryboy We opened this issue as an epic in #2043 (which we can close and replace with this one) but want to verify — Is the expectation to update the pattern in the Carbon Charts library or to add the updated canvas patterns as Carbon for IBM Products patterns (our own Storybook)?

Based on our previous chat, I thought the plan was to move the components here but the description reads as the opposite (Carbon Charts will keep the pattern).

**Comment by quarryboy** [comment]
i will defer to you and @theiliad on the best way to handle this in terms of the actual code and where it lives. 

my assumption from previous conversations was that we would use the Carbon charts library as the jumping off point for updating (or wholesale replacing the content depending on the need) to reflect the updates found in the PAL. with Carbon Next on the horizon as a single entry point for all the guidance, would it make more sense to just replace the content that's already in the Carbon Charts storybook?

**Comment by theiliad** [comment]
> i will defer to you and @theiliad on the best way to handle this in terms of the actual code and where it lives.
> 
> my assumption from previous conversations was that we would use the Carbon charts library as the jumping off point for updating (or wholesale replacing the content depending on the need) to reflect the updates found in the PAL. with Carbon Next on the horizon as a single entry point for all the guidance, would it make more sense to just replace the content that's already in the Carbon Charts storybook?

I think at the very least what I've seen so far could go into Carbon Charts itself 🙂

**Comment by elycheea** [comment]
@quarryboy @theiliad Hmm, I think we do want to maintain some ownership of the canvas pattern so there’s parity between our site (or Carbon Next neighborhood) and our Storybook. We’d probably want to avoid asking the product teams we support to add the Carbon Charts package just for Canvas if it comes up. **Devin**, are there teams you know of outside of our product teams who may use the canvas pattern?

I definitely would not want to duplicate our efforts so I’m open to thoughts on how we approach this.

**Comment by quarryboy** [comment]
good call @elycheea . there are a few non-IBM products that use Elyra canvas that could benefit since that product is open source and would ultimately adopt whatever package is created. hence those products by proxy would incorporate it. is that answering your question or do you mean only internal to IBM?

**Comment by elycheea** [comment]
Based on last discussion with @kristastarr, this will be maintained by a separate team for now.
Can we share the link to the canvas repo/library?
