### ISSUE TITLE
Datagrid design review

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#2499]
## Design review

Component epic #1607

### Standards

- [ ] All pattern updates/changes/iterations have been discussed with the
      component developer
- [x] Patterns have been approved by either DSAG or another approving entity

### Pattern and behavior

- [ ] The component behaves according to the guidelines set by the pattern
      maintainer
- [ ] The component’s UI matches the pattern specifications set by the pattern
      maintainer
- [ ] The component’s motion matches the specifications set by the pattern
      maintainer(s)
- [ ] The UI produced is responsive, cross-browser, and responds to the
      currently set Carbon theme.
- [ ] Colors, themes, sizes and additional props are true and correct, aligning
      with Carbon set tokens (unless otherwise specified by the pattern)
- [ ] Paddings/margins/spacings are true and correct, in both desktop and mobile
      views

### Storybook

- [ ] A functioning component renders in Storybook
- [ ] The Storybook displays multiple scenarios that show how the component can
      be used
- [ ] Changing props in the Storybook updates the component

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/ibm-products/issues/3117
- [ ] https://github.com/carbon-design-system/ibm-products/issues/3118
- [ ] https://github.com/carbon-design-system/ibm-products/issues/3119
- [ ] https://github.com/carbon-design-system/ibm-products/issues/3120
- [ ] https://github.com/carbon-design-system/ibm-products/issues/2608
- [ ] https://github.com/carbon-design-system/ibm-products/issues/2606
- [ ] https://github.com/carbon-design-system/ibm-products/issues/2607
- [ ] https://github.com/carbon-design-system/ibm-products/issues/3121
- [ ] https://github.com/carbon-design-system/ibm-products/issues/2537
- [ ] https://github.com/carbon-design-system/ibm-products/issues/3158
- [ ] https://github.com/carbon-design-system/ibm-products/issues/2503
- [ ] https://github.com/carbon-design-system/ibm-products/issues/3159
```

**Comment by Ashley-Bock** [comment]
- While dragging item back to original location, icons sometimes become stacked: 
<img width="414" alt="Screenshot 2022-12-13 at 1 08 04 PM" src="https://user-images.githubusercontent.com/120116973/207423437-51f20b52-5a5c-403c-80c0-52ccea28847c.png">

**Comment by elycheea** [comment]
This is an ongoing effort. 🔜

**Comment by sdignum** [comment]
### Standards
- [ ]  All pattern updates/changes/iterations have been discussed with the
component developer
- [x] Patterns have been approved by either DSAG or another approving entity

### Pattern and behavior
- [x] The component behaves according to the guidelines set by the pattern maintainer
- [x] The component’s UI matches the pattern specifications set by the pattern maintainer'
- [x] The component’s motion matches the specifications set by the pattern maintainer(s)
- [x] The UI produced is responsive, cross-browser, and responds to the currently set Carbon theme.
- [x] Colors, themes, sizes and additional props are true and correct, aligning with Carbon set tokens (unless otherwise specified by the pattern). 
- Caveat here is the tooltip for dark themes looks wrong (I see this on Carbon stuff as well) - it shows a shadow on both the caret and the tooltip container, creating a line between the caret and the content area.
- [x] Paddings/margins/spacings are true and correct, in both desktop and mobile views

### Storybook

- [x] A functioning component renders in Storybook
- [ ] The Storybook displays multiple scenarios that show how the component can be used 
- According to Carbon guidance on the [data table section](https://carbondesignsystem.com/components/data-table/usage/#pagination) and the [Pagination guidance](https://carbondesignsystem.com/components/pagination/usage), there should be a simple view, one with disabled pages, and one where the number of pages are unknown, but I don't see a way to look at those variations in Storybook.
- Also, Carbon pagination storybook allows for adjusting height of the pagination bar (sm, med, large)
- [x] Changing props in the Storybook updates the component - N/A

**Comment by sdignum** [comment]
@elycheea  I think I'm done reviewing pagination with the understanding that someone else is looking at accessibility (I did notice the dropdowns/selectors do not respond to the Enter key, and the accessibility guidance for pagination does say that space bar and enter key should both open the dropdowns/selectors if I read it correctly).

**Comment by elycheea** [comment]
@sdignum Thank you! Will review comments in more depth after the weekend, but did you get a chance to look at loading state as well? Not sure there’s much to do there since it’s largely based on Carbon ... but maybe just a quick “as expected” or “not quite as expected” would work for that one.
