### ISSUE TITLE
Datagrid design review: base component

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#2537]
## Design review

- Component epic #1607 #2499 
- Links: [PAL guidance](https://pages.github.ibm.com/cdai-design/pal/components/data-table/overview) / [Storybook](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary)
  - [Toolbar](https://ibm.box.com/s/3cbxo79wdk2v36yz96rsryk4miillg0y)
  - Sorting ([Carbon](https://www.carbondesignsystem.com/components/data-table/usage/#multi-select-and-batch-action))
  - Pagination ([Carbon](https://www.carbondesignsystem.com/components/data-table/usage/#multi-select-and-batch-action))
  - Loading state ([Carbon](https://www.carbondesignsystem.com/components/data-table/usage/#multi-select-and-batch-action))
  - [Empty state](https://pages.github.ibm.com/cdai-design/pal/patterns/empty-state/usage)
  - [Column alignment](https://pages.github.ibm.com/cdai-design/pal/components/data-table/column-alignment/usage)
  - Ability to handle thousands of entries

Other hooks/utilities we should check as part of base component:
@matthewgallo 

```
useHeaderRow
useSkeletonRows
useDefaultStringRenderer
useRowRenderer
useFlexResize
useFloatingScroll
getAutoSizedColumnWidth
```

---

### Standards

- [ ] All pattern updates/changes/iterations have been discussed with the
      component developer
- [ ] Patterns have been approved by either DSAG or another approving entity

### Pattern and behavior

- [ ] The component behaves according to the guidelines set by the pattern
      maintainer
- [ ] The component’s UI matches the pattern specifications set by the pattern
      maintainer
- [ ] The component’s motion matches the specifications set by the pattern
      maintainer(s)
- [ ] The UI produced is responsive, cross-browser, and responds to the
      currently set Carbon theme.
- [ ] Colors, themes, sizes and additional props are true and correct, aligning
      with Carbon set tokens (unless otherwise specified by the pattern)
- [ ] Paddings/margins/spacings are true and correct, in both desktop and mobile
      views

### Storybook

- [ ] A functioning component renders in Storybook
- [ ] The Storybook displays multiple scenarios that show how the component can
      be used
- [ ] Changing props in the Storybook updates the component

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/ibm-products/issues/3117
- [ ] https://github.com/carbon-design-system/ibm-products/issues/3118
- [ ] https://github.com/carbon-design-system/ibm-products/issues/3119
- [ ] https://github.com/carbon-design-system/ibm-products/issues/3120
- [ ] https://github.com/carbon-design-system/ibm-products/issues/2608
- [ ] https://github.com/carbon-design-system/ibm-products/issues/2606
- [ ] https://github.com/carbon-design-system/ibm-products/issues/2607
- [ ] https://github.com/carbon-design-system/ibm-products/issues/3121
- [ ] https://github.com/carbon-design-system/ibm-products/issues/2509
- [ ] https://github.com/carbon-design-system/ibm-products/issues/3158
- [ ] https://github.com/carbon-design-system/ibm-products/issues/3159
```
