### ISSUE TITLE
Storybook 7 has been released

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-products#2846]
Storybook 7 will require investigation to determine the amount of work required to upgreade.

Migration guide.
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-registerjs
```[tasklist]
### Tasks
- [ ] Fix getting started shields
- [ ] https://github.com/carbon-design-system/ibm-products/issues/3128
- [ ] https://github.com/carbon-design-system/ibm-products/issues/3356
```

**Comment by elycheea** [comment]
Should look into the move to Storybook 7 after v2 release. If it’s easy to accomplish for v2, then we should also update this for v1 to reduce maintenance overhead.

This issue should track the investigation. We can create an epic after to track more specific tasks.

**Comment by lee-chase** [comment]
See https://storybook.js.org/docs/react/migration-guide

- **automigrate fails `npx** storybook@next automigrate --config-dir ./packages/core`
![image](https://github.com/carbon-design-system/ibm-products/assets/15086604/3874877f-e333-4333-96c6-af5a2f5086bc)

- **upgrading stories manually fails `npx storybook@latest migrate csf-2-to-3 --glob="packages/ibm-products/src/**/*.stories.js"`
Lots of this
npx storybook@latest migrate csf-2-to-3 --glob="packages/ibm-products/src/**/*.stories.js"

- MDX version has changed from 1 to 2
- Story format has changed from 2 to 3 (Storybook 7 still supports 2). Should see this as deprecated

**Comment by lee-chase** [comment]
Probably worth following https://github.com/storybookjs/storybook/issues/21710

**Comment by lee-chase** [comment]
PR #3037 is a work in progress attempt to upgrade storybook.

**Comment by lee-chase** [comment]
@elycheea we make extensive use of dynamic titles to organise our components.

This issue was marked as won't fix a year ago.

https://github.com/storybookjs/storybook/issues/15815

**Comment by lee-chase** [comment]
Using storyStoryV7 false appears to allow storybook to start but all stories but Welcome DOCS to error

```
  features: {
    legacyMdx1: true, // 👈 Enables MDX v1 support
    // setting storyStoryV7 to false allows the storybook to build
    storyStoreV7:  false, // 👈 Opt out of on-demand story loading
  },
```

This suggests our stories are not CSF https://storybook.js.org/docs/react/migration-guide#storiesof-support-discontinued-by-default

![image](https://github.com/carbon-design-system/ibm-products/assets/15086604/8f5c960c-b591-409c-95c7-645d065c2c19)

![image](https://github.com/carbon-design-system/ibm-products/assets/15086604/87d95076-1f9b-449f-a6c9-491a80d707d7)
