### ISSUE TITLE
v2 release

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#2884]
### Renaming repository to `ibm-products`
- Should we rename the folder in the monorepo to `ibm-products`
- Should we rename the repository to `ibm-products`
- Might break netlify if we rename ... should look into this
- Use new ibm-products Carbon URL

Major release seems like appropriate timing to move away from the legacy name.

### Order of operations
- [x] Rename `cloud-cognitive` folder @matthewgallo 
  - [x] v1 ~#2904~ #3009
  - [x] v2 https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/2905
- [x] Update dependencies #2911 @elycheea 
- [x] “Final release” of v1 from `main` before renaming to `v1` (1.53.1 from new branch)
- [x] Rename branches ~1 week ahead of release @lee-chase 
- [x] Add `v1-ibm-products.carbondesignsystem.com` @matthewgallo
- [x] Update examples (prefixes @lee-chase) #2999 
- [x] Update v2 migration docs (@matthewgallo)
- [x] Rename repository? (~this one tbd~ sounds like @lee-chase)
    - [x] Update more URLs #3004 #3005
- [x] Update CodeSandbox URLs
- [x] Release v2 _(manual release)_ (probably May 17)

_Can be asynchronous from actual release_
- [x] Add v2 Storybook banner (@elycheea) #2994
- [x] Update Storybook URLs (@elycheea) #3012 #3014
