### ISSUE TITLE
Novice to pro: Inline tip

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#2940]
# Inline tip

## Brief description

The inline tip exists to facilitate just-in-time focused learning, in-context of the relevant component, or when the user is in a focused state.

_[Novice to pro](https://pages.github.ibm.com/cdai-design/pal/novice-to-pro/overview) is a continuous learning framework aimed to orient, onboard, explain, educate, and cultivate novice users into high-functioning power users._

## Details

Link to designs: [usage](https://pages.github.ibm.com/cdai-design/pal/novice-to-pro/components/inline-tip/usage), [Figma](https://www.figma.com/file/BuZgGaVw11oBdh9v03ecI6/Novice-to-pro-components?type=design&node-id=1-2&t=ReDL9Fsz6zJ9Y0QJ-0).

### Links to other materials

e.g. sketch files, icons, images, prototypes

## Design Maintainer(s)

- Shelley Dignum @sdignum
- Rebecca Love 

## Tasks

Before starting work on this epic, please review and complete the following.

- [x] Initial review of design/existing code

### Working in Carbon for IBM Products package

- [x] Have you reviewed our
      [contribution guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/.github/CONTRIBUTING.md)?
- [x] Have you noted our
      [code guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/docs/CODE_GUIDELINES.md)?
- [ ] Did you use the CLI to scaffold your new component?
