### ISSUE TITLE
Datagrid design review: Toolbar

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#3117]
## Design review

- Component epic #1607 #2499 
- Links: [PAL guidance](https://pages.github.ibm.com/cdai-design/pal/components/data-table/settings/usage) / [Storybook v2](https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid-datagrid-canary--empty-state) / [Storybook v1](https://v1-ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid-datagrid-canary--empty-state)
  - [Toolbar](https://ibm.box.com/s/3cbxo79wdk2v36yz96rsryk4miillg0y)

---

### Standards

- [ ] All pattern updates/changes/iterations have been discussed with the
      component developer
- [ ] Patterns have been approved by either DSAG or another approving entity

### Pattern and behavior

- [ ] The component behaves according to the guidelines set by the pattern
      maintainer
- [ ] The component’s UI matches the pattern specifications set by the pattern
      maintainer
- [x] The component’s motion matches the specifications set by the pattern
      maintainer(s)
- [x] The UI produced is responsive, cross-browser, and responds to the
      currently set Carbon theme.
- [ ] Colors, themes, sizes and additional props are true and correct, aligning
      with Carbon set tokens (unless otherwise specified by the pattern)
- [ ] Paddings/margins/spacings are true and correct, in both desktop and mobile
      views

### Storybook

- [x] A functioning component renders in Storybook
- [x] The Storybook displays multiple scenarios that show how the component can
      be used
- [x] Changing props in the Storybook updates the component
```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/ibm-products/issues/3241
- [ ] https://github.com/carbon-design-system/ibm-products/issues/3129
```

**Comment by elycheea** [comment]
@Ashley-Bock can you take this one?

**Comment by elycheea** [comment]
@kristastarr Feel free to remove any checks that don’t apply.

---

## Accessibility review

### [Keyboard](https://www.ibm.com/able/toolkit/develop/keyboard)

#### Level 1

- [ ] Properly code the navigation order
  - [ ] Ensure interactive elements are reachable with the keyboard
  - [ ] Where possible, achieve the desired tab order by adjusting the DOM,
        rather than overriding the tabindex
  - [ ] When overriding the default focus indicator, confirm focus is highly
        visible
- [ ] Implement established keyboard conventions
  - [ ] Use standard HTML elements where possible, using CSS to alter appearance
        not behavior
  - [ ] Be familiar with established keyboard conventions
  - [ ] Implement keyboard operation for custom elements

#### Level 2

- [ ] Ensure keyboard access to complex interactions
  - [ ] Make custom media player and animation controls keyboard accessible

#### Level 3

- [ ] Code screen updates predictably
  - [ ] Use "activate" rather than "focus" as a trigger
  - [ ] Use an onchange event without disorienting the user

### [Dynamic updates](https://www.ibm.com/able/toolkit/develop/dynamic-updates)

#### Level 1

- [ ] Provide errors accessibly
  - [ ] Use accessible methods to implement error messages
  - [ ] Implement validation and notification to minimize interruptions

#### Level 2

- [ ] Make content accessible that appears on hover or focus
  - [ ] Ensure <kbd>Esc</kbd> dismisses new content
  - [ ] If content appears on hover, the new content needs to remain visible
        until dismissed
  - [ ] Moving the pointer away from the trigger should not be the action that
        dismisses the new content
  - [ ] Ensure custom tooltips and similar hover text can be triggered by
        keyboard
  - [ ] Discuss alternatives to hover text
  - [ ] Use caution where interactive controls appear in the hover text
- [ ] Code cancellation actions accessibly
  - [ ] Provide accessible ways of cancelling pointer interaction
- [ ] Properly code status messages
  - [ ] Use `role=status` to advise on the success or results of an action
  - [ ] Use `role=alert` or an ARIA live region to convey a suggestion or
        warning

#### Level 3

- [ ] Allow reduced motion
  - [ ] Implement motion media queries to reduce user risk

### [Text and non-text](https://www.ibm.com/able/toolkit/develop/text-and-non-text)

#### Level 1

- [ ] Implement text alternatives for meaningful images, sound, and visual data
  - [ ] Give decorative images an ALT attribute with an empty string (`alt=""`)
  - [ ] Use HTML, ARIA, or technology-specific techniques to add short text
        alternatives
  - [ ] Where relevant text exists in the UI, use `aria-labelledby` and
        `aria-describedby` to reference
  - [ ] Provide an accessible method for exposing long text alternatives
  - [ ] Embed multimedia content that supports closed captions
- [ ] Implement correct structure and metadata
  - [ ] Code headings according to specifications
  - [ ] ~Code the `<title>` element on every page according to specifications~
  - [ ] ~Set the language for each page~

#### Level 2

- [ ] Add additional structure where appropriate
  - [ ] Use `<figcaption>` and `<caption>` elements where figures and tables are
        titled
  - [ ] Add additional context to generic link names
  - [ ] Consider adding regions and other ARIA roles to distinguish text
        groupings

#### Level 3

- [ ] ~Mark up foreign words and abbreviations~
  - [ ] ~Use the `lang` attribute for foreign words and phrases~
  - [ ] Use `<abbr>` elements and title attributes to expand abbreviations
- [ ] Achieve necessary reading order
  - [ ] Order content appropriately in the DOM
  - [ ] Only use CSS to alter text position without altering meaning

### [User input](https://www.ibm.com/able/toolkit/develop/user-input)

#### Level 1

- [ ] Associate labels with inputs
  - [ ] Programmatically associate inputs with labels
  - [ ] Add accessible names for inputs lacking visible labels
- [ ] Provide correct name, role, and value
  - [ ] If repurposing a standard component, use ARIA to set the correct name
        and role
  - [ ] On custom components, use ARIA to expose `name`, `role`, and `value`

#### Level 2

- [ ] Reduce conflict between the visible label and a component's accessible
      name
  - [ ] Match the accessible name to the visible label
  - [ ] Include the text of the label in the accessible name

#### Level 3

- [ ] Indicate the purpose of common inputs
  - [ ] Use HTML `autocomplete` attributes, where appropriate

**Comment by Ashley-Bock** [comment]
**1. Pop-out styling**
There are discrepancies between v1 and v2 in terms of the pop-out styling. The v1 better matches the specs in the PAL guidance images, but I'm not sure if the change in v2 was intentional. See below: 

v2:
<img width="275" alt="Screenshot 2023-06-14 at 3 17 50 PM" src="https://github.com/carbon-design-system/ibm-products/assets/120116973/a1924a4c-307c-49a8-b7a4-b95b36c141f9">

v1:
<img width="302" alt="Screenshot 2023-06-14 at 3 18 26 PM" src="https://github.com/carbon-design-system/ibm-products/assets/120116973/2bdb6ebd-d7a4-4f60-b863-75d055a729b2">

- [ ] **Action item:** Determine if pop-out change was intentional and unify visuals in PAL guidance to match v2 specs. 

**2. Order of sizes listed**
In the examples in the PAL guidance, the sizes are listed smallest to largest. In both v1 and v2, they are listed largest to smallest. 

v2 example:
<img width="265" alt="Screenshot 2023-06-14 at 3 21 25 PM" src="https://github.com/carbon-design-system/ibm-products/assets/120116973/84322543-a5d6-406d-bfe1-9e93537f38dc">

PAL guidance
![image](https://github.com/carbon-design-system/ibm-products/assets/120116973/e181a002-70ea-4ccb-ad6d-0967a8c1cc9b)

- [ ] **Action item:** decide which order to display sizes and unify visuals in PAL guidance. 

**3. Toolbar height** 
In the guidance, it says that the toolbar height should change as the user adjusts the row height. Neither v1 or v2 demonstrate this in the storybook. 

- [ ] **Action item:** Decide if this should still be included in the pattern even if it is not going to be supported behavior of the component.

**Comment by Ashley-Bock** [comment]
### Standards

- [ ] All pattern updates/changes/iterations have been discussed with the component developer
- [ ] Patterns have been approved by either DSAG or another approving entity

### Pattern and behavior

- [ ] The component behaves according to the guidelines set by the pattern maintainer

- [ ] The component’s UI matches the pattern specifications set by the pattern maintainer
- [ ] The component’s motion matches the specifications set by the pattern maintainer(s)
- [ ] The UI produced is responsive, cross-browser, and responds to the currently set Carbon theme.
- [ ] Colors, themes, sizes and additional props are true and correct, aligning with Carbon set tokens (unless otherwise specified by the pattern)
- [ ] Paddings/margins/spacings are true and correct, in both desktop and mobile views

### Storybook

- [ ] A functioning component renders in Storybook
- [ ] The Storybook displays multiple scenarios that show how the component can be used
- [ ] Changing props in the Storybook updates the component

**Comment by elycheea** [comment]
1. **Pop-out styling**
@matthewgallo I think we changed this to `Toggletip` to avoid the redundant tooltip. https://github.com/carbon-design-system/ibm-products/pull/2873 Since our product teams provide their own `DatagridActions`, it might be good to have a good recommendation on `Toggletip`, `OverflowMenu`, or other `Popover` styles? 🤔 @Ashley-Bock I think this one is specific to the row size design review, but for the consistency of the Toolbar, may be a good topic to bring up? v2/Carbon 11 allows use of the newer `Toggletip` and `Popover` components, but v1/Carbon 10 only have `OverflowMenu`.

2. **Order of sizes**
I think this one is actually configurable by the users of the component so I think this is okay?

3. **Toolbar height**
@matthewgallo is this something we changed intentionally, something users have control over instead of us, or something that was missed. I could imagine this being a little bit tricky for some of the smaller sizes.

**Comment by elycheea** [comment]
@Ashley-Bock @matthewgallo So I went looking to figure out whether `Toggletip` or `Popover` makes more sense in this context. Then I stumbled upon #2527 which @AlexanderMelox and I happened to find a while back.

I think anything that drops down from the toolbar should be considered a “**disclosure**”[^1].

>Settings and filters follow the disclosure pattern by clicking an icon button that opens a popover. Interactive elements are often found in settings and filters in order to modify or adjust specific content. The disclosure pattern allows you to nest interactive elements inside of a popover while still being accessible.

So based on this, I think the original design with the `Popover` is most likely the way to go for now. @Ashley-Bock not sure if we need to add some context/guidance on the disclosure pattern in the PAL guidance, but I don’t think we have a dedicated Toolbar page anyway.

[^1]: [Disclosures](https://carbondesignsystem.com/patterns/disclosures-pattern/#settings-and-filter-menus
) via Carbon Design System.

**Comment by kristastarr** [comment]
Some comments about keyboard accessibility - mostly related to Settings.  I tried to capture in screen recording.  

1. In most cases, when you tab from Download button to Settings button, you are able to press space/enter to open the Settings popover correctly. However, sometimes when you tab to it, only a faint 1px blue outline appears around the button (which does not match the rest of the focus states), and then nothing happens when you press space, and focus is lost. After pressing tab twice, focus resumes on the settings button. I’ve tried to determine what pattern of actions causes it to work vs not work. I think it might be alternating between correct and incorrect, but I’m not 100% sure.

2. When you are able to correctly open the dropdown, you must press tab again - and the faint 1px blue focus state appears around settings, - then press tab a second time to enter the list before you are able to press up/down/L/R to navigate the list.   Focus should be present in the first list item after pressing space/enter to activate the popover.  Also as you press up/down arrows to cycle through the radio button options, the table itself moves up and down behind it.   

3. After using up and down to move focus to your selected radio button, pressing tab moves you to the “Primary button” but wondering if it would be better to press enter to make a selection, which would move focus to the settings button, then use tab to move to the primary button. I’m looking for some examples of best practices to reference.  

4. When popover is open and you tab to settings, it closes. However, if popover is open and you shift+tab to Download before interacting with the popover content, the popover remains open and overlaps with the Download tooltip. I’m thinking it should close so that what happens with shift+tab is consistent with what happens with tab.  
![Screenshot 2023-07-03 at 8 16 05 AM](https://github.com/carbon-design-system/ibm-products/assets/21047571/4b84562a-1973-40e7-8f5b-2ce2123d4fa5)


5. When Primary button has focus, and you press tab, focus is unknown, and then if you press tab again it lands on the next interactive element (the “Create new” button), instead of going directly to the Create new button. Is there a tab stop between those two that is hidden or moved do a different location with CSS? Maybe the items in the “Primary button” dropdown?

6. Visual things: 
The “Create new” text is not centered vertically in the button
The focus state on “View documentation”  looks weird since there is lots of white space on the right of the text as the focus indicator takes up the entire width of the “empty-state__content” container 
![Screenshot 2023-07-03 at 8 16 23 AM](https://github.com/carbon-design-system/ibm-products/assets/21047571/2316620d-0900-4b90-bfe2-174719e4081a)



https://github.com/carbon-design-system/ibm-products/assets/21047571/942acf3e-053f-4c2e-85f9-cc465299093a

**Comment by kristastarr** [comment]
Tested with Mac Voiceover - everything except Settings works well.  For Settings, after you click/activate the button, there is no information about the popover and it's status of open/closed, or it's contents and how to interact with them, so need to add some aria labels here.  
See https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-haspopup

**Comment by elycheea** [comment]
> 2. Focus should be present in the first list item after pressing space/enter to activate the popover.  Also as you press up/down arrows to cycle through the radio button options, the table itself moves up and down behind it.
> 4. When popover is open and you tab to settings, it closes. However, if popover is open and you shift+tab to Download before interacting with the popover content, the popover remains open and overlaps with the Download tooltip. I’m thinking it should close so that what happens with shift+tab is consistent with what happens with tab.
>    ![Screenshot 2023-07-03 at 8 16 05 AM](https://user-images.githubusercontent.com/21047571/250572423-4b84562a-1973-40e7-8f5b-2ce2123d4fa5.png)
> 5. When open, the popover should dismiss when Esc is pressed

Documented in the new issue (#3241).


> 1. However, sometimes when you tab to it, only a faint 1px blue outline appears around the button (which does not match the rest of the focus states), and then nothing happens when you press space, and focus is lost. After pressing tab twice, focus resumes on the settings button. I’ve tried to determine what pattern of actions causes it to work vs not work. I think it might be alternating between correct and incorrect, but I’m not 100% sure.

I wasn’t able to replicate this. Were you using a specific browser?

> 3. After using up and down to move focus to your selected radio button, pressing tab moves you to the “Primary button” but wondering if it would be better to press enter to make a selection, which would move focus to the settings button, then use tab to move to the primary button. I’m looking for some examples of best practices to reference.

No specific tasks for this one at this time but hopefully we’ll have a better idea about the approach as more people use the component.

> 6. When Primary button has focus, and you press tab, focus is unknown, and then if you press tab again it lands on the next interactive element (the “Create new” button), instead of going directly to the Create new button. I think the dropdown for "Primary button" is a tab stop even when it is not displayed.

I believe this is actually the whole data table body is its own tab stop. Don’t recall if there was a specific reason for it, but open to more discussion on whether to change that behavior. (Might have implications in other stories though.)

> 7. Visual things:
>    The “Create new” text is not centered vertically in the button
>    The focus state on “View documentation”  looks weird since there is lots of white space on the right of the text as the focus indicator takes up the entire width of the “empty-state__content” container

Not an issue with the Datagrid in particular — believe this came from an update in the Carbon buttons but should be something we can address separately. I think both of these stem from the `EmptyState` components though.

> 8. Primary button dropdown - you can correctly tab to the primary button and press enter/space to activate the dropdown, then first option in the dropdown has focus.  However, if you then shift+tab to try to return focus to the primary button, the entire dropdown menu takes focus and no interactions are available, you must press shift+tab again to return focus to the primary button.
> 9. When the primary button takes focus, it looks like the blue focus ring is present for a quick millisecond before disappearing.  I'm not sure if others are noticing this flicker.  The tooltip itself would meet criteria for focus indicator, but I think having the outline in addition would make it even more clear. so we could maybe consider keeping the focus ring as well, especially if others think the flicker of the outline is noticeable, or find a way to remove the outline altogether so there is no flicker.

Not prioritizing these for now since these will be replaced with the Carbon `MenuButton`.
