### ISSUE TITLE
Datagrid design review: Sorting

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#3118]
## Design review

- Component epic #1607 #2499 
- Links: [PAL guidance](https://pages.github.ibm.com/cdai-design/pal/components/data-table/overview) / [Storybook v2](https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid-datagrid-canary--sortable-columns) / [Storybook v1](https://v1-ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid-datagrid-canary--sortable-columns)
  - Sorting ([Carbon](https://www.carbondesignsystem.com/components/data-table/usage/#multi-select-and-batch-action))

---

### Standards

- [x] All pattern updates/changes/iterations have been discussed with the
      component developer
- [x] Patterns have been approved by either DSAG or another approving entity

### Pattern and behavior

- [x] The component behaves according to the guidelines set by the pattern
      maintainer
- [x] The component’s UI matches the pattern specifications set by the pattern
      maintainer
- [x] The component’s motion matches the specifications set by the pattern
      maintainer(s)
- [x] The UI produced is responsive, cross-browser, and responds to the
      currently set Carbon theme.
- [x] Colors, themes, sizes and additional props are true and correct, aligning
      with Carbon set tokens (unless otherwise specified by the pattern)
- [x] Paddings/margins/spacings are true and correct, in both desktop and mobile
      views

### Storybook

- [x] A functioning component renders in Storybook
- [x] The Storybook displays multiple scenarios that show how the component can
      be used
- [x] Changing props in the Storybook updates the component

Edited to reflect @Ashley-Bock’s review!
```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/ibm-products/issues/3227
- [ ] https://github.com/carbon-design-system/ibm-products/issues/3247
```

**Comment by elycheea** [comment]
@Ashley-Bock to help with this review 🙌

**Comment by Ashley-Bock** [comment]
### Standards

- [ ] All pattern updates/changes/iterations have been discussed with the component developer

- [ ] Patterns have been approved by either DSAG or another approving entity

### Pattern and behavior

- [ ] The component behaves according to the guidelines set by the pattern maintainer

- [ ] The component’s UI matches the pattern specifications set by the pattern maintainer

- [ ] The component’s motion matches the specifications set by the pattern maintainer(s)

- [ ] The UI produced is responsive, cross-browser, and responds to the currently set Carbon theme.

- [ ] Colors, themes, sizes and additional props are true and correct, aligning with Carbon set tokens (unless otherwise specified by the pattern)

- [ ] Paddings/margins/spacings are true and correct, in both desktop and mobile views

### Storybook
 
- [ ] A functioning component renders in Storybook

 - [ ] The Storybook displays multiple scenarios that show how the component can be used
 - [ ] Changing props in the Storybook updates the component

**Comment by Ashley-Bock** [comment]
No issues between guidance and storybook. Only thing to consider, do designers have to always signify which column the table is sorted by default? In storybook, it doesn't appear that it shows which column has the default sorting and the guidance doesn't mention it either.

**Comment by elycheea** [comment]
@Ashley-Bock I believe the default sort is actually unsorted. It might be the same as the “row index” in Storybook. @matthewgallo Don’t see any mention in our [docs](https://v1-ibm-products.carbondesignsystem.com/?path=/docs/ibm-products-components-datagrid-datagrid-canary--sortable-columns#sortable-columns) if we support default sort? (Linked v1 since v2 docs are undergoing the Storybook upgrade.)

**Comment by kristastarr** [comment]
The keyboard interactions look good.
 There are a few screenreader issues when testing with voiceover. 

1. Table description 
Currently voiceover provides only a vague description of the table.  Need to add `aria-label`, `aria-describedby`or `caption` to provide accessible description of the table
See: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/table_role

2. Aria sort
- Need to check markup of the table - should be using `aria-sort` so that the screenreader announces to the user that the table is sortable 

Current: ![Screenshot 2023-07-02 at 11 27 10 AM](https://github.com/carbon-design-system/ibm-products/assets/21047571/af21f712-32e8-4ce6-a585-437705397c24)

Current: ![Screenshot 2023-07-02 at 11 36 49 AM](https://github.com/carbon-design-system/ibm-products/assets/21047571/3c79bd1a-9635-4c12-a50a-a833608cc590)

Correct example from https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Advanced:
 ![Screenshot 2023-07-02 at 12 03 37 PM](https://github.com/carbon-design-system/ibm-products/assets/21047571/2978950a-c8f0-43d4-b1d8-868e0f5d18db)



3.  Row splitters:

- Row splitters are not interactible via keyboard focus alone, but are interactable via screen reader
- When interacting via screenreader use, the row splitters aren't working properly  - Was this worked on in a different PR maybe? 

Current: ![Screenshot 2023-07-02 at 12 06 03 PM](https://github.com/carbon-design-system/ibm-products/assets/21047571/81b6ba9e-506a-40b7-aa06-19dcf3796592)
Current: ![Screenshot 2023-07-02 at 12 06 56 PM](https://github.com/carbon-design-system/ibm-products/assets/21047571/1cf727bb-26cc-4900-b66b-8e6dc38754b9)

**Comment by kristastarr** [comment]
4. When using CNTRL+Option+L/R arrows to navigate horizontally through the table with the screen reader, it reads the the contents of a cell as a group, saying the same content three times.  Should be reading out just text.  I'm not sure why this is happening when navigating horizontally but not vertically 
![Screenshot 2023-07-02 at 12 33 39 PM](https://github.com/carbon-design-system/ibm-products/assets/21047571/0a6cc3a4-c5a6-430c-a435-e64207df4219)

Current:

**Comment by kristastarr** [comment]
Lmk if you want to talk through any of these issues if they are not clear by the descriptions 😄

**Comment by elycheea** [comment]
@kristastarr @matthewgallo The bit on row splitters — I think this is coming from the resizable columns feature. I think we should be able to re-add the resizing behavior so might be worth having you take a review at the behavior once we have that working again. Don’t think that one needs to be a part of the Sorting followup though.

Not sure if we have a good solution of the groups at the moment either ... I’m guessing it’s also part of a number of other extensions. Might need some ideas on how we approach this. How critical do you think this one is for our initial release? :thinking:

**Comment by kristastarr** [comment]
For the row splitters, yes I think it makes sense to fix it on the resizable columns feature since that impacts multiple other components.

For the groups - I don't think I delved into the code for this one, but can take a look - did you guys see what's causing them to be "grouped"?

**Comment by elycheea** [comment]
Opened a new issue for investigating why cells are being interpreted as groups so we can close this one!
