### ISSUE TITLE
NestedRows (Datagrid): layout issues in row expander

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#3240]
## What package(s) are you using?

- [X] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

There are layout issues with the row expander when using the nested row extension of the Datagrid.
> Is this issue related to a specific component?

Datagrid
> What did you expect to happen? What happened instead? What would you like to
> see changed?

No style/layout issues with row expander.
Row expander icon should match alignment from the [Carbon DataTable](https://react.carbondesignsystem.com/?path=/story/components-datatable-expansion--default).

> What browser are you working in?

Chrome
> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

Latest
> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

N/A
## Steps to reproduce the issue

1. See [nested row](https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid-datagrid-canary-extensions-nestedrows--nested-rows-usage-story) or [expanded row](https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid-datagrid-canary-extensions-expandablerow--expandable-row-story) extension in storybook

<img width="1369" alt="image" src="https://github.com/carbon-design-system/ibm-products/assets/10215203/f13464cb-09be-43c7-9faa-f99455a831bd">

Most likely the same fix but should ensure that both are addressed since they are similar.

```[tasklist]
### Tasks
- [ ] Fix expander alignment in row expansion extension
- [ ] Fix expander alignment in nested row extension
```
