### ISSUE TITLE
Simplify storybook controls to simple/intuitive examples without node components

### ISSUE THREAD

**Issue by glapadre** [carbon-design-system/ibm-products#3360]
## What will this achieve?
Create a more seamless and intuitive experience for users to use the controls in storybook. This will allow users to easily edit a control with simple editable text fields, dropdown menus (with predefined well thought out examples specific for that component), or toggles for true/false examples. 

We want to move away from having the user "set object" where it is not clear what even goes into the object causing bad UX and leading some users to not use storybook as it is intended. 

## How will success be measured?

Going through each pattern/component and testing the controls, this will be a manual process. 

### Migrate AWAY from controls like these:
<img width="383" alt="Screenshot 2023-08-04 at 10 22 29 AM" src="https://github.com/carbon-design-system/ibm-products/assets/25260547/07a24791-732c-473d-b8a4-16bc38e73e8a">

<img width="398" alt="Screenshot 2023-08-04 at 10 17 43 AM" src="https://github.com/carbon-design-system/ibm-products/assets/25260547/68719949-0388-498e-8f6f-5af633c29928">

### Migrate TO controls like these:
<img width="392" alt="Screenshot 2023-08-04 at 10 19 30 AM" src="https://github.com/carbon-design-system/ibm-products/assets/25260547/eeb01714-da85-44ae-b3d4-ce235f64455a">

<img width="391" alt="Screenshot 2023-08-04 at 10 19 34 AM" src="https://github.com/carbon-design-system/ibm-products/assets/25260547/fb0ccb05-4a4a-4ed2-be37-cba31e1350c4">

```[tasklist]
### Tasks
- [ ] Simplify storybook controls: Tag set (component)
- [ ] Simplify storybook controls: Cards (component)
- [ ] Simplify storybook controls: Options tile (component)
- [ ] Simplify storybook controls: Page header (component)
- [ ] Simplify storybook controls: Side panel (component)
- [ ] Simplify storybook controls: Tearsheet (component)
- [ ] Simplify storybook controls: DataSpreadsheet (component)
- [ ] Simplify storybook controls: Datagrid (component)
- [ ] https://github.com/carbon-design-system/ibm-products/issues/3797
- [ ] https://github.com/carbon-design-system/ibm-products/issues/3447
- [ ] https://github.com/carbon-design-system/ibm-products/issues/3830
- [ ] Simplify storybook controls: Edit and update (pattern)
- [ ] Simplify storybook controls: Empty state (pattern)
- [ ] https://github.com/carbon-design-system/ibm-products/issues/3944
- [ ] https://github.com/carbon-design-system/ibm-products/issues/3973
- [ ] Simplify storybook controls: HTTP errors (pattern)
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4014
- [ ] Simplify storybook controls: Notifications (pattern)
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4020
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4023
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4026
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4029
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4027
- [ ] Simplify storybook controls: Web terminal (pattern)
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4028
- [ ] Simplify storybook controls: ActionBar (internal)
- [ ] Simplify storybook controls: ActionSet (internal)
- [ ] Simplify storybook controls: BreadcrumbWithOverflow (internal)
- [ ] Simplify storybook controls: ButtonMenu (internal)
- [ ] Simplify storybook controls: ButtonSetWithOverflow (internal)
- [ ] Simplify storybook controls: ComboButton (internal)
- [ ] Simplify storybook controls: ExampleComponent (internal)
- [ ] Simplify storybook controls: FilterSummary (internal)
- [ ] Simplify storybook controls: TearsheelShell (internal)
```
