### ISSUE TITLE
Novice to pro: new Checklist component

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#3396]
# Novice to pro: new Checklist component

## Brief description

The **Checklist** tracks a user's progress much like Your Learning or WalkMe. Each item in the list can be clickable, and each item has an icon that defines the item's state as "not started", "in progress", and "complete".

## Details

_[Novice to pro](https://pages.github.ibm.com/cdai-design/pal/novice-to-pro/overview) is a continuous learning framework aimed to orient, onboard, explain, educate, and cultivate novice users into high-functioning power users._

### Links to other materials

[Figma](https://www.figma.com/file/hUBwrcf6BxYOVBEPd3cR4t/Novice-to-Pro%3A-Checklist?node-id=883%3A52453&mode=dev)

![image](https://github.com/carbon-design-system/ibm-products/assets/52505287/d7789a9a-f25f-47f5-899d-22aa730ece3e)

## Design Maintainer(s)

- Shelley Dignum
- Bridget Ndege

## Tasks

Before starting work on this epic, please review and complete the following.

- [x] Initial review of design/existing code

### Working in Carbon for IBM Products package

- [x] Have you reviewed our [contribution guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/.github/CONTRIBUTING.md)?
- [x] Have you noted our [code guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/docs/CODE_GUIDELINES.md)?
- [x] Did you use the CLI to scaffold your new component?
