### ISSUE TITLE
Add example for Datagrid table headers as tabs

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#3439]
# Enhancement to Datagrid table headers

## Brief description

> Some tables require tabs so that the user directly can switch between different content of the table. Those tabs are placed directly on top of the toolbar. We use Carbon’s container tabs. In that case we recommend that tabs replace the default table header. Make sure that labels are clear and concise.

## Details

[Link to design](https://pages.github.ibm.com/cdai-design/pal/components/data-table/headers/usage/#tabs-in-a-table-header)

### Links to other materials

See [contained tabs](https://react.carbondesignsystem.com/?path=/story/components-tabs--contained) from Carbon.

## Design maintainer(s)

- Ashley Bock

## Tasks

Before starting work on this epic, please review and complete the following.

- [ ] Initial review of design/existing code

### Working in Carbon for IBM Products package

- [ ] Have you reviewed our
      [contribution guidelines](https://github.com/carbon-design-system/ibm-products/blob/master/.github/CONTRIBUTING.md)?
- [ ] Have you noted our
      [code guidelines](https://github.com/carbon-design-system/ibm-products/blob/master/docs/CODE_GUIDELINES.md)?
- [ ] Did you use the CLI to scaffold your new component?

```[tasklist]
### Tasks
- [ ] Add table header story using contained tabs
- [ ] Tabs should replace the default table header
- [ ] Examples should use clear and concise labels
```

**Comment by ljcarot** [comment]
Create a TanStack example for this.

**Comment by ljcarot** [comment]
We've been investigating [TanStack ](https://tanstack.com/table/latest)[Table](https://tanstack.com/table/latest), a third-party, open-source offering, which provides extensive data table capabilities surpassing what our Carbon Datagrid offers. It provides much more flexibility and customization. TanStack Table is headless which means it can easily be added alongside Datagrid component in your product or application. The benefits of more flexibility for product teams and less maintenance for Carbon makes it a win win. Lastly, it is available in multiple frameworks including [React](https://github.com/carbon-design-system/tanstack-carbon/tree/main/react#readme) and [Web Component](https://github.com/carbon-design-system/tanstack-carbon/tree/main/web-components#readme) so it provides an option to non-React product teams.

For these reasons, we have decided to transition from building our own custom table component to using an example-based approach with TanStack Table. Datagrid will still exist in our library for existing teams but we are announcing the deprecation* of the Datagrid component in v2.54.0 release so teams can begin to work through the transition. Details about how to use both Datagrid and TanStack together can be found [here](https://github.com/carbon-design-system/tanstack-carbon/tree/main). 

*Deprecation means that no new features will be added however sev 1 and sev 2 bugs will be supported.
