### ISSUE TITLE
Add support for resizing multiple Datagrid(?) columns at once

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#3515]
Originally from #1923 
We should do some evaluation on _data tables_ to determine if this makes sense in the Datagrid context. Some of the interactions described feel more akin to a DataSpreadsheet.

### Desired behavior
- [ ] Hold <kbd>Shift</kbd> and hover over the right side of any column header until a horizontal split cursor appears
  a. Drag the column line to set the desired width manually
  b. Double click the column line to resize all visible (or selected??) columns to fit to content

**Can we facilitate a comparable experience via keyboard?**

![resizing_2columns](https://user-images.githubusercontent.com/5809654/163623808-8ea76600-7142-4e45-be50-0c6f45e52fe5.gif)

```[tasklist]
### Tasks
- [ ] Evaluate whether this interaction is appropriate for data tables (or data spreadsheets)
- [ ] Work with design to define a comparable experience for keyboard users
```
