### ISSUE TITLE
Implement CSS logical properties

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#3556]
Discovered through #3495 — it appears that [`stylelint-config-carbon@1.15.0`](https://github.com/carbon-design-system/carbon/releases/tag/v11.38.0) introduces CSS logical properties, part of the RTL improvements they’ve been working through.

Probably a larger initiative for us to consider as well, but don’t believe these changes seem too widespread for us to update in one of our routine dependency updates.

### Tasks
- [x] https://github.com/carbon-design-system/ibm-products/issues/5236
- [x] Remove local stylelint in favor of `stylelint-config-carbon`
- [ ] Replace CSS properties with logical counterparts
- [ ] `yarn lint:styles`

**Comment by elycheea** [comment]
Could leverage VRT to aid with the before/after.

**Comment by ljcarot** [comment]
Is this still in review or complete? @kennylam

**Comment by aubrey-oneal** [comment]
Check in on whether this is blocked by Percy.

**Comment by ljcarot** [comment]
Okay to close @elycheea ?

**Comment by elycheea** [comment]
@ljcarot The PR is still open and pretty old.

After changing the base branch to `main`, there’s actually several conflicted files so I recommend we pop this one back to backlog for the new year and we remake the changes on a new branch since this was originally pointing to the `percy-integration` branch.

**Comment by AlexanderMelox** [comment]
https://github.com/carbon-design-system/ibm-products/pull/5315
