### ISSUE TITLE
feat(Datagrid): Allow user to pass in custom `filterType` to useDatagrid

### ISSUE THREAD

**Issue by AlexanderMelox** [carbon-design-system/ibm-products#3670]
## What will this achieve?
This will allow users to include their own custom filtering methods inside of useFiltering

## How will success be measured?
User should be able to pass in a custom filterType

```[tasklist]
### Tasks
- [ ] Add new `custom` property to `filterTypes` in `useFiltering` hook
- [ ] Render `custom` filter component in `useFilters`
- [ ] New filter data structure will need to be updated to reflect the `custom` property
```

**Comment by elycheea** [comment]
From backlog Nov 9, we are wondering if this can be after the initial filtering extension release as an enhancement.

**Comment by elycheea** [comment]
Could this enhancement also be a way to cover #3713 ?

**Comment by elycheea** [comment]
@matthewgallo to add more detail on acceptance criteria.

**Comment by ljcarot** [comment]
We've been investigating [TanStack ](https://tanstack.com/table/latest)[Table](https://tanstack.com/table/latest), a third-party, open-source offering, which provides extensive data table capabilities surpassing what our Carbon Datagrid offers. It provides much more flexibility and customization. TanStack Table is headless which means it can easily be added alongside Datagrid component in your product or application. The benefits of more flexibility for product teams and less maintenance for Carbon makes it a win win. Lastly, it is available in multiple frameworks including [React](https://github.com/carbon-design-system/tanstack-carbon/tree/main/react#readme) and [Web Component](https://github.com/carbon-design-system/tanstack-carbon/tree/main/web-components#readme) so it provides an option to non-React product teams.

For these reasons, we have decided to transition from building our own custom table component to using an example-based approach with TanStack Table. Datagrid will still exist in our library for existing teams but we are announcing the deprecation* of the Datagrid component in v2.54.0 release so teams can begin to work through the transition. Details about how to use both Datagrid and TanStack together can be found [here](https://github.com/carbon-design-system/tanstack-carbon/tree/main). 

*Deprecation means that no new features will be added however sev 1 and sev 2 bugs will be supported.
