### ISSUE TITLE
Condition builder - Preview (experimental) 

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#3776]
# Condition builder

## Brief description

Goal: Condition Builder is available as Experimental in code, in Figma kit and with Usage docs.

## Details

[Design issue](https://github.ibm.com/CDAI-design/pal/issues/349) (internal)
[Link to Design]() [Link to example or existing component]()

### Links to other materials

1. [Figma file](https://www.figma.com/file/c1TS2Myo4E2OWnA0Yhg8jb/Condition-builder-concepts?type=design&node-id=1120%3A354291&mode=design&t=WLsp1mmmegYD5QfE-1) - Includes sketches and process

2. [Guidance](https://www.figma.com/proto/vyKGt5HsLCghk2CiGLcS95/Condition-Builder-Component---Usage-Guidance?type=design&node-id=1-2944&t=bUil5EXJeDBaa3ii-6) 

3. [Visual Design Figma file](https://www.figma.com/file/LBvWjDAhCQxoQ67eCbN8PU/Condition-Builder-component---Visual-Design---Sep-2023?type=design&node-id=0-1&mode=design&t=RQkSmS9Rq9n84inH-0)
## Design Maintainer(s)

- @My-Money29 
- @cate-wilcox

## Tasks

Before starting work on this epic, please review and complete the following.

- [ ] Initial review of design/existing code

### Working in Carbon for IBM Products package

- [ ] Have you reviewed our
      [contribution guidelines](https://github.com/carbon-design-system/ibm-products/blob/master/.github/CONTRIBUTING.md)?
- [ ] Have you noted our
      [code guidelines](https://github.com/carbon-design-system/ibm-products/blob/master/docs/CODE_GUIDELINES.md)?
- [ ] Did you use the CLI to scaffold your new component?

```[tasklist]
### Acceptance criteria
- [x] Review [conditions builder prototype](https://github.ibm.com/CDAI-UX-Engineering/dsag-condition-builder-prototype) and code
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4577
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4916
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4900
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5494
- [ ] Condition builder: Draft Style docs
- [x] Condition builder: Draft Code docs
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5044
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5042
- [ ] Enrich the user interaction aspect utilizing micro-interactions
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5043
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5426
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5495
```

```[tasklist]
### Release review r1 and outstanding issues
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5706
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5687
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5496
- [ ] https://github.com/carbon-design-system/ibm-products/issues/6032
- [ ] https://github.com/carbon-design-system/ibm-products/issues/6124
```

**Comment by elycheea** [comment]
@amal-k-joy Just FYI — still need to work out details with @My-Money29 and @janhassel before we start up work, but feel free to look at the prototype to get acquainted with it.

**Comment by My-Money29** [comment]
@amal-k-joy, Hi :)

Updated the issue with links to resources.

We are currently working on updating the visual design file to match the new design iteration.

When you are ready, please schedule a meeting so that we can get familiarized and form a plan.

**Comment by elycheea** [comment]
Something to keep in mind is that each of these needs to support globalization so we should avoid hardcoded strings if we can.
