### ISSUE TITLE
Improve Datagrid column customization stories

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#3832]
> 2. Tooltip for 'customize columns' icon should be set to Position-Bottom, instead of Position-left.
> 3. Inconsistent naming - Clicked the"customize columns" icon and a tearsheet labeled "Customize display" popped up.

_Originally posted by @My-Money29 in https://github.com/carbon-design-system/ibm-products/issues/3663#issuecomment-1778689875_
            
```[tasklist]
### Tasks
- [x] Change Customize columns `tooltipAlignment` to `bottom` or `bottomLeft`
- [x] Update Tearsheet title to `Customize columns`
- [ ] Review with Tomer @My-Money29
- [ ] Review tests if needed
```
