### ISSUE TITLE
Start documenting governance model for community package

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#4042]
```[tasklist]
### Tasks
- [ ] Document notes from previous calls with Cloud
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4247
- [ ] Add more notes on how we approach this — and discussions with other teams
```

**Comment by elycheea** [comment]
@My-Money29 Can also help tie this back to the contribution model too.

**Comment by My-Money29** [comment]
@davidmenendez hi! Scheduled a meeting for us, next week. Please, post an update (if there is one) on this issue prior to our meeting

**Comment by My-Money29** [comment]
Braindump from meeting with @elycheea, yesterday:

 ### Why are we meeting?

- Officially vetting an asset via DSAG takes time.
- Lets give them more room - and call this a community asset - share code that might not fit through DSAG
- Legacy products need to contribute assets so that they move forward - Unblock those teams. Move a legacy component to a place where they can access it under v11.
- Experimental code = Community package
	- People want to contribute but they don't know how.
	- Why are you asking me for design?! I just want to contribute the code!
- It's about accelerating the contribution process of the code. 

### What do we want to create?

**The end result is to:**
- Define the criteria for the Community Package and the Canary package, and communicate that via the Storybook and the website.
  
	- We need to define the difference between what's [[Canary]] and [[Community Package]]. When does an item meet the Canary standards?
		- Criteria suggestions:
			- Analytics - Telemetry - What's in use rather than what's needed.
			- What's needed.
			- Business aspect (PLG Products) - It's not just the number of products it's the quality and high status of products.
			- Is there a workgroup for this asset? It has code and design support, why stop it?! The workgroups often align with our Priorities. 
			- Only code exists
			- Only design exists
			- Accessibility standards - defined/undefined?
		- Following the D&UX review measurements and the Experience Standards practice, perhaps a score could be given to each criteria, and an item that meets the score (or don't) won't make it to higher tiers. 
			- Tier 3 - Community
			- Tier 2 - Canary
			- Tier 1 - PAL / Carbon
		- Perhaps an asset that doesn't meet the score is nominated for depreciation.
			- What is the right balance between deprecating and keeping an asset?


### Questions:
- What more criteria does David think are missing/needs to be excluded?
- What is the responsibility of the contributor if they bring an asset to the Community Package?
- The community library would be based on react. Right, David?
- What are the (MVP standards?) code standards for the community package?
- When can we mine data from the Telemetry Package?
- What makes it to the PAL and what to Carbon?

**Comment by My-Money29** [comment]
Recording "[Pal Experimental Discussion](https://ibm.box.com/s/4pynezgcbto50o3xtt2rfo9en7mlb25y)" - (Feb 7) - David, Elysia, Jean, Jeff, Linda

**Comment by davidmenendez** [comment]
@My-Money29 i think we talked about some of this stuff already, but here are some thoughts i have regarding the questions asked

> How do we know if an asset would be eventually adopted my the PAL or not?

I think this is something that ultimately comes down to DSAG? It also probably depends on which path a certain component takes. If the component is spurred by a designer then odds are that we have more concrete design assets to accompany the work, which presumably has gone through some sort of design approval process in the past. if it's a developer who's bringing a component then presumably they're coming with no direct design assets or it's been hobbled together from various designs similarly to how filtering was, in which case a designer will probably have to be assigned to assist in finalizing design and UX assets.

> Is the community a pathway to be part of the PAL?

I'm not 100% sure on the bureaucracy of being adopted into a PAL, but I would like to think that It definitely can and should be seen as an alternative path to being added.

> We don't want a team to adopt an asset that's not being supported.

This certainly seems like a major discussion point. While the community package should be seen as an opportunity to experiment with different pattern and component approaches ultimately they are still not PAL "approved." I'm not sure what the best way is to convince developers and consumers to implement something that may ultimately never be adopted and may be deprecated. Usage of these components from the early stages will ultimately be helpful to helping throughout the design and development lifecycle, so it  benefits us to encourage consumers to use these particular components. Ultimately I think this responsibility lies with the designers and developers of the products who utilize these components to know the risks and to be ready to pivot if something should be declared unfit for adoption.

I like the way that the Material UI team has worded their [labs documentation](https://mui.com/material-ui/about-the-lab/) to address up front the shortcomings of using experimental components and I think a similar approach can be used for our purposes.

**Comment by My-Money29** [comment]
Following our meeting with @elycheea and @davidmenendez, last week, I've updated the [Community Package - Governance model](https://app.mural.co/t/dsagmembers0371/m/dsagmembers0371/1707921505141/8e99b0e16f4de01f69067397469e09552cd2fc94?sender=ub561019164a5695f34b10832) details to reflect our discussion. 

### Criteria:
1. Dual-Entry Asset: 
- Only code
- Only design

   2. Governance:
Expectations from contributing body:
- Maintenance/Deprecation of asset.
- Open source training
- Due diligence
- Not publishing anything proprietary - You made sure you're not bringing code that you shouldn't
- No DSAG/DSIT approval process while in the Community Package

Expectations from IBM Products team:
- Setup Telemetry to mine metrics
- What else?

3. General practices:
- React
- Carbon 11
- Carbon's Guidance (Carbon dev handbook) 





![Image](https://github.com/carbon-design-system/ibm-products/assets/101175720/e6960ff4-f8b5-45d5-b7a5-f63adc83bcd1)





### Next step:
- Define the governance expectations from IBM Products team.

**Comment by elycheea** [comment]
This effort will consolidate with consolidate with Carbon Labs in time so closing this as no longer planned.
