### ISSUE TITLE
New Component: DelimitedList

### ISSUE THREAD

**Issue by paul-balchin-ibm** [carbon-design-system/ibm-products#4058]
# DelimitedList

_Please refer to #4052 for more details about migrating legacy Security components to **Products v2**._

## Brief description

Migrate **DelimitedList** from `Products v1 / Security / DelimitedList` to **Products v2**. 

References: [GitHub](https://github.com/carbon-design-system/ibm-products/blob/main_v1/packages/security/src/components/DelimitedList/DelimitedList.js), [Storybook](https://v1-ibm-products.carbondesignsystem.com/?path=/story/security-components-delimitedlist--default).

For migration purposes:
- New component architecture must meet **Products v2**'s code specifications.
- The design and behavior of version `v2` must match version `v1` exactly.

## Tasks

Before starting work on this epic, please review and complete the following.

- [x] Initial review of design/existing code. Refer to existing component specifications: [GitHub](https://github.com/carbon-design-system/ibm-products/blob/main_v1/packages/security/src/components/DelimitedList/DelimitedList.js), [Storybook](https://v1-ibm-products.carbondesignsystem.com/?path=/story/security-components-delimitedlist--default).

### Working in Carbon for IBM Products package

- [x] Have you reviewed our [contribution guidelines](https://github.com/carbon-design-system/ibm-products/blob/master/.github/CONTRIBUTING.md)?
- [x] Have you noted our [code guidelines](https://github.com/carbon-design-system/ibm-products/blob/master/docs/CODE_GUIDELINES.md)?
- [x] Did you use the CLI to scaffold your new component?
