### ISSUE TITLE
Add documentation on migrating from `UserProfileImage` to `UserAvatar`

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#4074]
Some examples of migration guides
- [Carbon v11 guide](https://github.com/carbon-design-system/carbon/blob/main/docs/migration/v11.md#carbonthemes)
- Security migration notes[^1][^2]

[^1]: [Truncated list](https://github.com/carbon-design-system/ibm-products/pull/4139)
[^2]: [Security migration guide](https://github.com/carbon-design-system/ibm-products/pull/4437)

```[tasklist]
### Tasks
- [x] Document changes between `UserProfileImage` and `UserAvatar` (see [here](https://github.com/carbon-design-system/ibm-products/pull/6223/commits/7497bed5674eb1f9f0dfb621771234399e447b4d#diff-62387a7d98fcac83a4ba86f3b8a8f9ed8dfb934d958d7d84b031b54f4b279146L14))
- [ ] Add link from `UserProfileImage` to `UserAvatar`
- [ ] Add migration notes in section of `UserAvatar` mdx
- [ ] Include a link to the codemod
```

**Related**
#6388

**Comment by elycheea** [comment]
@davidmenendez Can we decouple the documentation on migrating the `UserProfileImage` to `UserAvatar` from the deprecation? We are going to wait to actually deprecate `UserProfileImage` since it’s currently stable.
