### ISSUE TITLE
Add a deprecation notice on `HTTPError` components

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#4083]
📌  **Note:** This should only be updated _after_ the release review is completed in the original issue. This should occur as a part of the formal release from `canary`. 📌 

--

With the updates to the `FullPageError` pattern, we should deprecate the `HTTPError403`, `HTTPError404`, and `HTTPErrorOther` components.

We can add a deprecation warning by adding 

```jsx
ComponentName.deprecated = {
  level: 'warn',
  details: `Please replace ${componentName} with _______`,
};
```

In this case something like, 

```jsx
HTTPError403.deprecated = {
  level: 'warn',
  details: `Please replace ${componentName} with FullPageError`,
};
```

Additionally, we recommend including ~an [`ActionableNotification`](https://react.carbondesignsystem.com/?path=/docs/components-notifications-actionable--overview)~ a [`StaticNotification`](https://react.carbondesignsystem.com/?path=/docs/experimental-unstable-staticnotification--overview) in the component story. (See [ButtonMenu](https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-internal-buttonmenu--button-menu) for example).

```[tasklist]
### Tasks
- [x] Add deprecation warnings to HTTPError403
- [x] Add deprecation warnings to HTTPError404
- [x] Add deprecation warnings to HTTPErrorOther
```
