### ISSUE TITLE
Tag overflow

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#4085]
# Tag overflow

## Brief description

This is an enhancement to the existing `TagSet`, but we will introduce this as a new component called the `TagOverflow` to accommodate the different use cases that this component can be used for.

## Details

[Link to design](https://pages.github.ibm.com/cdai-design/pal/components/tag-overflow/usage/)

### Links to other materials

e.g. sketch files, icons, images, prototypes

## Design maintainer(s)

- Laura Marshall

## Tasks

Before starting work on this epic, please review and complete the following.

- [ ] Initial review of design/existing code

### Working in Carbon for IBM Products package

- [ ] Have you reviewed our
      [contribution guidelines](https://github.com/carbon-design-system/ibm-products/blob/master/.github/CONTRIBUTING.md)?
- [ ] Have you noted our
      [code guidelines](https://github.com/carbon-design-system/ibm-products/blob/master/docs/CODE_GUIDELINES.md)?
- [ ] Did you use the CLI to scaffold your new component?

```[tasklist]
### Acceptance criteria
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4087
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4086
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4090
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4387
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4758
- [ ] Add support for view all ~tags modal~
- [ ] Replace custom popover with operational tag?
```

```[tasklist]
### Review process
- [ ] Design review
- [ ] Accessibility review
- [ ] Release review
- [ ] Put deprecation notice on the original `TagSet`???
```

**Comment by elycheea** [comment]
@szinta this one admittedly will require some discussion in terms of how we decide to actually implement this. I believe @davidmenendez also shared some thoughts recently on potential need to refactor parts of the `TagSet`[^1].

@davidmenendez Can we go into more detail on this sometime so we don’t bring over existing debt?

[^1]: https://github.com/carbon-design-system/ibm-products/pull/3997#pullrequestreview-1842053477

**Comment by elycheea** [comment]
Need to validate whether we need to support multiliine in TagOverflow.

**Comment by ljcarot** [comment]
@elycheea When you get a chance, can you please evaluate this Epic and determine if it is still relevant? Thx cc: @RichKummer

**Comment by elycheea** [comment]
@ljcarot @RichKummer I think we can close this original epic since this is taking shape as an overflow utility now as part of #6274 and is being refactored in #6601.
