### ISSUE TITLE
Add a deprecation notice on `UserProfileImage`

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#4140]
> [!WARNING]
> We should try to time this deprecation with the website comms from @RichKummer.

With the updates to the `UserAvatar` component, we should deprecate the original `UserProfileImage` component.

We can add a deprecation warning by adding 

```jsx
ComponentName.deprecated = {
  level: 'warn',
  details: `Please replace ${componentName} with _______`,
};
```

In this case something like, 

```jsx
UserProfileImage.deprecated = {
  level: 'warn',
  details: `Please replace ${componentName} with UserAvatar`,
};
```

### Tasks
- [x] Move user profile image to `Deprecated` section in Storybook
- [x] Update deprecation notice in Storybook docs
  - [x] Include [codemod instructions](https://react.carbondesignsystem.com/?path=/docs/deprecated-unstable-staticnotification--overview)
  - [x] Include link to `UserAvatar`
- [x] Add deprecation annotation in stories
- [x] Add `@deprecated` and `.deprecated` to `UserProfileImage.tsx`
- [x] Update tests for `console.warn`

**Comment by matthewgallo** [comment]
Telemetry usage shows high usage for `UserProfileImage`, will revisit next sprint.

**Comment by elycheea** [comment]
Our revised plan that we discussed back in December was actually that we would wait until the next major to formally deprecate `UserProfileImage` but add the codemod/migration docs instead. I’ve added the migration steps from David’s PR to the refinement steps for future reference.

**Comment by elycheea** [comment]
So after reviewing recent telemetry, we do think it makes sense to deprecate the `UserProfileImage` in the current version as the Core team does as soon as a new version is available. We’ll update the communications to help teams adopt the latest.

Should review whether we would remove in the next major or next major + 1.
