### ISSUE TITLE
DataSpreadsheet refactor

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#4186]
Followup from DataSpreadsheet release review that we never got around to closing out.

We can recheck current code coverage, but believe @matthewgallo and @davidmenendez both contributed to get this to about 80-90%

* ~a lot of missing code coverage~
* `handleKeyPress` has a lot of redundant code
* not a deal breaker, but considering how large the file is a lot of the handler initializers may want to be moved into separate util or hook files at some point
* if you command click the same 2 cells over and over again they just keep getting added to the selection
* `isHoldingCommandKey` is defined a few different times, so it should probably be a utility

_Originally posted by @davidmenendez in https://github.com/carbon-design-system/ibm-products/issues/2324#issuecomment-1339960322_
            
```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4187
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4188
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4241
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4597
```
