### ISSUE TITLE
New Component : Icon button bar

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#4240]
# Icon button bar

_Please refer to #4052 for more details about migrating legacy Security components to **Products v2**._

## Brief description

This component is to be migrated from the `@carbon/ibm-security` package (found in `main_v1` packages/patterns) to our `main` branch and is part of the initiative documented in #4052 and #4036.

Migrate `IconButtonBar` from `Products v1 / Security / IconButtonBar` to Products v2.

References: [GitHub](https://github.com/carbon-design-system/ibm-products/blob/main_v1/packages/security/src/components/IconButtonBar/IconButtonBar.js), [Storybook](https://v1-ibm-products.carbondesignsystem.com/?path=/story/security-patterns-iconbuttonbar--default).

## Details

[Link to Security version](https://v1-ibm-products.carbondesignsystem.com/?path=/story/security-patterns-iconbuttonbar--default)

**Notes on this migration**
For this initial release, we will follow these two principles to keep working moving forward and to unblock teams reliant on the older package —
1. **Zero design changes from Security to Products.** This make it easier to compare old component to new component. Any design updates can as followup.
2. **New components must meet Products’ code specs.** Rather than copy and paste old code from Security to Products, we will refactor it to ensure they’re up to date.

Summary from @paul-balchin-ibm’s initial review —

> ### IconButtonBar
> 
> [GitHub](https://github.com/carbon-design-system/ibm-products/blob/main_v1/packages/security/src/components/IconButtonBar/IconButtonBar.js), [Storybook](https://v1-ibm-products.carbondesignsystem.com/?path=/story/security-patterns-iconbuttonbar--default)
> 
> #### TLDR
> 
> - **✓** Follows **Carbon for IBM Products** component architecture.
> 
> #### PROBLEMATIC IMPORTS
> 
> ```
> import { OverflowMenu, OverflowMenuItem } from '../..';
> import IconButton from '../IconButton';
> ```
> 

### Links to other materials

e.g. sketch files, icons, images, prototypes

## Design contact(s)

- @cameroncalder

## Tasks

Before starting work on this epic, please review and complete the following.

- [ ] Read the [Overview of the Security migration](https://github.com/carbon-design-system/ibm-products/issues/4052)
- [ ] Initial review of design/existing code

### Working in Carbon for IBM Products package

- [ ] Have you reviewed our
      [contribution guidelines](https://github.com/carbon-design-system/ibm-products/blob/master/.github/CONTRIBUTING.md)?
- [ ] Have you noted our
      [code guidelines](https://github.com/carbon-design-system/ibm-products/blob/master/docs/CODE_GUIDELINES.md)?
- [ ] Did you use the CLI to scaffold your new component?

```[tasklist]
### Acceptance criteria
- [ ] Migrate component to `main` under IBM Products
- [ ] Document `IconButtonBar` changes for migration ([see example](https://github.com/carbon-design-system/ibm-products/pull/4139))
```
