### ISSUE TITLE
AI Docs for Slug Props

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/ibm-products#4431]
Following the lead of the React storybook and how the Slug component and component slug props are getting documented (https://github.com/carbon-design-system/carbon/pull/15812), let's add similar documentation for AI-enhanced Carbon for IBM Products components.

**Acceptance criteria**

The list of slug-enabled components that need developer documentation can be found here: https://airtable.com/appCAqlGVN8tRUbAp/shr71ZyLlIGORz3Vh/tblHqPusgkK8hIeHo
```[tasklist]
### Remaining components using slug without docs
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5306
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5307
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5308
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5368
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5369
- [x] Datagrid
```

**Comment by matthewgallo** [comment]
***Note: we'll need to wait for the renaming (`slug` --> `aiLabel`) to happen before working on this.
