### ISSUE TITLE
Add AI kit enhancements to the IBM Products Figma libraries

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/ibm-products#4432]
For each of the Carbon for IBM Products components that have been enhanced with the AI slug gradient:

https://airtable.com/appCAqlGVN8tRUbAp/tblHqPusgkK8hIeHo/viwPD80oVVWwAk0xA?blocks=hide

Following this issue for how the Carbon core libraries are getting updated:

https://github.com/carbon-design-system/carbon-design-kit/issues/766

The IBM Products Figma libraries need updated to include the slug variants. @aagonzales and @RichKummer to coordinate what this effort looks like.
```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5048
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5049
- [ ] [AI kit enhancement] Datagrid (does not exist in Figma kit) ⚠️
```
