### ISSUE TITLE
C4P AI Usage Docs 🤖 

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/ibm-products#4433]
For each of the Carbon for IBM Products components that have been enhanced with the AI slug gradient:

https://airtable.com/appCAqlGVN8tRUbAp/tblHqPusgkK8hIeHo/viwPD80oVVWwAk0xA?blocks=hide

Following this issue for how the Carbon core libraries are getting updated:

https://github.com/carbon-design-system/carbon-website/issues/3925

The Carbon for IBM Products website likely needs updated as well so that we have consistent AI slug and gradient documentation.

Tasks:
- [x] Get a list of components that have the slug (look in Storybook)
- [x] Get Anna's template/list of documentation that has changed
- [ ] Create an issue for each page which requires guidance

---

## AI docs Template
[Original Carbon issue link](https://github.com/carbon-design-system/carbon-website/issues/4007)

### Usage tab
[See example in Figma](https://www.figma.com/file/OJwBWBlctEgm9zYUCYbhu3/Carbon-for-AI-%E2%80%93-website-integration?type=design&node-id=80%3A7220&mode=design&t=XPoeQ0K8Ea0VbhbW-1)

- Add inline notification to the top of the page under intro paragraph. The link should go to the AI component’s storybook example.
- Add “AI presence” to the anchor links.
- Add an H2 section for “AI presence” between “Modifiers” (or “Behaviors”) and “Related” content sections.
- Copy the content from the template example and edit the template content to be specific to each component. Only the input components will get the extra revert h3 sections.
- Create images for the components similar to the template examples (add images to the [v11 IBM Product PAL website](https://www.figma.com/design/lDM3X9hSrOE6vKLEf1CxbX/v11-IBM-Product-PAL-Website?node-id=334-2564&t=cm6MZDPOHqZj9PBD-1) file)

_If links to the general AI guidelines sections aren’t ready yet then don’t include links or hyperlinks yet. We will add these in later when ready._

### Style
[See example in Figma](https://www.figma.com/file/OJwBWBlctEgm9zYUCYbhu3/Carbon-for-AI-%E2%80%93-website-integration?type=design&node-id=80%3A7192&mode=design&t=XPoeQ0K8Ea0VbhbW-1)

- Add “AI presence” to the anchor links.
- Add an H2 section for “AI presence” at the end of the page
- Copy the content from the template example and edit the template content where needed to be specific to each component.
- Create an image for the component similar to the template examples. (add images to the [v11 IBM Product PAL website](https://www.figma.com/design/lDM3X9hSrOE6vKLEf1CxbX/v11-IBM-Product-PAL-Website?node-id=334-2564&t=cm6MZDPOHqZj9PBD-1) file)

_If links to the general AI guidelines sections aren’t ready yet then don’t include links or hyperlinks yet. We will add these in later when ready._

### Accessibility
Gower says we don't need a dedicated section like I designed on the a11y tab because the slug keyboard nav works the same across components. It only needs to be represented on general AI guidelines page.

He recommends just linking out to the general AI guidelines.
```[tasklist]
### Tasks
- [ ] Where to link to core AI guidelines?
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5926
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5755
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5756
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5757
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5758
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5759
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5769
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5786
- [ ] https://github.com/carbon-design-system/ibm-products/issues/6198
```

**Comment by sstrubberg** [comment]
waiting for new website build

**Comment by ljcarot** [comment]
Website build complete and Core has released AI documentation on CDS site.  Use this to get template -> https://github.com/carbon-design-system/carbon-website/issues/3925

**Comment by ljcarot** [comment]
Epic complete
