### ISSUE TITLE
New Component: FilterPanel

### ISSUE THREAD

**Issue by lily-peng** [carbon-design-system/ibm-products#4477]
# FilterPanel
_Please refer to #4052 for more details about migrating legacy Security components to **Products v2**._
## Brief description
Migrate **FilterPanel** from `Products v1 / Security / FilterPanel` to **Products v2**.

References: [GitHub](https://github.com/carbon-design-system/ibm-products/tree/main_v1/packages/security/src/components/FilterPanel), [Storybook](https://v1-ibm-products.carbondesignsystem.com/?path=/story/security-patterns-filterpanel--default).

For migration purposes:

* New component architecture must meet **Products v2**'s code specifications.
* The design and behavior of version `v2` must match version `v1` exactly.

## Tasks

Before starting work on this epic, please review and complete the following.

- [ ] Initial review of design/existing code. Refer to existing component specifications: [GitHub](https://github.com/carbon-design-system/ibm-products/tree/main_v1/packages/security/src/components/FilterPanel), [Storybook](https://v1-ibm-products.carbondesignsystem.com/?path=/story/security-patterns-filterpanel--default).

### Working in Carbon for IBM Products package

- [x] Have you reviewed our [contribution guidelines](https://github.com/carbon-design-system/ibm-products/blob/master/.github/CONTRIBUTING.md)?
- [x] Have you noted our [code guidelines](https://github.com/carbon-design-system/ibm-products/blob/master/docs/CODE_GUIDELINES.md)?
- [ ] Did you use the CLI to scaffold your new component?

```[tasklist]
### Tasks
- [x] Label (required by Checkbox)
- [x] Checkbox
- [x] Checkbox with overflow
- [x] Group
- [x] Accordion and AccordionLabel
- [ ] Search
```
