### ISSUE TITLE
Remove story-structure file, explore new way to sort stories (we can avoid having to add every new component to story-structure)

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#4527]
```[tasklist]
### Tasks
- [x] Remove `getStoryTitle` for *components* section
- [x] Remove `getStoryTitle` for *patterns* section
- [x] Remove `getStoryTitle` for *internal* section
- [x] Remove `getStoryTitle` for *n2p* section
- [x] Remove `getStoryTitle` for *Community* section
- [x] Remove `getStoryId`, only used with `<Story />` component in docs. `id` prop is deprecated in favor of `of` prop ([see here](https://github.com/storybookjs/storybook/commit/e2704f680a2bd71fc7bf31574e010d3d943bcd1c#diff-09fb1af073d8dcf9d7c48494449e831f20558f8da984b679570d483271e8b900R32-R35))
- [x] `story-structure.js` no longer needed
```
