### ISSUE TITLE
Look into alternative approach to `title` attribute for long text

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#4565]
> The filter panel (and the labels) have very limited horizontal space. It's easy for database-driven labels to be long enough to get cut off. A title would at least allow a user to hover over the label and see the full text.

This has been a theme that’s come up in discussion with @kristastarr on the Datagrid reviews too. I think we can keep as is for this first PR even though I don’t think this is preferred behavior based on what I’ve started reading.

Since it applies to Datagrid as well, I think we should open this as further issue/discussion.

_Originally posted by @elycheea in https://github.com/carbon-design-system/ibm-products/pull/4563#discussion_r1526835919_

#### More reading
- [Tooltips in the time of WCAG 2.1](https://sarahmhigley.com/writing/tooltips-in-wcag-21/)
- [Using `aria-labelledby` to concatenate a label from several text nodes](https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA9)
- [Understanding SC 1.4.10: Reflow (Level AA) techniques](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html#techniques)

            
```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4581
- [x] Update in tearsheet description
- [x] Update in page header title
- [ ] https://github.com/carbon-design-system/ibm-products/issues/6534
```

**Comment by paul-balchin-ibm** [comment]
Years ago I had demoed variant layouts for showing multiple values per cell in a table. For some apps this seems to be a common problem. [CodeSandBox](https://codesandbox.io/p/sandbox/multiple-values-per-table-cell-37irj8?file=%2Fsrc%2Ftable-baseline.js). This might add to the conversation. (Please forgive the clumsy coding and documentation; it was early days and I was in a rush. 😅)

**Comment by ljcarot** [comment]
@elycheea When you get a chance, can you please evaluate this Epic and determine if it is still relevant? Thx cc: @RichKummer

**Comment by matthewgallo** [comment]
@davidmenendez has an issue to investigate `StringFormatter` to potentially use across Tearsheet description, PageHeader title and descriptions, and any other text overflow instances. We will use that issue to follow up with any additional overflow work.

**Comment by elycheea** [comment]
See #6901
