### ISSUE TITLE
Team Forming

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/ibm-products#4610]
> As a `PAL maintainer`

> I need to: better understand our team processes

> So that I can: deliver amazing results with confidence, clarity and direction.
```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4775
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4776
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4777
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4613
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4980
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4999
- [x] Determine Date/Time of Office Hours. Propose aligning with Core and Dotcom's timeslot
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4634
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4635
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4638
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5046
```
