### ISSUE TITLE
Security PAL Migration

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/ibm-products#4611]
As a developer consuming components and patterns from the deprecated Security PAL, I can confidently find these assets, refactored with modern coding standards and updated to use v11 tokens in the Product PAL storybook.

As a designer consuming components and patterns from the deprecated Security PAL, I can confidently find these assets in the Figma kit.

As a designer and developer, consuming components and patterns from the deprecated Security PAL, I can confidently find information on how to use these assets documented on the Product PAL website.

Refer to internal design issue
https://github.ibm.com/CDAI-design/pal/issues/1203

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4052
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4037
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4036
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4003
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4482
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4476
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4253
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4240
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4224
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4189
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4149
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4602
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4239
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4146
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4136
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4071
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4060
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4058
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4309
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4477
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4436
- [ ] Decorator: update the kit
- [ ] Decorator: update the website
- [ ] Decorator: Usage docs (possible Core candidate because of overlap with Core's Experimental Tag)
- [ ] Decorator: Style docs
- [ ] Decorator: Accessibility docs
- [ ] BigNumbers: Usage docs
- [ ] DescriptionList: Is this a thing? It's StructuredList under the hood.
- [ ] SearchBar: Usage docs
- [ ] SearchBar: Style docs
- [ ] SearchBar: Accessibility docs
- [ ] ActionBar: Usage docs
- [ ] ActionBar: Style docs
- [ ] ActionBar: Accessibility docs
- [ ] ScrollGradient: Usage docs
- [ ] ScrollGradient: Style docs
```

**Comment by sstrubberg** [comment]
- The Decorator can have icons in it. It also has interactive elements. Strong experimental `Tag` vibes from Core.
- The Decorator has a lot of color stuff going on (@oliviaflory). It also has this key pair interaction moment that is different than Core's.
- BigNumbers feels pretty straightforward
- DescriptionList: Is this a thing? It's StructuredList under the hood. Should we just deprecate it?
- Action was internal. Now it's not. And it's supplanting IconButtonBar because it "does everything plus more" - Paul
- Nav is open to question. Is this a thing? It feels a lot like ContainedList from Core.
- StringFormatter and DelimitedList feel like utilities, not components.

**Comment by elycheea** [comment]
@sstrubberg We should probably have a high level conversation about next steps so we’re aligned with Security team on what to expect coming up.

**Comment by elycheea** [comment]
Decorator probably a good proposal to contribute further.

ICA / big numbers also worth a proposal too.

Delimited list feels more like a utility ... might make more sense to recategorize (might change for stable).

Filter panel brought it over to help teams for migration but likely will become foundation for broader filtering experience. Expect to have changes as we broaden it for overall IBM Software. Needs design attention.

Nav versus filter panel? No strong opinions ... probably migration path. Probably deprecate over time — similar to accordion. Recommend teams to migrate to Accordion over time.

Status indicator seems like a decent proposal. Helpful for multi-sequenced events like this.

String formatter another utility ... possible re-categorization.

Truncated list pretty useful for the functionality but possibly more utilitarian. Probably needs more thought if on how we categorize it.

Description list likely should become a structured list variant. DescriptionListModule that references this has another variant that has key value pairs stacked.

Action bar probably a proposal.

Search bar as a proposal.

Scroll gradient also more of a utility.

**Comment by matthewgallo** [comment]
We'll open up follow up issues for any further work here, initial components in migration have been merged.
