### ISSUE TITLE
Migrate website to GHEC internal repo

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/ibm-products#4614]
#### The problem

- https://pages.github.ibm.com/cdai-design/pal/ is hosted internally.
- Causes alot of functional problems. Website is tied to the internal repo.
- Bugs are in the wrong places.

#### Acceptance criteria

- Product PAL lives in a internal Github repo on GHEC.
- Deploy internally
- Comms

#### Questions

- Does the website get deployed on Cirrus?
- How do we deal with proprietary information?
- Do we want to whole sale migrate? Or do we want to start fresh?
- Does this effect functionality of the website? It currently uses the CDAI PAL editor to make changes to the MDX.

<img width="1222" alt="image" src="https://github.com/carbon-design-system/ibm-products/assets/15822070/afa0cdab-5458-4436-9e5f-79d44a2dc8cb">

- By doing this will we be able to link this new repo to our GH Project board?

REF https://github.ibm.com/ibmcloud/carbon-for-cloud/issues/20

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4623
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4622
- [x] Migrate website: Communicate to DSAG how website affects them
- [ ] Sync with design IA audit (@aubrey-oneal)
```

**Comment by sstrubberg** [comment]
<img width="354" alt="image" src="https://github.com/carbon-design-system/ibm-products/assets/15822070/f841341d-7663-4df9-a6fc-152da2f8f5ed">

**Comment by ljcarot** [comment]
Can we close this Epic @sstrubberg
