### ISSUE TITLE
First-time Orientation pattern 🏖️ 

### ISSUE THREAD

**Issue by ljcarot** [carbon-design-system/ibm-products#4619]
**First-time Orientation pattern**

As a designer and/or developer focused on my product's PLG improvements, I want to create within my product, a **First-time Orientation** experience that highlights for a new user how to get started using my product with the goal to help the user reach an aha moment(s).

[Design spec](https://www.figma.com/file/z5GvCED9gBr1b71soW3fIb/Get-started-pattern?type=design&node-id=44%3A5786&mode=design&t=bwRRjnGQJA8SYbA9-1): 

Other links:
[Prototype](https://www.figma.com/proto/x1drLxt4vAcQtSE5abaSaJ/Onboarding-patterns%3A-Orientation?page-id=2566%3A5&type=design&node-id=2566-1407&viewport=2482%2C1026%2C0.5&t=QpovExKDR1h2ugH8-1&scaling=min-zoom&starting-point-node-id=2566%3A1407&mode=design)

[Guidance for website](https://www.figma.com/file/QH8ex9Mh1xnNIJLZkBlE5w/Novice-to-pro-%7C-Documentation?type=design&node-id=3289%3A16386&mode=design&t=4J6PaKpwgST1Xc46-1)

Additional [notes](https://ibm.box.com/s/z8hhxvecbpjxdph7td7me4fhhs7b4gn2) from meetings

## Design Maintainer(s)

- Cameron Calder
- Bridget Ndege

## Tasks

Before starting work on this epic, please review and complete the following.

- [x] Initial review of design/existing code

### Working in Carbon for IBM Products package

- [x] Have you reviewed our
      [contribution guidelines](https://github.com/carbon-design-system/ibm-products/blob/master/.github/CONTRIBUTING.md)?
- [x] Have you noted our
      [code guidelines](https://github.com/carbon-design-system/ibm-products/blob/master/docs/CODE_GUIDELINES.md)?
- [x] Did you use the CLI to scaffold your new component?

```[tasklist]
### Tasks
- [x] Review gradient composition - deeper dive with smaller team
- [x] Review for a11y on CAG - Gower gave thumbs up
- [x] https://github.com/carbon-design-system/ibm-products/issues/4681
- [x] Ready for refinement and sizing with dev
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4809
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4683
- [ ] https://github.com/carbon-design-system/carbon/issues/16305
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5233
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4982
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4810
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5040
- [x] First-time Orientation: Comms for announcing new pattern
- [x] Get Started: Code Recipe for building Get Started Pattern
```

**Comment by sstrubberg** [comment]
Should `Orientation` be in our Guidelines section?

What's the breakdown? 

Guideline = Orientation
Patterns = First time orientation is a pattern that uses Card, Vertical Tabs, etc. Then there's another five patterns under Orientation.. Just in time, etc. 

Components = That make those patterns.

What Components are in Core and what Components are Product PAL
