### ISSUE TITLE
Migrate website: Implementation Prototype

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/ibm-products#4622]
#### Acceptance Criteria

- Investigate token usage for Github API
- ~~Investigate what it takes to host the website `internally` on GHEC and launch the website internally Cirrus~~
- By the end of the sprint, we'll have an audit of what our next steps are.

#### Devops

- ~How does the devops work on the website? Contact @szinta and @elycheea~
- ~Assuming none of the devops needs to change, it could be easier.~

Currently deployment exists in two parts. Content deploys in one repo while navigation and other things are tied to this [microsite-common](https://github.ibm.com/cloud-integration-design/cdai-microsite-common).

The editor component will be removed as a dependency. Testing has confirmed it is possible to deploy from public to GHE gh-pages via GH actions. The original website URL will remain the same. The original GHE repo will remain in use for the sole purpose of hosting gh-pages.

```[tasklist]
### Tasks
- [x] https://github.com/carbon-design-system/ibm-products/issues/4914
- [x] https://github.com/carbon-design-system/ibm-products/issues/4915
- [x] Setup workflow where it publishes back to GHE gh-pages
- [ ] Add notice to README directing users to new repo
- [ ] Disable repo issues (only after notification has been added)
- [ ] ~Migrate existing issues to new repo~
- [x] Migrate wiki content to new repo
- [x] Add authentication to deploy previews
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5429
```
