### ISSUE TITLE
Component Accessibility Status

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#4625]
REF carbon-design-system/carbon#13745

> Product teams can confidently build WCAG 2.2 AA accessible products using Carbon for IBM Products.

- Increase transparency on what accessibility standards are currently met and tested.
- Increase accessibility coverage by introducing more automated tests.
```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4626
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5225
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5226
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5361
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5362
```

**Comment by elycheea** [comment]
Closing in favor of #6364
