### ISSUE TITLE
PAL Onboarding for Designers

### ISSUE THREAD

**Issue by carrenelloyd** [carbon-design-system/ibm-products#4636]
### User opportunity

As a designer maintaining the Product PAL, I am confident knowing how the Product PAL works, along with being able to identify key stakeholders and high priority work-streams. I will be able to begin to successfully delivering work after completing this epic.

#### Sprint Zero - Onboarding 

- What is the Products PAL? 
	⁃	Read [About ](https://pages.github.ibm.com/cdai-design/pal/overview/about)and Overview section. 
	⁃	Get an understanding of the overall layout of the PAL site 
	⁃	What is our Point of view? In terms of specifications - Overview (screen size, theme)
	⁃	Understand Core set of components 13
- Watch videos On Products PAL. [YourLearning](https://yourlearning.ibm.com/activity/PLAN-23664761452B) 
- Track your questions, feedback and concerns formulate your own POV. 
- [ ] Schedule learning shesh AMA with Carrie - 

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4642
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4643
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4644
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4646
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4647
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4648
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4649
- [ ] Onboarding: AMA with Carrie
```

**Comment by carrenelloyd** [comment]
Sam Ting's Carbon orientation Q1 2024 https://ibm.box.com/s/3izl1r2x7ea4fd7wugfgdsfzgvmhzld1
