### ISSUE TITLE
Cloud PAL exit

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#4807]
REF [ibmcloud/carbon-for-cloud#20](https://github.ibm.com/ibmcloud/carbon-for-cloud/issues/20) [cdai-design/pal#1320](https://github.ibm.com/cdai-design/pal/issues/1320)

```[tasklist]
### Tasks
- [ ] Reach out to Cloud team to discuss website timing
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4881
- [ ] Get new design team members access to Cloud repo
```

**Comment by carrenelloyd** [comment]
All info is being documented in this ticket https://github.ibm.com/ibmcloud/carbon-for-cloud/issues/20 and this one https://github.ibm.com/cdai-design/pal/issues/1320
