### ISSUE TITLE
Get Started: Storybook organization

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-products#4810]
## Issue
We need to determine how we want to organize the Get started components and pattern in Storybook.

---

After speaking with Cameron, the Get started card is specific to Onboarding usage, so we do not want to surface it under the current "components" folder. We want to move it under the Novice to Pro folder

![Screenshot 2024-06-04 at 9 33 48 AM](https://github.com/carbon-design-system/ibm-products/assets/45692622/bfa14135-ede9-4a42-9e98-f1bcce605586)

```[tasklist]
### Tasks
- [ ] Rename story to `Get started card`
- [ ] Move the story under `Novice to pro folder`
- [ ] Rename `Novice to pro` folder to `Onboarding`
```

**Comment by elycheea** [comment]
Regarding “experimental” section — more fuel to the fire #4645

**Comment by oliviaflory** [comment]
Moving our notes to a comment because these are no longer relevant


## Notes
~On Apr 10 we discussed are these components or patterns?~

**Components**
- Cards (3 variants roughly categorized as: default, image, number)
- Tab drawer: we could see this being use more broadly in the future

**Pattern**
- The combination of the above components make up the Get started pattern
- The tab drawer is NOT required (see Figma guidance)

### Questions 
**1. _Can something be represented in storybook in more than one place?_**
Proposal:
```
Components
- Cards
-- Expressive
-- Productive
-- Get started 
- Tab drawer

Patterns
- Get started
-- Get started card
-- Tab drawer
```
**2. _Do we integrate the Get started and other PLG components into the existing stories?_**
- Or are they in a separated PLG section

Answer:
- Get started card is part of the `Novice to Pro` or `Onboarding` component set. 
   - ie it should not be grouped under `Cards`
- Other PLG components TBD
 
**3. _How are we surfacing that these are experimental (subject to change)_**
 - Pepper in components within existing stories and add `Experimental` tag 
 - Create an experimental section
```[tasklist]
### Tasks
- [ ] Move `Get started` card under `Novice to pro` folder
```
