### ISSUE TITLE
C4IP Figma Library Organization 🏖️ 

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/ibm-products#4811]
[Figma All themes C4IP library (view access)](https://www.figma.com/file/0F9dKH2abAd7gSfvnacfWf/(v11)-C4IP-BETA---All-Themes---Carbon-for-IBM-Products?type=design&node-id=1%3A1309&mode=design&t=6fBfToiU1oRf51Ug-1)

Reference box notes:
* [Figma variables strategies to Dec 2023](https://ibm.ent.box.com/notes/1289751967088?s=7hkpr472gifh2951wi3s5261dc7dzd5f)
* [Figma kit libraries for C4IP](https://ibm.ent.box.com/notes/1354909552280?s=q758f9ihg402mnuijjj9usqtcx5i6cwo)

```[tasklist]
### Setup tasks
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5607
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4880
- [x] Contribution process (git vs figma)
- [x] Slack channel for volunteers: #ibm-products-figma-libraries (private)
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4918
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4962
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4888
```

**Comment by RichKummer** [comment]
Quick comparison of top 10~ component inserts by library:


Component name | All themes | v11 gray 100 | v11 gray 10 | v10 All themes
-- | -- | -- | -- | --
Combo button | ✅ |   | ✅ |  
Status icons | ✅ | ✅ | ✅ |  
Page header | ✅ | ✅ | ✅ |  
Selectable row item | ✅ |   |   |  
Filter flyout | ✅ |   |   |  
Productive card | ✅ | ✅ | ✅ |  
Scrolling | ✅ |   |   | ✅
User profile images | ✅ | ✅ | ✅ | ✅
Tag set | ✅ | ✅ | ✅ |  
Create flow | ✅ |   |   |  
Menu button |   | ✅ | ✅ | ✅
Combo button |   | ✅ |   | ✅
Selectable row item |   | ✅ |   | ✅
Empty state |   | ✅ |   | ✅
Toolbar |   |   | ✅ |  
Add items |   |   | ✅ |  
Side panel |   |   | ✅ |  
Tearsheet (wide) |   |   | ✅ |

**Comment by RichKummer** [comment]
Carbon Telemetry snapshot – 04/19/24

![Image](https://github.com/carbon-design-system/ibm-products/assets/15643582/512f8046-f89d-4e77-9bff-31ede04e4131)
