### ISSUE TITLE
Review of Product PAL Design kit docs

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-products#4880]
### The problem
Most Product teams are still utilizing the (v10) Gray 10 or Gray 100 theme kits instead of the (v10) All themes kit. By the end of this review we should be able to have a POV on whether we should update the Design kit documentation on the Product PAL website.

### Review the Carbon for IBM Product PAL kit docs

**[Figma](https://pages.github.ibm.com/cdai-design/pal/design-kits/figma/)**
- Are we referencing G10 & G100 kits or All themes
- Identify areas where we need to remove Cloud (eventually)

**[Sketch](https://pages.github.ibm.com/cdai-design/pal/design-kits/sketch)**
- Can we remove this page
- Is anyone maintaining the Sketch kit
   - Note: link to Product PAL sketch kit = "cannot find this document"

**Questions:** 
- Why have they not migrated to the (v10) All themes kit?
- Have there been comms about the all themes kit?
- Will migration from v10 to v11 be smoother if they are utilizing the All themes kits
```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5045
- [x] Review Design kit / Sketch page
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5235
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5237
```

**Comment by My-Money29** [comment]
Alignment asset index component naming #1388 
https://github.ibm.com/cdai-design/pal/issues/1388
