### ISSUE TITLE
Figma operations

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-products#4882]
```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4883
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4884
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4886
- [x] Create team operation folder
- [x] Work with the workgroups to align on the things.
```

**Comment by RichKummer** [comment]
Closed, with follow on #5568 to clean up and finalize Figma spec
