### ISSUE TITLE
Create proposal for Figma organization

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-products#4884]
Follow on from #4883 

[Figma organization file](https://www.figma.com/file/y9ROtWcrB1eHQ2gyq7yzyP/C4IP-Figma-organization?type=design&node-id=0%3A1&mode=design&t=dEtMCqZ82tPBmmy1-1)

```[tasklist]
### Tasks
- [x] Review Carbon Core organization
- [x] Review Dotcom organization
- [x] Tracey add things you like and dislike about System squad's Figma organization
- [x] Olivia add things you like and dislike about Dotcom squad's Figma organization
- [x] Rich add things you like and dislike about Dotcom squad's Figma organization
- [x] Create proposal for PAL organization
- [x] Play back proposal to PAL Design team (Carrie, Olivia, Tracey, Aubrey)
```

Ideas:
- Website
   - Website template
   - Website docs
- WIP
   - Things that are not released / not final
- Components & Patterns (separate?)
- Team operation

**Comment by RichKummer** [comment]
Created a [C4IP Figma organization file](https://www.figma.com/file/y9ROtWcrB1eHQ2gyq7yzyP/C4IP-Figma-organization?type=design&node-id=0%3A1&mode=design&t=dEtMCqZ82tPBmmy1-1) to compare and share thoughts.
