### ISSUE TITLE
Create guidance for Figma specs

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-products#4886]
Product PAL has a mix of components and patterns
- some are not grid aware
- some are grid aware
- We want to establish a template for us and contributors to consistently spec components in Figma

Core:
- Non grid aware

Dotcom:
- Grid aware and non grid aware

IBM Experience library:
- Mixed lets review
```[tasklist]
### Tasks
- [x] Create list of expectations
- [x] Playback to team
- [x] Collect feedback from developers
```

**Comment by RichKummer** [comment]
## Developer feedback 06-14-24

[Mural](https://app.mural.co/t/ibm14/m/ibm14/1718051205844/639328b497fb12a247c69f87e770a4ae7894bab7?sender=uf83bc0b1e31118868ab69626)

### 1. Common missing info in design specs
- Inconsistent spacing/padding between variations
- Not showing all variations and only showing ideal states
     - Label what content is optional and what happens without optional content
- Missing responsive behavior
- Need to label examples vs features.

### 2. For design tokens, prefer a list or more visual
- List is more scannable, maybe better for simpler components. Easier to read/scannable.
- Visual is good for very complex states or components but feels too noisy. 
- Visual might have the edge in highly interactive or granular states, and is more contextual. In more complex components, a list of all tokens could get pretty lengthy.
- Prefer base/defaults (spacing, size, typography) that don't typically change, with specific states separated out to show what changes.

### 3. In an interaction flow, what sort of specifics are needed
- Would want to know what "types" are supported – what should we include out-of-the-box vs customizable by the adopter.
     - ex. multi selection, single select, number, string, etc.
-  Should have alignment on naming (but maybe not always needed). Would help keeping naming in Figma and code close.
- Seeing the sequence of interactions visualized is useful, but I would want more details rather than less. I'd like a short description at each step to describe what happened.
-
