### ISSUE TITLE
Product PAL Information Architecture 

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-products#4887]
```[tasklist]
### Dependencies
- [x] Codifying the difference between Component & Pattern; alignment between ecosystem
- [x] Cloud Phase 2 and Phase 3 exit
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5344
```

```[tasklist]
### Preparation
- [x] Gather Carrie's IA research
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4753
- [x] https://github.com/carbon-design-system/ibm-products/issues/5313
```

```[tasklist]
### Required for launch
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5300
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5284
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5285
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5343
- [ ] https://github.com/carbon-design-system/carbon-for-products-website/issues/10
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5291
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5333
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5339
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5325
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5444
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5338
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5286
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5293
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4146
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4144
- [ ] https://github.com/carbon-design-system/carbon-for-products-website/issues/155
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5504
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5296
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5297
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5299
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5690
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5475
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5492
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5503
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5532
- [x] Delete hidden pages
- [x] Prep for launch: test out all the links and new content
- [x] Create comms for new website launch
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5732
- [ ] https://github.com/carbon-design-system/carbon-for-products-website/issues/67
- [ ] https://github.com/carbon-design-system/carbon-for-products-website/issues/66
- [ ] https://github.com/carbon-design-system/carbon-for-products-website/issues/69
- [ ] https://github.com/carbon-design-system/carbon-for-products-website/issues/44
- [ ] https://github.com/carbon-design-system/carbon-for-products-website/issues/71
- [ ] https://github.com/carbon-design-system/carbon-for-products-website/issues/70
```
_**Note** Post launch issues moved to #114

**Comment by carrenelloyd** [comment]
PAL Site nav user test results
https://app.mural.co/t/dsagmembers0371/m/dsagmembers0371/1694633547585/450fb852ebc0009816083c7536e8afca5d08b237?sender=ue4888531e4a8fb912dc62519

**Comment by carrenelloyd** [comment]
PAL Site nav user test results
https://app.mural.co/t/dsagmembers0371/m/dsagmembers0371/1694633547585/450fb852ebc0009816083c7536e8afca5d08b237?sender=ue4888531e4a8fb912dc62519

**Comment by carrenelloyd** [comment]
Fimga low-fi of Left Nav and Home Page
https://www.figma.com/file/Fu9rOdSFQyIGTdn4UgOXFp/DSAG-PAL-Enhancement-Nav-research?type=design&node-id=0%3A1&mode=design&t=MDYIk9WN9xUiVBpQ-1

**Comment by oliviaflory** [comment]
@aubrey-oneal wondering if we can close this epic?? 

We could remove the post launch items, I think I've moved them all to the website board.

**Comment by oliviaflory** [comment]
Closing as complete, docs moving to core will be tracked in [#286](https://github.com/carbon-design-system/carbon-for-products-website/issues/286)
