### ISSUE TITLE
[Website]: misc dependency and workflow updates

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/ibm-products#4915]
Once the PAL GHE website repository has been migrated to its new location (https://github.com/carbon-design-system/ibm-products/issues/4914), the following updates need to happen

```[tasklist]
### Tasks
- [ ] remove the page editor from the project dependency
- [ ] update to use Node 18+
- [ ] add workflow to deploy build artifacts back to GHE `gh-pages`
```
