### ISSUE TITLE
Team Forming: PR Auto-rotation Assignments

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/ibm-products#4980]
#### Acceptance Criteria

- Implement PR Auto-rotation assignments in Github
- Create a program where new hire devs along with dotcom devs feel proficient in reviewing and approve PRs with high quality code.

REF https://github.com/carbon-design-system/carbon/pull/16335
```[tasklist]
### Tasks
- [x] Create reviewer team
- [x] Turn on PR auto-assign from new team
- [ ] ~Clarify/document expectations for PR review shadowing~
```
