### ISSUE TITLE
[Feature Request]: Provide Shift-click segment selection for Datagrid

### ISSUE THREAD

**Issue by crichtonibm** [carbon-design-system/ibm-products#4990]
### The problem

The Selectable Row feature provides a Select All capability, but does not support the "standard" shift-click method of selecting a swath of rows at once. 

### The solution

Update the Selectable Row feature to support Shift-selection of a checkbox to set/reset all checkboxes between the previous checkbox toggled (normally without shift) and the current checkbox. 

If row 1 is toggled normally, it becomes the primary row. Then, if row 5 is shift-toggled, the result would be rows 1 through 5 all being either selected or deselected, depending on the current state of the entire set.   If 1-5 were already all selected when the shift-select of 5 occurred, then they will all be deselected. If ANY of the 1-5 was already in the deselected state, then all would be selected.

The primary row should only be changed when a normal (no shift) selection occurs. In the above example, we shift-selected row 5. Lets say they are now all selected. If I shift-click row 6, I would expect the segment to be 1-6, not 5-6, as 1 was still the primary row. 

If there is no primary row, then a shift-select is treated as a non-shifted select, and it will select the primary row.

If the primary row is removed from the table, then it is as though there never was a primary row selected (so a shift select will be treated as a non-shift select)

### Owner/main maintainer(s)

Joe Crichton (requestor)

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues
```[tasklist]
### Tasks
- [ ] Requires exploring keyboard accessibility options
```

**Comment by ljcarot** [comment]
We've been investigating [TanStack ](https://tanstack.com/table/latest)[Table](https://tanstack.com/table/latest), a third-party, open-source offering, which provides extensive data table capabilities surpassing what our Carbon Datagrid offers. It provides much more flexibility and customization. TanStack Table is headless which means it can easily be added alongside Datagrid component in your product or application. The benefits of more flexibility for product teams and less maintenance for Carbon makes it a win win. Lastly, it is available in multiple frameworks including [React](https://github.com/carbon-design-system/tanstack-carbon/tree/main/react#readme) and [Web Component](https://github.com/carbon-design-system/tanstack-carbon/tree/main/web-components#readme) so it provides an option to non-React product teams.

For these reasons, we have decided to transition from building our own custom table component to using an example-based approach with TanStack Table. Datagrid will still exist in our library for existing teams but we are announcing the deprecation* of the Datagrid component in v2.54.0 release so teams can begin to work through the transition. Details about how to use both Datagrid and TanStack together can be found [here](https://github.com/carbon-design-system/tanstack-carbon/tree/main). 

*Deprecation means that no new features will be added however sev 1 and sev 2 bugs will be supported.
