### ISSUE TITLE
Remove any `defaultProps` usage across all components

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#5032]
## What will this achieve?

In preparation for React 19 support, we should make sure that all `defaultProps` usage is removed since it will no longer be supported in React 19 ([recommended option is to use es6 default params](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-proptypes-and-defaultprops)).

## How will success be measured?

When we no longer use `defaultProps` across our library.

## Additional information

- Designs
- Existing code
- etc

### Components to update
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5033
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5034
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5035
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5036
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5037

**Comment by elycheea** [comment]
Looks like these have been address with #7681 or in some cases, possibly earlier. I’m going to close this and the subissues as completed.
