### ISSUE TITLE
Delivery of patterns

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#5041]
### Determine how we deliver patterns

Patterns are defined as something that can be accomplished in multiple ways utilizing a combination of component(s) with additional design considerations.
- Patterns are “recipes” with “ingredients” (components) that are combined to accomplish something.
- Patterns may have demo code associated with a pattern for example purposes. However no pattern will support all possible configurations in code.

We need to define what "demo code" is so we can be clear with our adopters about what they are getting (or not getting)
Decide how we will publish our pattern "recipes"

```[tasklist]
### Design
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5651
- [x] Align with Core on pattern ingredient list method
- [ ] Onboarding: how do we document Onboarding patterns AND components
```

```[tasklist]
### Dev
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5652
- [ ] https://github.com/carbon-design-system/ibm-products/issues/6489
```

```[tasklist]
### Cross-discipline
- [ ] https://github.com/carbon-design-system/ibm-products/issues/6260
- [ ] Publish definition of demo code on website
```

_**Note**: Publishing of ingredient list moved to [285](https://github.com/carbon-design-system/carbon-for-products-website/issues/285)_

**Comment by oliviaflory** [comment]
Add the patterns to task list above



![Image](https://github.com/user-attachments/assets/5d08e7c0-dc9c-4b33-a27e-8a27152f0800)
![Image](https://github.com/user-attachments/assets/eceaa23c-8a50-4ead-a43d-683294a988f6)

**Comment by sstrubberg** [comment]
Fear of things being created in Labs that aren't composable.
What is our Compound Component Strategy?

### Learning requirement

[Video explainer](https://www.youtube.com/watch?v=vPRdY87_SH0)
[Kent Dodd's blog post on it](https://kentcdodds.com/blog/compound-components-with-react-hooks) - old but still relevant!
[Example of it in use in Primer's PageHeader](https://primer.style/components/page-header/react/beta#examples)
[Example from Radix's NavigationMenu](https://www.radix-ui.com/primitives/docs/components/navigation-menu)

**Comment by elycheea** [comment]
Closing for now as this priority has shifted to incorporate UE patterns.
