### ISSUE TITLE
Team Forming: get designers on local dev environment

### ISSUE THREAD

**Issue by aubrey-oneal** [carbon-design-system/ibm-products#5046]
```[tasklist]
### Tasks
- [ ] A developer should document any barriers to getting designers on a local dev environment. I.e. installing nvm.
- [ ] A developer should walk the designers through the process so we can troubleshoot together
- [ ] As a group, review the PR process so that everyone feels confident
```
```[tasklist]
### Designers
- [x] Aubrey
- [x] Tracey
- [x] Rich
- [x] Olivia
```

**Comment by sstrubberg** [comment]
This will be unblocked once https://github.com/carbon-design-system/ibm-products/issues/4614 is completed.

**Comment by matthewgallo** [comment]
Everyone should be setup now! If any issues arise, feel free to reach out to myself or anyone from the dev team! 😄
