### ISSUE TITLE
Replace `ActionableNotification` in Storybook with `StaticNotification`

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#5080]
## What will this achieve?

Our Storybook includes a number of `ActionableNotification`s to indicate deprecated components. The newer `unstable_StaticNotification`[^1] from `@carbon/react` is more appropriate for this usage.

> `unstable__StaticNotification` is non-modal and should only be used inline with content on the initial render of the page or modal because it will not be announced to screenreader users like the other notification components.

## How will success be measured?

`ActionableNotification` in stories should be replaced with `StaticNotification`.

Currently used in ButtonMenu, ComboButton, and `preview.js`.

## Additional information

- Designs
- Existing code
- etc

[^1]: https://react.carbondesignsystem.com/?path=/docs/experimental-unstable-staticnotification--overview#unstable__staticnotification
```[tasklist]
### Tasks
- [ ] Remove from ButtonMenu
- [ ] Remove from ComboButton
- [ ] Remove from `packages/core/.storybook/preview.js`
```
