### ISSUE TITLE
PLG IA

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-products#5101]
### We need a solution for how to include the PLG IA into the Prod Pal website

What makes up PLG?
- PLG site
   - Emails
   - Login and logout
   - Onboarding components
   - Onboarding patterns
   - Registration
   - Upgrade and purchase
   - Try (is on a separate page)
   
- PAL (PLG and MSCP)
   - Try offer guidance
      - Try offers
   - Product led growth and MultiCloud SaaS Platform Patterns
      - Email patterns
      - Login and logout patterns
      - Onboarding patterns and Aha! guidance
      - Registration patterns
      - Try and Buy routes to market patterns
      - Upgrade and purchase patterns
   - _Where is Preview?_

### Context
- What is the schema
   - Pattern > Flow > Components (it doesn't make sense in the context of what we have today)
   - Where to document components if they only belong to a specific "flow"
      - Talk to Matt R and Aubrey about "Collections"
      - Ask Cameron if there's other use cases for these assets
  
- Get started / Onboarding / Orientation flow
   - Get started is a page _within_ an overall user flow or multi-screen pattern
   - "Orientation flow" is the name of the user flow / multi-screen pattern
   - It is currently linking out to patterns in PAL and/or components in the PAL and Core
   - The docs currently written for Orientation flow are not consistent with 
      - "Get started" vs "Getting started"
      - How to refer to cards
      - When we link out to other components (interstitial screen) vs document within the page (cards) or documenting tabs (none)

Link to Olivia's [as-is exploration](https://www.figma.com/file/WzBzlGiRAxV8pMRrNZUllE/PLG-on-Product-PAL-website?type=design&node-id=0%3A1&mode=design&t=pw34r3AezRYQZf2g-1)

```[tasklist]
### Tasks
- [ ] Confirm what exactly is in PLG vs what is not
- [ ] Run the assets through the existing schema or definitions (component vs pattern)
- [ ] Determine new schema (adding user flow)
- [ ] Talk to Matt R and Aubrey about "collections"
- [ ] Answer: how to document something that only belongs to a specific PLG ___
- [ ] Ask Cameron: Are there other use cases for Get started cards outside of Orientation flow? What about other PLG ___
- [ ] etc

```

**Comment by oliviaflory** [comment]
Closing, we tackled PLG IA within the component and pattern definition work and Aubrey's IA work
