### ISSUE TITLE
Figma C4IP organization/migration

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/ibm-products#5115]
Follow on to #4884 

```[tasklist]
### Tasks
- [ ] Finalize Figma organization (website docs)
- [x] Create new team in Figma
- [x] Migrate Figma files
- [x] Organize based on proposal
```
