### ISSUE TITLE
Use Carbon feature flag mechanism

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#5116]
As to not create any breaking changes, we should make sure that our current feature flag system still works but includes a warning to use the new feature flag system, including a note that all new feature flags added to our library will only be included via the new mechanism.
```[tasklist]
### Tasks
- [ ] Update feature flag docs
- [ ] Update any stories using the old feature flag approach to the new one
- [ ] Include warning if old feature flag mechanism is used
```
