### ISSUE TITLE
Checklist: release component as stable

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#5137]
## What will this achieve?

Now that `Checklist` has gone through design and dev release reviews with appropriate fixes, it's ready to be released as stable.

```[tasklist]
### Tasks
- [ ] Move `Checklist` to released in package-settings
- [ ] Move Checklist styles to `index-released-only`
- [ ] Add `Checklist` in `carbon.yml`
```
