### ISSUE TITLE
[Feature Request]: EditInPlace,  add an onblur function

### ISSUE THREAD

**Issue by AustinGitHub** [carbon-design-system/ibm-products#5148]
### The problem

Currently, when you click out of the text input, if you made any changes, it will persist that change instead of reverting back to the original text. User hasn't hit save yet, so it saves anyways for the onblur 

https://github.com/carbon-design-system/ibm-products/assets/10100397/cf7283e4-698a-4951-a5be-df9212edcb29

### The solution

Add an onblur event action so user can add this to the component props and have their own way to decide what action it should do when on Blur/Clicking out of the edit will do. 

### Owner/main maintainer(s)

IBM

### Business priority

Medium Priority = upcoming release but is not pressing

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues
```[tasklist]
### Tasks
- [ ] `onBlur` should not save new value
```

**Comment by thefirstartist** [comment]
@AustinGitHub
I think providing the onBlur event may not be the best solution for resolving this issue. If we allow users to keep the changes in the text field without clicking the 'Save' button, then it functions just like a regular text input field. In that case, users should simply use the regular text input field instead of this component.

Additionally, allowing the product team to choose what they want could lead to potential inconsistencies among our products.

**Comment by AustinGitHub** [comment]
Then can we have some way to indicate how the user left the input field whether it was from clicking out or from the save? Because some UI designs might want it to not save if user clicks out if they didn't hit the save button but there isn't a way to know what behavior was taken. Thanks!

**Comment by thefirstartist** [comment]
I think clicking outside of the text field is equivalent to giving up on the editing process. We discard the changes and return the data to its original state. The only way to retain the changes is by clicking the save button.

Most design systems use the 'X' button in this type of component to represent 'Clear.' Therefore, clicking outside the component cancels the action, while clicking the 'X' button inside the field clears the content. This approach tends to be more intuitive for users. It's okay if we want to use the 'X' for cancel, but clicking outside should definitely be Cancel.

**Comment by thefirstartist** [comment]
Yes, we are in agreement. What I was suggesting is not to provide the option for designer to `have their own way to decide what action it should do` to avoid inconsistencies. Clicking outside to cancel should be mandatory, not optional.

**Comment by AustinGitHub** [comment]
Will look into this tomorrow

**Comment by elycheea** [comment]
Closed by @AustinGitHub’s contribution. :)
