### ISSUE TITLE
Asset Requirements Checklist

### ISSUE THREAD

**Issue by carrenelloyd** [carbon-design-system/ibm-products#5151]
(Draft) Asset Requirements checklist

### **Core** 

- Three or more BU’s need it 
- It is an element or primitive 
- No backend logic 
- Composable enough for three or more BUs
- Supports instrumentation 
- Works across three use cases 
- May contain a core asset as a base
- Presentation only
- Universal patterns/guidance 
- Is connected to a strategic business initiative

### **Products**

- Three or more teams within Software
- Not element or primitive 
- Can have backend logic 
- Composable enough for three or more teams
- Enables instrumentation (technical logic)
- Has a specific business solution
- Is connected to a strategic business initiative 
- Works for limited use cases 

### References
- Shixie's scorecard matrix
- [UK.gov contribution docs](https://design-system.service.gov.uk/community/contribution-criteria/): has a great checklist about proving biz impact, etc

```[tasklist]
### Things to do
- [ ] Create a workstream/workgroup
- [ ] Who will lead this workstream?
- [ ] Refine the checklist: details about what each step means (connected to happy path?
- [ ] Create a path for teams to navigate the checklist
- [ ] Mix with the rubric. How does this work?
- [ ] Test drive a new asset
- [ ] Decide where this gets published (longer term)
- [ ] Has a dependency on Composability definition
- [ ] Need to understand what Labs is
```

**Comment by ljcarot** [comment]
Created the checklist in Box -> https://ibm.box.com/s/9ckiqpusmkxjwqjx4s8vahziaxr4ieqe
