### ISSUE TITLE
Discuss future of Notifications

### ISSUE THREAD

**Issue by aubrey-oneal** [carbon-design-system/ibm-products#5297]
https://pages.github.ibm.com/cdai-design/pal/patterns/notifications/usage/

Considering:
- move panel to core
- scrub docs of the full page? 

```[tasklist]
### Tasks
- [x] Get Telemetry numbers on notification panel usage
- [ ] Is this specific to Cloud Pak?
- [x] Sync with core on if Notification panel goes into notifications and UI shell workstream
- [ ] Determine next steps based on Core
```

**Comment by oliviaflory** [comment]
### Figma usage

Gray 10
- 1,057 instances
- 38 teams
- 84 files

Gray 100
- 828 instances
- 21 teams
- 71 files

### Telemetry
- 1,280 instances
- 528 repos

### Discussion with Lauren
- Yes it is a good candidate to bring Notifications panel into core
- Leaning towards bringing it into the UI shell umbrella
   - Would likely reference the panel in the Notifications components/pattern
- No date set for the work to start

**Comment by oliviaflory** [comment]
### Next steps 
Things to consider:
- Rename the page 
   - Is there something that encompasses both the panel and the full page?
- Utilize tree nav
   - Notification panel
   - Notification page
   - would this require an overview page?
- Remove panel docs when it moves to core
