### ISSUE TITLE
Remove 3rd party logos from websites

### ISSUE THREAD

**Issue by aubrey-oneal** [carbon-design-system/ibm-products#5299]
Context from Carrie:
This [3rd party logos] was a collective community effort so no workgroup. I instructed everyone to add their 3rd party logos to Box. People all over Software were constantly asking where they were housed, so we made a page, but we may want to revaluate if this is needed (and or legal)

Acceptance criteria:
- [ ] ~Work with legal to understand the status of the 3rd party logos on our site.~
- [ ] ~Re-work the existing page to include a usage/legal tab with any information users may need. You may want to [merge the content found on IDL](https://www.ibm.com/design/language/ibm-logos/8-bar).~
- [ ] Discuss whether we should move this page under the Guidelines sub-menu or move it to Core

### Decision:
Remove both 3rd party logo pages from the website to remove any concerns about incorrect usage

Contacts:
Possibly Teresa Tan?

```[tasklist]
### Tasks
- [x] Delete 3rd party logos on new site: https://pages.github.ibm.com/carbon/ibm-products/
- [x] Delete 3rd party logos on v10 site: https://pages.github.ibm.com/cdai-design/pal/third-party-logos/usage
- [x] Remove “Third-party logos” from v10 navigation: https://github.ibm.com/cloud-integration-design/cdai-microsite-common
- [x] Redeploy v10 navigation
```

**Comment by carrenelloyd** [comment]
We may decide to deprecate this page entirely and work with the Branding team to publish logos on the DAM

Here is the box note where Denise Bell has been capturing meeting notes, and action items with regards to getting legal approval for teams to use logos externally
https://ibm.box.com/s/0x0otpcfqi84ne8flol02efs89aygjp0

**Comment by ljcarot** [comment]
Makes me nervous that we may be using logos without the proper approval and compliance to their specifications.  Lets deprecate this page/content in favor of sending people to inquire with brand team.  @aubrey-oneal and @oliviaflory fyi
