### ISSUE TITLE
Data table extensions, scrolling: Code and Figma border colors for frozen column are incorrect

### ISSUE THREAD

**Issue by jjennings7** [carbon-design-system/ibm-products#5324]
Note this issue is to fix the issue in Figma, and we will only be updating it in the (v11) C4IP All Theme Figma Kit and the v(v11) Gray theme Figma Kit. We also have a code issue for Storybook

### Package

Carbon for IBM Products

### Description

In Carbon 10 and 11, the frozen column border color is incorrect in both Figma and the Storybook code.

### Figma
The border color in both v10 and v11 kits are incorrect. One is too dark and one is too light. Neither matches the original specs. 
![Screenshot 2024-05-22 at 4 01 18 PM](https://media.github.ibm.com/user/199198/files/5a474718-c135-4273-9c1b-0c0da223a1d0)

**Expected behavior**
The right border should be `$active-light-ui` in v10 which seems to translate to `$border-subtle` in v11. 

**Correct border color**
![Screenshot 2024-05-22 at 4 16 06 PM](https://media.github.ibm.com/user/199198/files/70beb5af-1fe1-450c-9acf-d00611ff9f3a)

---
### Storybook / code
In v1.72.3 (Carbon 10), the border color is the correct hex value, #c6c6c6, but the wrong token is assigned, `$disabled-02`. In addition, the border does not extend into the header cell. 
![Screenshot 2024-05-22 at 3 50 35 PM](https://github.com/carbon-design-system/ibm-products/assets/48838320/56b5012b-ae61-47c3-994d-66e3ffc8b7d6)

In 2.39.0 (Carbon 11), the border color is the correct hex value, #c6c6c6, but the wrong token is assigned, `$disabled-02`.
![Screenshot 2024-05-22 at 3 50 50 PM](https://github.com/carbon-design-system/ibm-products/assets/48838320/0c3c6c78-25cb-470d-afb8-0dc949470e75)

**Expected behavior**
The right border should be `$active-light-ui` in v10 which seems to translate to `$border-subtle` in v11. The border should be present on the entire frozen column,  including the header cell.

**Resources**
In issues [#1980](https://github.com/carbon-design-system/ibm-products/issues/1980) and [#2509](https://github.com/carbon-design-system/ibm-products/issues/2509#issuecomment-1347117321), `$active-light-ui` is indicated as the correct border color. This information is also published in the [PAL guidance](https://pages.github.ibm.com/cdai-design/pal/components/data-table/scrolling/usage#styling).

### Component(s) impacted

**Figma**
(v10) Gray 10 - IBM Products
(v11) Gray 10 - IBM Products

**Storybook**
v1.72.3 (Carbon 10) - Datagrid - [Frozen columns](https://v1-ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid-datagrid--frozen-columns)
2.39.0 (Carbon 11) - Datagrid - [Frozen columns](https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid--frozen-columns&globals=viewport:basic)

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

all

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Product/offering

DataStage

### CodeSandbox or Stackblitz example

https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid--frozen-columns&globals=viewport:basic

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues
```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5327
```

**Comment by ljcarot** [comment]
@RichKummer Can you see if this has been fixed?

**Comment by ljcarot** [comment]
@RichKummer Can you help me understand what this issue pertains to?

**Comment by RichKummer** [comment]
> [@RichKummer](https://github.com/RichKummer) Can you help me understand what this issue pertains to?

Yes! This is a bug in the Figma kit resulting from an incorrect color token used in the Data table extensions section.
For additional background, the token being used is `$border-strong-01` using Figma's effects. We want to change this to a border using `$border-subtle-00`

## Tasks
- [ ] In the [Datagrid section](https://ibm.monday.com/docs/7755879548) of the v11 Figma kit we have a component for "Frozen columns"
- [ ] For all variants of the Frozen columns, we should first remove the border effect using `$border-strong-01`. This can be done by selecting a variant, scrolling down on the right panel to "Effects" and clicking the `–` next to the inner border effect.

<img width="959" alt="Image" src="https://github.com/user-attachments/assets/8a3d73b4-52d9-4534-9d4c-5b25f95fd4b4" />


- [ ] You can then add a border that is either only on the left or right that uses `$border-subtle-00`. If the variant is "First", the border should appear on the right. If the variant is last, the new border should appear on the left. I've updated the top left variant so the solution is visible.

<img width="1012" alt="Image" src="https://github.com/user-attachments/assets/9cd4bc87-43f2-43e1-acd3-94019b798381" />

- [ ] Review with Rich
- [ ] Publish the update to the library.

**Comment by rachels01** [comment]
I've removed the existing Effects and Strokes, and added in the new $border-subtle-00 stroke to the data tables [here](https://www.figma.com/design/0F9dKH2abAd7gSfvnacfWf/(v11)-Carbon-for-IBM-Products?m=auto&node-id=12272-291345&t=HfZrml0Ih2sPJT82-1). @RichKummer please review when you have a chance.

**Comment by rachels01** [comment]
Rich has reviewed and approved the update, and published the changes. Closing the ticket.
