### ISSUE TITLE
Explore: Add and select

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-products#5325]
[Documentation page](https://pages.github.ibm.com/cdai-design/pal/patterns/add-and-select/usage)
[Storybook](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-patterns-add-and-select-singleaddselect--default&globals=viewport:basic)

We need to have a better understanding of the current Add and select pattern in order to determine if it is a component, pattern or guidance based on the new definitions.

*Note: David seems to know a lot about `AddSelect`, reach out to him for questions!*
*Look up the designer on the Airtable – Oliver Kauselmann*

#### Component
An asset that has been designed and coded
- Export is a component because there is a coded modal provided specifically to export

#### Pattern
Something that can be accomplished in multiple ways utilizing a combination of component(s) with additional design considerations (a recipe of components)
- Patterns may provide coded examples, but will not be required to provide code or support every possible instance of a pattern
- Dashboards are patterns because you can build a dashboard in many different ways
   - Various sized tiles
   - Various components, actions, information within those tiles

#### Guidance 
Overarching direction or instruction that can be applied across an entity
- As you move further away from the “core” of the spoke, we may see more detailed guidance and opinion on guidance at the “spoke” levels
- Content is guidance because we apply the same principles across all IBM experiences and services
   - Capitalization rules
   - How to display dates

-----

### Tasks
- [x] Read the current [Add and select documentation ](https://pages.github.ibm.com/cdai-design/pal/patterns/add-and-select/usage)
- [x] Review the current[ Add and select code](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-patterns-add-and-select-singleaddselect--with-hierarchy&globals=viewport:basic)
- [x] Answer: Do add and select have coded assets? (This might make it a component)
- [x] Answer: Are there multiple ways to utilize add and select? (This might make it a pattern)
- [x] Answer: Is there no code or specific components associated? Does this fall into the Guidance definition?
- [x] Gather Telemetry metrics
- [ ] Deliverable: Form an opinion on what category Add and select slot into and the future of the asset. Share with Product PAL team

**Comment by RichKummer** [comment]
## Component vs Pattern for Add & select
`Add & select` is currently under _Patterns_, but we need to see if this still holds true with the new Component and Pattern changes.

### Component
* Components are an asset that has been designed and coded: **YES**, `Add & Select fit this as they have code living in [Storybook](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-patterns-add-and-select-multiaddselect--default&globals=viewport:basic)

**Comment by RichKummer** [comment]
## Decisions
1. `Add & Select` remains a pattern.
2. It does not get deprecated in the short term.
3. Tracked until Dec 2024 to see if usage picks up.
