### ISSUE TITLE
[DataSpreadsheet]: Hitting enter on a cell does new line instead of entering edit mode on same line

### ISSUE THREAD

**Issue by AustinGitHub** [carbon-design-system/ibm-products#5330]
### Package

Carbon for IBM Products

### Description

https://github.com/carbon-design-system/ibm-products/assets/10100397/31e79048-8557-402c-9e9d-8c142027ebc5

### Component(s) impacted

Data Spreadsheets

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.39.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Product/offering

IBM

### CodeSandbox or Stackblitz example

https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-data-spreadsheet-dataspreadsheet--data-spreadsheet&globals=viewport:basic

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues
```[tasklist]
### Tasks
- [ ] Pressing enter should cause the current cell to enter edit mode and not apply new line, unless the cell is already in edit mode
```

**Comment by AustinGitHub** [comment]
Will take a look at this today
