### ISSUE TITLE
Explore: Edit and update

### ISSUE THREAD

**Issue by aubrey-oneal** [carbon-design-system/ibm-products#5338]
We need to have a better understanding of the current `Edit and update` pattern in order to determine if it is a component, pattern or guidance based on the new definitions.

#### Component
An asset that has been designed and coded
- Export is a component because there is a coded modal provided specifically to export

#### Pattern
Something that can be accomplished in multiple ways utilizing a combination of component(s) with additional design considerations (a recipe of components)
- Patterns may provide coded examples, but will not be required to provide code or support every possible instance of a pattern
- Dashboards are patterns because you can build a dashboard in many different ways
   - Various sized tiles
   - Various components, actions, information within those tiles

#### Guidance 
Overarching direction or instruction that can be applied across an entity
- As you move further away from the “core” of the spoke, we may see more detailed guidance and opinion on guidance at the “spoke” levels
- Content is guidance because we apply the same principles across all IBM experiences and services
   - Capitalization rules
   - How to display dates

-----

### Tasks
- [x] Read the current [Edit and update](https://pages.github.ibm.com/cdai-design/pal/patterns/edit/usage)
- [x] Review the current [Edit and update code](https://carbon-for-ibm-products.netlify.app/?path=/docs/ibm-products-patterns-edit-and-update-editfullpage--docs)
- [x] Answer: Do `edit and update` have coded assets? (This might make it a component)
- [x] Answer: Are there multiple ways to utilize `edit and update`? (This might make it a pattern)
- [x] Answer: Could `edit and update` be categorized into "common actions" or 'CRUD' (create, read, update, delete)
- [ ] Form an opinion on what category `edit and update` slot into and the future of the asset. Share with Product PAL team

**Comment by oliviaflory** [comment]
#### Answer: Do `edit and update` have coded assets? (This might make it a component)
Production
- Edit in place

Canary/Experimental
- Edit full page
- Edit side panel
- Edit tear sheet
- Edit tear sheet narrow
- Edit update cards

#### Answer: Are there multiple ways to utilize `edit and update`? (This might make it a pattern)
- Yes
- The guidance is very broad and not written consistently
- It also covers components that are not included in the code (data table and text editors?)
#### Answer: Could `edit and update` be categorized into "common actions" or 'CRUD' (create, read, update, delete)
- Not exactly a CRUD
- Possibly common actions?
#### Form an opinion on what category `edit and update` slot into and the future of the asset. Share with Product PAL
