### ISSUE TITLE
TagSet overflow does not appear when in Datagrid

### ISSUE THREAD

**Issue by csamarchi** [carbon-design-system/ibm-products#5407]
### Package

Carbon for IBM Products

### Description

The expected behavior is when user clicks on the `Tagset` button to see more tags, the overflow menu should appear with listed tags. Instead, you click, and nothing appears. 

![Screenshot 2024-05-29 at 11 01 17 AM](https://github.com/carbon-design-system/ibm-products/assets/42501494/6263f297-30f4-4a58-91c3-cc59cbb74b76)

https://github.com/carbon-design-system/ibm-products/assets/42501494/6a1b9cc9-7a42-4a26-8d9c-e3ae654b356c

![tagsetoverflow](https://github.com/carbon-design-system/ibm-products/assets/42501494/71a91884-5e15-4809-8542-bd271c178280)

### Component(s) impacted

`TagSet`, `Datagrid`, `SidePanel`, & `SidePanelContainer`

Slack conversation [here](https://ibm-cloudplatform.slack.com/archives/C013ZTX0N6B/p1716998590411699)

Code snippet:
![Screenshot 2024-05-29 at 11 02 33 AM](https://github.com/carbon-design-system/ibm-products/assets/42501494/15383dc3-31cb-4399-b540-6e935d85a1f3)

TagSet docs [here](https://carbon-for-ibm-products.netlify.app/?path=/docs/ibm-products-components-tag-set-tagset--docs)

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

v^1.72.2

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

Projects-ui

### CodeSandbox or Stackblitz example

https://stackblitz.com/edit/github-q7ndbt?file=src%2FExample%2FExample.jsx

### Steps to reproduce the issue (if applicable)

1. Click into SidePanel
2. Find Tags `+n` in Datagrid
3. Click `+n`
4. Overlay should show

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues
```[tasklist]
### Tasks
- [ ] Put together demo for v2 using tag overflow in datagrid
```

**Comment by davidmenendez** [comment]
i have confirmed this behavior is appearing in C4P v1 as well as v2 and it appears to be confined to overflow within the context of a datagrid

**Comment by elycheea** [comment]
@csamarchi Unfortunately with EOS for Carbon 10 coming up in September, we will not be adding this fix for v1. If you need assistance with a workaround, you’re welcome to join one of our upcoming office hours. Our next one is the first week of September.

**Comment by davidmenendez** [comment]
hey @csamarchi a fix has been issued to resolve this bug and should be available in our next release.

if you look at the [fix PR](https://github.com/carbon-design-system/ibm-products/pull/6005) all you need to do is use the new `autoAlign` functionality in `TagSet` to alleviate the visual bug
