### ISSUE TITLE
DataGrid with sticky columns , the header is not sticky 

### ISSUE THREAD

**Issue by marinamas** [carbon-design-system/ibm-products#5431]
### Package

Carbon for IBM Products

### Description

When a DataGrid column is made sticky , only the row data gets sticked to the left/right  but the header is not sticky.

### Component(s) impacted

DataGrid

### Browser

Chrome, Safari, Firefox, Microsoft Edge

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

"@carbon/ibm-products": "2.41.0",

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Product/offering

Infrastructure 

### CodeSandbox or Stackblitz example

https://codesandbox.io/p/sandbox/rowactions-f7jsfq?file=%2Fpackage.json%3A25%2C24

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues
```[tasklist]
### Tasks
- [ ] Column header should remain sticky, see [here](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid--batch-actions&globals=viewport:basic) for incorrect behavior
```
