### ISSUE TITLE
[ConditionBuilder]: naming of `variant` prop

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#5436]
### Summary

As @elycheea and myself started working on the complex state accessibility audit we noticed the `variant` prop for the `ConditionBuilder` component and are wondering if renaming it to match Carbon's more commonly used `type` or `kind` props makes more sense for consistency across the design system.

### Name and organization

Our team

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues
```[tasklist]
### Tasks
- [ ] Update Storybook to use option instead of manually type string
```

**Comment by amal-k-joy** [comment]
@elycheea @matthewgallo 
There is an update as shared by @My-Money29  to rename the variant names as  
sentence ==>Non - Hierarchical
tree ==> Hierarchical

**Comment by amal-k-joy** [comment]
@matthewgallo @elycheea 
Also if we are thinking of changing the prop name `variant`, feel like `type`  is more close .  Just saw these definition online. whats your thoughts?
Type: A category or class of things having common characteristics.
Kind: A category with a more specific characteristic; often implies a natural grouping or inherent quality.
Variant: A form or version of something that differs in some respect from other forms of the same thing or from a standard.
