### ISSUE TITLE
Update asset index page with new components and products lists

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/ibm-products#5492]
Update the Asset index page on new site with new Airtable to reflect new list of components and patterns
New airtable link: https://airtable.com/appY30x3q9FcdIcL1/shrRvKKu57LqbiEqf 

Old Asset index: https://pages.github.ibm.com/cdai-design/pal/overview/asset-index
New asset index: https://pages.github.ibm.com/carbon/ibm-products/overview/asset-index

```[tasklist]
### Tasks
- [ ] Rename copied Airtable to Carbon for IBM Products v11
- [ ] Update link for Components view
- [ ] Update link for Patterns view
- [ ] Update link for Guidelines view
- [ ] Remove Connected Experiences
```
