### ISSUE TITLE
Evaluate Keyboard tabs and Keyboard guidelines pages

### ISSUE THREAD

**Issue by aubrey-oneal** [carbon-design-system/ibm-products#5504]
There is both a [keyboard shortcut guidelines ](https://pages.github.ibm.com/cdai-design/pal/patterns/keyboard-shortcut-guidance/usage/)page in Patterns and a [Keyboard (operation) guidance](https://pages.github.ibm.com/cdai-design/pal/keyboard-guidance) page.

### Keyboard shortcut guidance
This pattern is suggesting a consistent way to show a user the keyboard shortcuts within a product
- Explore if core would like to move this to their guidelines
- There is no coded asset for this as of today

### Keyboard (operation) guidance
This is "pattern" is outlining how to annotate keyboard operations of a product, likely used to hand off to a developer
- Evaluate if this content is up to date (check with Gower?)
- Is this content duplicative to other areas? (Carbon core or Accessibility)
---

- [ ] Work with our accessibility experts to merge and update this content @mbgower
- [ ] Add any additional missing Accessibility guidelines. 
- [ ] Either create a Figma or MDX draft of this content. It will live in a new page Guidelines>Accessibility, to be created in issue #5503 
```[tasklist]
### Tasks
- [ ] Explore if this should move to core as part of website phase 1
```

**Comment by elycheea** [comment]
@aubrey-oneal I always considered these two a bit different even though at a glance they feel similar. One is more guidance on how to design (and annotate) keyboard interactions (actually guidelines) — this could possibly be merged with Accessibility content though.

“Keyboard Shortcut Guidance” could probably be called just “keyboard shortcuts” (a pattern!) and be more focus on how we trigger and display shortcuts for experiences that does include them.
