### ISSUE TITLE
Style picker

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#5511]
### The problem

Products need a way to provide theming and customization that enhance distinction through the use of elements such as color and icons.

### The solution

The style picker allows users to customize icons, colors, or shapes in their UI, based on their preferences or requirements.

### Design link

https://pages.github.ibm.com/carbon/ibm-products/components/style-picker/usage/

### Owner/main maintainer(s)

Jonathan Nagel

### Second/backup maintainer(s)

@janhassel

### Product/offering

watsonx.gov
watsonx.ai
Apptio
DataStage

### Business priority

Medium Priority = upcoming release but is not pressing

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### Acceptance criteria
- [x] Evaluate the original [style picker prototype](https://github.ibm.com/CDAI-UX-Engineering/dsag-condition-builder-prototype/tree/main/src/components/StylePicker) and code
- [x] Refine initial style picker requirements

**Comment by ljcarot** [comment]
@lily-peng I've tagged you as assigned to this Epic and that you're working on this in Carbon Labs:Web Components.  Sound good?

**Comment by sstrubberg** [comment]
So pumped for this. @lily-peng. DM directly on Slack if anything comes up. We're really excited about Carbon Labs and I want to make sure you have all the support you need.

**Comment by AlexanderMelox** [comment]
Maybe utilizing lit/react package to automatically create the React component version?

https://lit.dev/docs/frameworks/react/

**Comment by jeffchew** [comment]
> Maybe utilizing lit/react package to automatically create the React component version?
> 
> https://lit.dev/docs/frameworks/react/

My answer to this is, why build it twice?

**Comment by AlexanderMelox** [comment]
@jeffchew I think we will look into this and see what are the biggest changes between the two

**Comment by makafsal** [comment]
The approach @AlexanderMelox sounds good to me. Also, `@lit/react` seems promising.
