### ISSUE TITLE
[Datagrid]: useColumnRightAlign order matters

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/ibm-products#5586]
### Package

Carbon for IBM Products

### Description

The order of addons matters when using `useColumnRightAlign` with `Datagrid`. In this particular order, the column header is not visible.

```js
// the column header labels are hidden
const datagridState = useDatagrid(
  { columns, data },
  useColumnRightAlign,
  useSortableColumns,
);

// the column header labels are shown as expected
const datagridState = useDatagrid(
  { columns, data },
  useSortableColumns,
  useColumnRightAlign,
);
```

### Component(s) impacted

Datagrid

### Browser

Microsoft Edge

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.43.1

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Product/offering

-

### CodeSandbox or Stackblitz example

https://stackblitz.com/edit/github-pdwkyw

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues
```[tasklist]
### Tasks
- [ ] Double check order of plugins, ensuring that column header is still visible
```
