### ISSUE TITLE
Asset index page: Update Airtable links

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-products#5658]
We will need to update the Airtable links on the Asset index page to reflect the latest updates of component vs pattern assets.

```[tasklist]
### Tasks
- [ ] Rename copied Airtable to Carbon for IBM Products v11
- [ ] Update link for Components view
- [ ] Update link for Patterns view
- [ ] Update link for Guidelines view
- [ ] Remove Connected Experiences
```

**Comment by ljcarot** [comment]
I updated the AirTable name to 'v11 of Carbon for IBM Products'. Is that okay?  https://airtable.com/appY30x3q9FcdIcL1/tblWw6RHMVPAAmXc2/viwDt5hjrziPekED5?blocks=hide

**Comment by oliviaflory** [comment]
@ljcarot that's great! I am going to close this issue in favor of #5492 I didn't see it initially!
