### ISSUE TITLE
DataGrid : multiLineWrap wrap doesn't apply for the table header 

### ISSUE THREAD

**Issue by marinamas** [carbon-design-system/ibm-products#5662]
### Package

Carbon for IBM Products

### Description

- Create a Datagrid table and add multiLineWrap = true for one column.
- multiLineWrap doesn't wrap the column header

Expectation:
I should be able to wrap Table header. Incase the column name is too big   , adding width will only include (...) in the header. There should be a way user should be able to see the Header name as below
![image](https://github.com/carbon-design-system/ibm-products/assets/80206173/0ac487b5-2d36-48d9-b20d-f4b14b427800)

### Component(s) impacted

Datagrid

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

"@carbon/ibm-products": "2.40.0",

### Suggested Severity

None

### Product/offering

NA

### CodeSandbox or Stackblitz example

https://codesandbox.io/p/sandbox/datagridfilter-forked-6xz574?file=%2Fsrc%2FExample.js%3A115%2C27

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues
```[tasklist]
### Tasks
- [ ] `multiLineWrap` should wrap only 2 lines for column headers
```

**Comment by ljcarot** [comment]
We've been investigating [TanStack ](https://tanstack.com/table/latest)[Table](https://tanstack.com/table/latest), a third-party, open-source offering, which provides extensive data table capabilities surpassing what our Carbon Datagrid offers. It provides much more flexibility and customization. TanStack Table is headless which means it can easily be added alongside Datagrid component in your product or application. The benefits of more flexibility for product teams and less maintenance for Carbon makes it a win win. Lastly, it is available in multiple frameworks including [React](https://github.com/carbon-design-system/tanstack-carbon/tree/main/react#readme) and [Web Component](https://github.com/carbon-design-system/tanstack-carbon/tree/main/web-components#readme) so it provides an option to non-React product teams.

For these reasons, we have decided to transition from building our own custom table component to using an example-based approach with TanStack Table. Datagrid will still exist in our library for existing teams but we are announcing the deprecation* of the Datagrid component in v2.54.0 release so teams can begin to work through the transition. Details about how to use both Datagrid and TanStack together can be found [here](https://github.com/carbon-design-system/tanstack-carbon/tree/main). 

*Deprecation means that no new features will be added however sev 1 and sev 2 bugs will be supported.
