### ISSUE TITLE
DataGrid violates content security policy.

### ISSUE THREAD

**Issue by Rakesh-Addepalle** [carbon-design-system/ibm-products#5678]
### Package

Carbon for IBM Products

### Description

In our project we enabled content security policy (CSP), Data grid is using inline styles which is violating CSP policy, because of this styles are not applied, and error's triggered in console.

### Component(s) impacted

Datagrid

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.44.0

### Suggested Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Product/offering

OpenPages

### CodeSandbox or Stackblitz example

https://stackblitz.com/edit/github-fenvlt?file=src%2FExample%2FExample.jsx

### Steps to reproduce the issue (if applicable)

Put this meta tag in html page to enable CSP

`    <meta
      http-equiv="Content-Security-Policy"
      content="default-src 'none'; connect-src 'self'; script-src 'self'; img-src * data:; style-src 'self'; frame-src *"
    />`

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues
```[tasklist]
### Tasks
- [ ] Replace `style={{}}` usage with classNames where appropriate
- [ ] Set [dynamic styles](https://github.com/carbon-design-system/carbon/blob/main/docs/style.md#authoring-dynamicinline-styles) using `useIsomorphicEffect()`
- [ ] Configure `react/forbid-component-props` in eslint to flag invalid usage of `style`
```

```[tasklist]
### Datagrid component requiring updates
- [ ] `useActionsColumn`
- [ ] `DatagridExpandedRow`
- [ ] `DatagridVirtualBody`
- [ ] `FilterPanel`
- [ ] `InlineEditCell`
- [ ] Any other components that receive spread props with `style` being applied
```

**Comment by AmandaFurukawa** [comment]
Can we get an ETA on this bug?

**Comment by AmandaFurukawa** [comment]
This bug is currently blocking us from delivering features planned for our 9004 release in September

**Comment by ljcarot** [comment]
@elycheea @kennylam can you see about fitting this in current sprint since high impact.  Kenny has experience with CSP from dotcom I believe.

**Comment by AmandaFurukawa** [comment]
Any updates on this?

**Comment by davidmenendez** [comment]
@AmandaFurukawa it's currently in progress #5831

**Comment by Rakesh-Addepalle** [comment]
Although the issue has been marked as closed https I was still able to reproduce it. You can check the StackBlitz link here: https://stackblitz.com/edit/github-fenvlt?file=package.json, where the issue is consistently reproducible.
<img width="1108" alt="Screenshot 2024-09-20 at 11 21 16 AM" src="https://github.com/user-attachments/assets/a3bef821-7d18-458a-8310-f5221ebfb0e0">
FYI: -@AmandaFurukawa

**Comment by kglickman** [comment]
This is very high priority!  We had pushed a feature into a future release in order to wait for this fix but we can't wait for another whole release.  Can this please be re-opened as Critical?  What is the process for that?

**Comment by ljcarot** [comment]
@elycheea I have reopened this.  This probably didn't show up in Triage list because it is a closed issue.  Can we have someone investigate why this update didn't work?  cc @anamikaanu96

**Comment by anamikaanu96** [comment]
Hey @Rakesh-Addepalle I did some investigation on this.

I created a basic React [project](https://stackblitz.com/edit/vitejs-vite-ddxucy?file=src%2FApp.tsx) in Stackblitz and added the CSP metadata, it also throws the same error because of the presence of import statement of scss files in main.jsx.  So we concluded that, this issue is not coming from `@carbon` / `@carbon/ibm-products` . Basically,  all the import statement of scss files cause [csp violation in react apps](https://github.com/facebook/react/issues/5878).
To improve content security, one thing we can do from our end is avoiding inline styles in the components and we have already done that.  To address the remaining issues, you might consider dynamically adding a nonce or hash to CSS imports using a Webpack configuration, something similar to what's outlined in this [link](https://stackoverflow.com/questions/71248765/adding-nonce-to-content-security-policy-in-a-react-app). I believe, this needs to be done in application level not in component library.

Also we have similar [issue](https://github.com/carbon-design-system/carbon/issues/12580) mentioned in carbon as well.

https://github.com/user-attachments/assets/e19a0934-3f51-454c-a191-6c2338c7040f

cc : @elycheea @ljcarot

**Comment by kglickman** [comment]
I am a teammate of Rakesh.  We are already using a webpack nonce and all our Carbon components with css imports load fine with it.  @Rakesh-Addepalle can  you try to repro in Stackblitz with __webpack_nonce__ set to a dummy value (i.e. "fakeNonce") in the very first line in the main.jsx file and put the matching nonce into the CSP like 'nonce-fakeNonce'.

**Comment by kglickman** [comment]
Oh, is that going to work with Vite?  I don't know anything about it but it seems like it wouldn't.

**Comment by kglickman** [comment]
I just tried by changing to add the bold
      content="default-src 'self' **'strict-dynamic' 'nonce-fakeNonce'**; connect-src 'self'; script-src 'self'; img-src * data:; style-src 'self'; frame-src *"

and `<script type="module" nonce="fakeNonce" src="/src/main.jsx"></script>` to add the fakeNonce but it's not helping.  

There's some stuff here about doing nonce's in Vite but I don't have time to learn Vite right now.  https://github.com/vitejs/vite/issues/9719

Is there a StackBlitz template for Webpack instead?

@Rakesh-Addepalle Does the error we're seeing in the product seem to be the same thing as the one in the StackBlitz?

**Comment by kglickman** [comment]
@anamikaanu96 I'm still seeing plenty of inline styles on the storybook page for version 2.50.0.

![image](https://github.com/user-attachments/assets/ed933125-498f-4ff7-a924-c322522976c7)

**Comment by Rakesh-Addepalle** [comment]
@anamikaanu96 I can confirm that when using carbon data table in our product we were not facing  any CSP errors as it doesn't contain inline styles. We already implemented webpack nonce in our product.
 **Carbon Data table** :- 

<img width="1489" alt="Screenshot 2024-09-30 at 11 26 47 AM" src="https://github.com/user-attachments/assets/e3d9d644-fe25-4e95-944b-caf9dab73453">


Ibm-products data grid:- 

<img width="1466" alt="Screenshot 2024-09-30 at 11 28 19 AM" src="https://github.com/user-attachments/assets/267e1095-06eb-4e4c-8eba-cae11850b564">

**Comment by anamikaanu96** [comment]
Hey @Rakesh-Addepalle can you provide the errors that you are getting in console?

**Comment by Rakesh-Addepalle** [comment]
Hi @anamikaanu96, I have updated stackblitz to use nonce for script and style tags still was able to reproduce the issue.
https://stackblitz.com/edit/github-fenvlt-ta4ybx?file=index.html
<img width="1490" alt="Screenshot 2024-09-30 at 1 59 53 PM" src="https://github.com/user-attachments/assets/b359a9b4-e51f-4a64-bac6-61706db09fd4">

**Comment by kglickman** [comment]
Not sure if anyone saw my post here https://github.com/carbon-design-system/ibm-products/issues/5678#issuecomment-2379154508.  I can see the inline styles in the story book.

**Comment by kglickman** [comment]
@Rakesh-Addepalle The link that you attached that has the nonce added via Vite seems to be pointing to an older version of the stackblitz.  I'm not seeing the nonce in it.  With the nonce, the inline styles ought to work, so I'm confused.

**Comment by Rakesh-Addepalle** [comment]
@kglickman If I add **unsafe-inline** to style-src then css will load without any errors.
<img width="1493" alt="Screenshot 2024-09-30 at 7 25 15 PM" src="https://github.com/user-attachments/assets/afa8d6fa-406a-49b7-8702-94ffd80c29be">

Without  **unsafe-inline**
<img width="1481" alt="Screenshot 2024-09-30 at 7 12 21 PM" src="https://github.com/user-attachments/assets/961f7b67-9298-4d50-bd74-49696559e536">

 I am able to connect to latest code, Can you please try once again.
https://stackblitz.com/edit/github-fenvlt-ta4ybx?file=index.html,vite.config.js

**Comment by kglickman** [comment]
@matthewgallo I don't think you need to create the webpack stackblitz template.  The grid is loading fine with the hard-coded Vite nonce.  Now I need to figure out what is that we are doing that is different than the sample code.

**Comment by kglickman** [comment]
I have a reproduceable case that occurs when there is initially no data in the grid.  https://stackblitz.com/edit/github-fenvlt-8jark3

**Comment by amal-k-joy** [comment]
Thanks for sharing new stackbltiz. 
As I checked the issues in the console, looks like the errors are throwing from the SVG images used in Empty state component when there is no data in the grid and not from the Datagrid component.
We believe we’ve addressed the CSP issues specific to Datagrid but have opened a follow up issue for reviewing the rest of our components and patterns and that will address this issue as well.

**Comment by AlexanderMelox** [comment]
Immediate datagrid issues have been address and open a follow up issue #
