### ISSUE TITLE
Condition Builder - Tree Variant  - Design Review

### ISSUE THREAD

**Issue by My-Money29** [carbon-design-system/ibm-products#5687]
Conduct a design review for the [Tree variant storybook](https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-conditionbuilder--condition-builder&globals=viewport:basic)

[Template](https://github.com/carbon-design-system/ibm-products/blob/main/docs/reviews/DESIGN_REVIEW_GUIDELINES.md) instructions to follow
[Design QA checklist](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/wiki/Definition-of-done-(Visual-QA-checklist)) from Carbon for IBM.com

```[tasklist]
### Tasks
- [ ] Checked the tree variant against all items in the review template
- [ ] Bugs and/or inconsistencies have been documented
```

# Design review notes:

## 1. [Design QA Checklist](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/wiki/Definition-of-done-(Visual-QA-checklist))

Component visual QA should be done to cover the following aspects:
1. Check for grid usage on all breakpoints

- [x] Beyond max
- [x]     max
- [x]     xlg
- [x]     lg
- [ ]     md - We need to add a capability for horizontal scrolling.
- [ ]     sm - We need to add a capability for horizontal scrolling.

2. Interactive states using correct styling

- [x] Default
- [x]     Hover
- [x]     Active
- [x]     Focus
- [ ]     Keyboard navigation 
- [x]     Other non-universal states such as selected in Table of content

3. Content edge cases

- [x]     Minimal content
- [x]     Maximum content
- [x]     Text line wrap
- [x]     With & without optional content

4. Theming

- [x]  White theme
- [x]     Gray 10 theme
- [x]     Gray 90 theme
- [x]     Gray 100 theme

6. Code

- [ ]     Color: No hardcoded color value unless explicitly requested by design
- [ ]     Typography: No hardcoded type styles unless explicitly requested by design
- [ ]     Pass all checks (except Percy when style changes are expected)
- [ ]     If PR addresses styling change, run a Percy test locally to catch obvious regressions.

<hr />

### 1. Keyboard navigation 
a. Firefox:
- [x] Tab scrolls through; a. Conditional operators of groups. b. Logical operator between groups.
- [x] Left and right arrows scroll through condition's cells.
1. Missing 'Return" OnClick event - Selecting any other operator than "Is", when selecting any Property and pressing the `Return` button doesn't select the value, leaving the popover open without the ability to focus on other popovers.

https://github.com/user-attachments/assets/94adbb2b-c579-472f-8367-2994e33f9313

2. Not sure if this is a browser controlled issue or not, but, when scrolling a list of Properties that has a scrollbar, the first two clicks on the down arrow, scroll the whole pop-over.
I imagine the scroll to reveal more options in the list should occur when the user is focusing on the bottom 2-3 items of the list.

This becomes an issue when focus is on the last item on the list, and the up arrow scrolls the list up, hiding the current focused item.

https://github.com/user-attachments/assets/879fb8ab-5cac-49d6-9099-3a18b9ff0b0e

<hr />

### 2 Accessibility test indicates one incomplete result.

![Image](https://github.com/user-attachments/assets/d1e59dbd-3c30-40ac-8f79-0afb6c897246)

<hr />

### 3. Entry point 

1. Change to sentence case.
4. Comparison of storybook to Button Figma asset:
a. Looking closely at the button in the storybook, it seems that the text and icon aren’t aligned to the center of the button’s frame.
b.  Seems like the icon isn’t aligned to the text.
c. Not sure, but, it seems like the icon is smaller than the original 8px icon. Are we employing custom code on this button?
d. Color token for [Ghost - Label](https://carbondesignsystem.com/components/button/style/#ghost-button) should match $link-primary
e. Color token for [Ghost - Label:hover](https://carbondesignsystem.com/components/button/style/#ghost-button) should match $link-primary-hover

100% view
![Image](https://github.com/user-attachments/assets/d8d28609-a41c-49a8-b53b-3dc2ee499f41)

500% view
![Image](https://github.com/user-attachments/assets/84e2f44f-bcb9-4905-bde2-ab338f99e31e)
(1 pixel difference in height of Primary text between the storybook and the Figma mockup)

<hr />

### 4. Tooltip
**a. Appears after value selection.**
- In some cases the tooltip disappears only after click, in some cases not.
- Intended behavior - Shouldn't appear after value selection.

https://github.com/user-attachments/assets/35bb8027-dd16-4035-b828-8ab172a215f6

**b. Utilizing the Icon Tooltop variant**
- The `Standard tooltip` appears when hovering on-top of icons.
- Intended behavior - utilize `Icon tooltip` for Delete, Add condition, Add subgroup and Add condition group buttons.
- If possible, It would be best to utilize the `Icon tooltip` variant for all the tooltips. Currently, when a user hovers over a cell that initiates a tooltip, and would like to interact with conditions at the top of the current condition, is blocked by the initiated tooltip. Either that, or we set the duration of the tooltip to the 0, Although from a visual perspective I think the Icon tooltip would be most fitting. Attaching an example:

https://github.com/user-attachments/assets/52d2e8eb-9c3c-4bcd-abbf-0a835dbcffda

Thoughts, @elycheea ?

**c. Data type; ID Long - Text wrap within tooltip**

Text doesn't wrap correctly
![Screenshot 2024-07-21 at 12 09 28](https://github.com/user-attachments/assets/9d3ff766-2189-48b3-a085-9dd87817e224)

**d. Tooltip indication for condition cells.**
In the process of setting up a condition, while hovering, tooltip for cells should indicate the dedicated cell's type. Current tooltip text reads "Add condition" for 3 cell types. Intended text should read-  Add property | Add operator | Add value.

Current:

![Image](https://github.com/user-attachments/assets/84b3ab13-e8b9-4c06-835b-2c154d29aa51)

![Image](https://github.com/user-attachments/assets/05b3761c-34d5-4474-9b90-69dc2f11eebf)

![Image](https://github.com/user-attachments/assets/c28e8dae-08bb-48f3-8b91-c19057527d0b)

**e. Tooltip for deleting a condition/subgroup**
Tooltip should read "Delete condition" / "Delete subgroup" respectful of each condition type.

Current:

![Image](https://github.com/user-attachments/assets/180f0c87-05c9-41ea-add2-17b835531ca5)

![Image](https://github.com/user-attachments/assets/d13cd8dc-28de-4d20-bb02-90da71a8bd29)

<hr />

### 5. Logical operator text alignment within cell
- Text within cell should align with first condition's text. 

![Screenshot 2024-07-21 at 12 21 17](https://github.com/user-attachments/assets/357bb878-7ce8-42d6-b95e-f20ef33e14cc)

<hr />

### 6. Add condition/subgroup hover-preview - bottom spacing
- Bottom spacing isn't set.
- Intended - $spacing02 to be added to the previewed condition/subgroup

![Screenshot 2024-07-21 at 11 54 07](https://github.com/user-attachments/assets/0640dc02-84d8-4cde-a8dd-59be0f6eec29)

<hr />

### 7. Deleting conditions
a. Change "Remove" to "Delete"
b. Every few consecutive deletes, a condition remains in focus state, and cannot be interacted with. Only a click outside of the condition reverts the condition to enabled.

https://github.com/user-attachments/assets/995f6e1d-26b1-4a51-9f96-b54bfaec13a1

c. Condition delete should delete a single condition.
- On delete button hover, only the single condition should be indicated for deletion.

<hr />

### 8. Color swatches 

a. Tokens.
**b. Reset color value within a group after 5 conditions.**
Current:
![Screenshot 2024-07-22 at 10 54 25](https://github.com/user-attachments/assets/c1994fe6-5af9-4dec-a47a-354c91f338c4)

Intended
![Screenshot 2024-07-22 at 10 52 16](https://github.com/user-attachments/assets/21db77ea-1cfd-46aa-9997-7284754537ae)

**c. Color order for condition groups**
1. Purple
2. Blue
5. Cyan
6. Teal
7. Green
8. Purple

![Screenshot 2024-07-22 at 11 09 21](https://github.com/user-attachments/assets/24c4844d-5b3a-4e1b-b4c7-fed8ae5eadf0) 
D. New condition group - Hover-preview color token

### 9. Warning icon
- Current utilizes the white exclamation mark.
- Intended - Exclamation color `Gray 100`

### 10. Hierarchical variant add button appearance

a. Add condition and subgroup buttons should appear without a top stroke, regardless of the fact that they belong to a condition or subgroup.

Intended:
![Screenshot 2024-07-24 at 16 25 40](https://github.com/user-attachments/assets/22092397-cacc-4666-be33-9a4848bc7dbd)

b. `Add subgroup` button should be in the same size as the `Add condition` button
Right now the Add subgroup spans 34px width

![Screenshot 2024-07-24 at 16 32 58](https://github.com/user-attachments/assets/3a4c0b17-da8e-4fc8-9c46-45596b7fcc31)

<hr /> 

### 1. Renaming both variants
- Sentence - Non-Hierarchical
- Tree - Hierarchical

<hr />

### 2. Conditional operators
We're adopting the calculation that Jan offered in his [storybook](https://pages.github.ibm.com/CDAI-UX-Engineering/dsag-condition-builder-prototype/?path=/story/components-conditionbuilder--tree)

The only difference is in naming of each conditional operator:

| Original name      | New name     |
| ------------- | ------------- |
| If all of | If all |
| If any of | If any |
| If not all | Unless all | 
| If not any | Unless any | 

Description of each Conditional Operator:
We have four options that the user can choose from. Here are the current placeholder labels together with an example and possible longer, more descriptive label as well as the technical expression they resemble:
1. if all
Example: “show all items that are paid and shipped”
Longer: “if all of the following are true”
Technical: a && b

2. if any
Example: “show all items that are paid or shipped”
Longer: “if any of the following are true”
Technical: a || b

3. Unless all
Example: “show all items that aren’t shipped and paid”
Longer: “if not all of the following are true”
Technical: !(a && b)

4. Unless any
Example: “show all items that are neither paid nor shipped”
Longer: “if none of the following are true”
Technical: !(a || b)

- Question for @amal-k-joy, @janhassel; Would the 4 conditional operators be available for the Non-Hierarchical variant as well? 

- Non-Hierarchical - In terms of functionality, a user can interact with the logical operator as they could before, only now a click on the logical and/or also changes the Conditional operator as well.

<hr />

**Comment by amal-k-joy** [comment]
@My-Money29 Added comment as **_Fixed_** against the above issues
Fyi, we have [this](https://github.com/carbon-design-system/ibm-products/issues/5706) task to track dev items.
