### ISSUE TITLE
Condition Builder design review issues and changes

### ISSUE THREAD

**Issue by amal-k-joy** [carbon-design-system/ibm-products#5706]
```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5739
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5748
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5740
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5749
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5750
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5751
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5752
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5770
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5790
```

**Comment by aubrey-oneal** [comment]
@My-Money29 We were refining issue and wanted to check in to see if you need to look at this one.

**Comment by amal-k-joy** [comment]
#5687 Condition Builder - Tree Variant - Design Review
