### ISSUE TITLE
[Feature Request]: Add an option to open by default not-stacked coachmarks

### ISSUE THREAD

**Issue by gcattan** [carbon-design-system/ibm-products#5709]
### The problem

I am opening a feature request, as suggested in the slack [channel](https://ibm-analytics.slack.com/archives/C013ZTX0N6B/p1721660925339699?thread_ts=1721656402.579709&cid=C013ZTX0N6B).

I would like to have this Coachmark to be open by default:

![image](https://github.com/user-attachments/assets/0bbc4bc2-7e73-4a86-a928-f7ed1e7086c6)

In the code it seems to be hardcoded depending on whether or not the `overlayKind` is slacked`:

![image](https://github.com/user-attachments/assets/04aedeb3-5967-4e99-b4a7-470a4ba3032e)
 

### The solution

Add an "isOpen" parameter to the Coachmark. 
If it is undefined, the default behavior is the existing one (open for slacked coachmark and closed otherwise).
If it is defined, the Coachmark is open or closed initially depending on the value of "isOpen"

### Owner/main maintainer(s)

gcattan/Jamie Har

### Product/offering

IBM Knowledge Center / Lineage

### Business priority

Low to Medium

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues
```[tasklist]
### Tasks
- [ ] Add support for open state
- [ ] Update Coachmarks usage to reflect the open-by-default use case
```

**Comment by oliviaflory** [comment]
@oliviaflory to check with Cameron and Paul from Security

**Comment by oliviaflory** [comment]
From Cameron:
- We are ok with this and could see a use case for it. Particularly in sandbox trials where it would be helpful to autodisplay the coachmark and still leave a persistent beacon after it’s closed. 
- Our team will update the usage guidance to highlight this use case as well. 
- In contrast, if it’s a first time use scenario where a coachmark would be displayed to drive usage—a beacon would not be necessary to include with the open coachmark NOR should it show up after dismissing the coachmark

**Comment by elycheea** [comment]
@gcattan @cameroncalder did sign off on this one. Would you be interested in contributing this to our library? Thanks!

**Comment by gcattan** [comment]
@elycheea yes, sure, I can give a hand here. 

I forgot to update the description, so this is apparently my mistake, but this is not a community contribution. This comes from some design requirements from IBM Knowledge Center/Lineage. 

I have updated the description accordingly.
