### ISSUE TITLE
TypeScript migration, final tasks

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#5718]
We're almost finished migrating all released components to typescript. We have a few more steps once that is complete to finish (following core's lead from https://github.com/carbon-design-system/carbon/issues/16360)

```[tasklist]
### Final tasks for typescript support
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5721
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5722
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5723
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5724
```

**Comment by matthewgallo** [comment]
Final tasks have been completed, any further issues the come up we can open new issues.
