### ISSUE TITLE
[Website] Draft outline for DSAG and IDL presentation

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-products#5730]
After we launch the new website we should share it in DSAG and possibly IDL playback.

This does not need to be a formal presentation (slides) it can be a walk through of what has changed and pointing to the new URL / Github

Draft and outline of points to talk through:
- New IA
   - Designing
   - Developing
   - Components
   - Patterns
   - Guidance
   - etc
- We will continue to update
- New URL
- New Github
   - How to open an issue
- Contribution process
   - We will be requiring approvals from the Product PAL team to merge new content
- Highlight any net new content
- Update to process for contribution and website publishing

```[tasklist]
### Tasks
- [x] Draft an outline: https://ibm.box.com/s/brjjxlrn2d2k412w7u1whgxjkibgsxlz
- [x] Sign up for DSAG
- [ ] Sign up for IDL (with Lauren)
```
