### ISSUE TITLE
Create PLG overview page

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-products#5732]
### We need a way to provide links to the PLG assets on our website
- The PLG assets range from inspiration to un-tested best practice guidance to guided flows
- We want to give these assets and guidance to Product teams ASAP, but we do not want to conflate production ready (most PAL assets) with experimental (PLG)

### Solution
- We have suggested creating an overview page for PLG that could provide a brief description of each PLG thing
   - How to phase that some are in progress, or assumptions, the team welcomes feedback?
- Provide links to Figma files so Product teams can see the guidance and test these new ideas out in their products
- Some PLG assets have already been published on PAL:
   - Previews
   - Onboarding / First time orientation
- Olivia started a mock up of adding more detail to the PLG landing page, but feel free to explore other options
   - [Figma link](https://www.figma.com/design/WzBzlGiRAxV8pMRrNZUllE/PLG-on-Product-PAL-website?node-id=62-4210&t=GQWrWWI7ZgjbnrTu-1)

![Image](https://github.com/user-attachments/assets/10042449-ae2b-4f7e-a0e4-d7612af70dd3)

```[tasklist]
### Tasks
- [ ] Incorporated PLG into the new IA
- [ ] Craft an Overview page
- [ ] Indicate whether links are going to Figma or staying within the site
- [ ] Share with the PLG leaders Cameron and Feride
```

**Comment by oliviaflory** [comment]
Need to open a PR to address changes. Work complete
