### ISSUE TITLE
DataGrid filter of type Radio doesn't filter properly

### ISSUE THREAD

**Issue by marinamas** [carbon-design-system/ibm-products#5742]
### Package

Carbon for IBM Products

### Description

1. Create a Datagrid table with filters
2. Add a radio filter to the table
3. When filtering string it is not looking for the exact string match 
For ex : incase two filter values are active and inactive. , using inactive as filter will return rows having active values as well. This happens with filter of type radio and dropdown
(The checkbox filter works as expected)

Attached a video for reference

https://github.com/user-attachments/assets/157071a6-3dc7-4047-903b-54456c433f9d

### Component(s) impacted

DataGrid filter of type radio

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

"@carbon/ibm-products": "2.45.0",

### Suggested Severity

Sev-2

### Product/offering

NA

### CodeSandbox or Stackblitz example

https://codesandbox.io/p/sandbox/datagrid-clear-fliter-issue-forked-plpt64?file=%2Fsrc%2FExample.js%3A70%2C13

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues
```[tasklist]
### Tasks
- [ ] We only expect `active` radio filter to show `active` items (not `inactive`)
```

**Comment by matthewgallo** [comment]
Agreed, `exactText` looks like what we want here

**Comment by marinamas** [comment]
Yes exactText would be perfect.
 I have observed the similar behavior with the dropdown filter which doesn't match the exact string.

Checkbox  filter is using the exactText
