### ISSUE TITLE
Evaluate adding stroke to ExpressiveCard and ProductiveCard

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-products#5805]
Carbon v11 added a feature flag to tiles (cards) that adds a stroke around interactive cards. This stroke is intended to help improve the visual differentiation between a non-interactive and interactive (clickable) card.

We need to evaluate if any of the variants of Expressive card or Productive card should have a stroke prop.

1. Read the Carbon Design System documentation about [Tiles](https://carbondesignsystem.com/components/tile/usage/)
   - This will help you understand the design guidance for WHY a card should have a stroke (clickable) or no stroke (not clickable) 
   - How buttons or icons are utilized
   - Sync with Olivia based on that learning
2. Evaluate the Expressive card    
   - Start a Figma file to review all the variants 
   - Evaluate if the card should have a stroke
   - Evaluate if the card is deviating from Carbon guidance (button placement or link usage)
   - Make note of suggested changes or fixes in the Figma file for review
3. Evaluate the Productive card
   - Start a Figma file to review the productive card variants
   - Evaluate if the card should have a stroke
   - Evaluate if the card is deviating from Carbon guidance (button placement or link usage)
   - Make note of suggested changes or fixes in the Figma file for review
    
Considerations:
- If the entire area of a card is clickable that would have a stroke

Expressive:
- Expressive card often has a button as the only click target.
- Compare Carbon for IBM Products [storybook](https://carbon-for-ibm-products.netlify.app/?path=/docs/ibm-products-components-cards-expressivecard--docs) and the [website guidance](https://pages.github.ibm.com/carbon/ibm-products/components/card/expressive-card/usage/)
   - Are there any contradictions between the two?

Productive:
- Productive card often has multiple click targets or clickable areas ie:
   - multiple icon buttons
   - A header area
   - Clickable body 
   - Various footer clickable areas
- Compare C4IP [Storybook](https://carbon-for-ibm-products.netlify.app/?path=/docs/ibm-products-components-cards-productivecard--docs) and [website guidance](https://pages.github.ibm.com/carbon/ibm-products/components/card/productive-card/usage/)

Document audit in Figma file
example audit files for reference:
- 

```[tasklist]
### Tasks
- [x] Review the Core Tile docs to understand the stroke usage
- [x] Review all the versions of Expressive card and note any variant that could have a stroke
- [x] As you review the Expressive card, note any variant that goes against the Core guidance
- [x] Review all the versions of Productive card and note any variants that could have a stroke
- [x] As you review the Productive card, note any variant that goes against the Core guidance
- [x] Play back the findings to the team to consider next steps
- [x] Document any next steps in parent Epic
```

**Comment by benjamin-kurien** [comment]
Presented the following findings to the team during a design crit:

1. Rules on how stroke is used within tiles in core. 
3. Explorations on where stroke can be applied to both expressive and productive cards to keep them aligned with the guidelines in core. Examples of where stroke should not be applied in cards were also presented.
5. Gaps identified between website documents, Figma kit and story book.
