### ISSUE TITLE
TagSet doesn't support tag sizes

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/ibm-products#5923]
### Package

Carbon for IBM Products

### Description

The `TagSet` component currently doesn't support `sm` and `lg` tags.

If `size` is passed to the individual tag object, the tags render as expected but the overflow tag still uses `md` size.

### Component(s) impacted

TagSet

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.43.1

### Suggested Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Product/offering

watsonx

### CodeSandbox or Stackblitz example

-

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues
```[tasklist]
### Tasks
- [ ] Determine whether to provide enhancement on tag overflow or tag set
- [ ] Investigate if we want to move to operational tags for this
- [ ] If yes, update the overflow to use operational tag
```

**Comment by kingtraceyj** [comment]
related #5726

**Comment by elycheea** [comment]
Related to #6002 — but we can remove the `OperationalTag` work from that issue.

**Comment by amal-k-joy** [comment]
We will try to use operational tag from carbon and investigate how to show view all link.
