### ISSUE TITLE
Disable old website repo

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-products#5944]
```[tasklist]
### Tasks
- [x] Update readme that repo is read only at this point
- [x] Merge last PR (notification + README) ~2pm
- [x] Lock `main` branch in repo settings
```

**Comment by elycheea** [comment]
Branch has been locked — we could also archive the repository, but can also wait some time before we actually do that.
