### ISSUE TITLE
Create release manager schedule

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#5969]
Thanks to @annawen1’s documentation on releases, it’s probably time us to share the responsibilities.

A few ways we can document our schedule, e.g. Box note or wiki, but mostly we want to ensure where we log this is somewhere we can easily track.
```[tasklist]
### Tasks
- [x] Decide as a team where to keep schedule
- [x] Create the rotation based on schedule with lead and support roles
- [x] Add to slack
```

**Comment by matthewgallo** [comment]
https://github.com/carbon-design-system/carbon/wiki/Release-rotation possible option of using wiki similar to core. `dotcom` is using a boxnote which is another option as well

**Comment by kingtraceyj** [comment]
We will keep rotation in wiki
