### ISSUE TITLE
Setup code sandbox / stackblitz for `@tanstack/react-table` and `DataTable` example

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#5977]
### The problem

A continuation of explorations for Datagrid 2.0, we should setup stackblitz and code sandbox environments for each example that we have so far.

### The solution

See above ^

### Owner/main maintainer(s)

Our team

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues
```[tasklist]
### Tasks
- [x] Create monorepo setup, https://github.com/matthewgallo/tanstack-carbon
- [x] Setup each example as it's own package in monorepo
- [x] Create code sandbox example links
- [x] Create stack blitz example links
```

```[tasklist]
### Examples
- [x] Resizable columns
- [x] Pagination
- [x] Global filtering
- [x] Sortable columns
- [x] Customize column order
- [x] Editable cells
- [x] Row expansion
- [x] Column filtering, flyout
- [x] Infinite scroll
- [x] Nested rows
- [x] Row click (side panel)
- [x] Sticky columns
- [x] Batch actions
```
