### ISSUE TITLE
[Feature Request]: [CreateFullPage] Add support for 'onClick' for the progress bar

### ISSUE THREAD

**Issue by shocquu** [carbon-design-system/ibm-products#6030]
### The problem

\<CreateFullPage/> utilizes the [Carbon Progress Indicator](https://react.carbondesignsystem.com/?path=/docs/components-progressindicator--overview) component but doesn't allow for state control or an onClick function. We need to allow users to freely move between steps.

### The solution

Add an 'onClick' prop to CreateFullPage that triggers when the user clicks on a progress step.

### Links to other materials

- https://react.carbondesignsystem.com/?path=/docs/components-progressindicator--overview
- https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-patterns-create-flows-createfullpage--create-full-page&globals=viewport:basic

### Owner/main maintainer(s)

Lineage team ? idk

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

```[tasklist]
### Tasks
- [x] Expose `onClick` in each create step
- [x] Add tests for CreateFullPage and CreateTearsheet
```

**Comment by kingtraceyj** [comment]
This would need UX explorations for validation states.

**Comment by shocquu** [comment]
1. In our scenario, the user can only move in one direction but should be able to move back to completed steps by clicking on the step indicator. If the user is in edit mode, all steps have the status "complete" and should be clickable, unless not all requirements are met. We will handle this on our side by not providing the `onClick` handler or marking the step as disabled.
2. Unfortunately, I am unable to share the design, but I can show a video demonstrating how we want it to work.

https://github.com/user-attachments/assets/3ad664f3-31a4-4aca-96dd-2222303580c5

**Comment by shocquu** [comment]
Bump

**Comment by elycheea** [comment]
@devadula-nandan’s comments from refinement 🙂 :
> i think we can expose onclick, and let the implementer handle the access with their own validations

**Comment by shocquu** [comment]
Great! 🙂 Alternatively, allowing us to pass a custom WizardProgress would work as well (similar to the `influencer` from the [Carbon tearsheet](https://ibm-products.carbondesignsystem.com/?path=/docs/ibm-products-components-tearsheet--docs#component-api)). I also noticed that CreateFullPageStep accepts an `onNext` prop, but there’s no equivalent `onPrevious`. Would it be possible to expose that as well? We use it to track the current step. Thanks in advance!
