### ISSUE TITLE
`@tanstack/table` explorations: add web component setup in monorepo and basic examples

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#6069]
With a greater number of teams utilizing web components, we should offer web component versions for all of the DataTable/`@tanstack/table` examples that we're building.
```[tasklist]
### Tasks
- [x] Update monorepo to rename `packages` to `react`
- [x] Add a `web-component` directory at project root
- [x] Update readmes, discussing the purpose of the monorepo and links to stackblitz and csb
```

```[tasklist]
### Lit examples
- [x] Basic example
- [x] Batch actions
- [x] Customizable columns (drag and drop interaction on hold until `@dnd-kit/dom` supports sortable lists/becomes more stable)
- [ ] Editable cells
- [ ] Filter flyout
- [ ] Filter panel
- [x] Global filter (included in batch actions example)
- [ ] Infinite scroll
- [x] Nested rows
- [x] Pagination (included in batch actions example)
- [x] Resizable columns
- [x] Row click
- [ ] Row expansion
- [ ] Sortable columns
- [x] Sticky columns
- [x] Virtualized
```

**Comment by matthewgallo** [comment]
Initial setup and support for web components is complete and examples for some of the less complex extensions have been added. I'll focus next sprint on some of the more complex extensions (ie editable cells, filtering, etc.).

https://github.com/matthewgallo/tanstack-carbon/tree/main/web-components
