### ISSUE TITLE
Update Datagrid stories and docs

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#6074]
```[tasklist]
### Tasks
- [ ] Re-add missing table header story
- [ ] Re-add missing column alignment story
- [ ] Add section on resizable columns to docs
```
