### ISSUE TITLE
Tearsheet: `slug` --> `aiLabel` renaming

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#6096]
```[tasklist]
### Tasks
- [ ] Change slug prop to aiLabel
- [ ] Deprecate slug prop
- [ ] Add new duplicate classname selectors to the ailabel.scss styles
- [ ] Update classnames within AILabel components to use the new #{$prefix}--ailabel names
- [ ] Create a new sub-issue/tasklist item on https://github.com/carbon-design-system/ibm-products/issues for removing these classes as part of new major version
```

For duplicate class, this is an example:
```
- .#{$prefix}--slug .#{$prefix}--slug__button {

+ .#{$prefix}--slug .#{$prefix}--slug__button,
+ .#{$prefix}--ai-label .#{$prefix}--ai-label__button {
```

![Image](https://github.com/user-attachments/assets/bbe0a04b-612c-4fa6-a026-75d529c5467c)
