### ISSUE TITLE
Unit test coverage for `@carbon/ibm-products` components

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#6101]
This is a parallel issue to the work that @guidari has been doing in `@carbon/react`.

REF https://github.com/carbon-design-system/carbon/issues/16319

> The goal of this workstream is to increase confidence in each component, not just to increase coverage. It’s better to have 80% coverage with high-quality tests than 100% coverage with low-quality tests.

> [!IMPORTANT]  
> Read the Carbon core [kickoff notes below](https://github.com/carbon-design-system/carbon/issues/16319#issuecomment-2346817818) for implementation instructions and tips

```[tasklist]
### Add code coverage CI check
- [ ] https://github.com/carbon-design-system/ibm-products/issues/6107
- [ ] https://github.com/carbon-design-system/ibm-products/issues/6108
```

```[tasklist]
### Evaluate current test coverage
- [ ] https://github.com/carbon-design-system/ibm-products/issues/6109
```

```[tasklist]
### Tests under 80% coverage
- [ ] https://github.com/carbon-design-system/ibm-products/issues/6653
- [ ] https://github.com/carbon-design-system/ibm-products/issues/6654
- [ ] https://github.com/carbon-design-system/ibm-products/issues/6261
- [ ] https://github.com/carbon-design-system/ibm-products/issues/6262
- [ ] https://github.com/carbon-design-system/ibm-products/issues/6655
- [ ] https://github.com/carbon-design-system/ibm-products/issues/6263
- [ ] https://github.com/carbon-design-system/ibm-products/issues/6264
- [ ] https://github.com/carbon-design-system/ibm-products/issues/6265
- [ ] https://github.com/carbon-design-system/ibm-products/issues/6651
- [ ] https://github.com/carbon-design-system/ibm-products/issues/6652
```

**Comment by ljcarot** [comment]
@elycheea Can you please check the list of components and patterns above and remove any that have been flagged for deprecation?  Doesn't make sense to put the effort in to any that will be deprecated this year.

**Comment by elycheea** [comment]
I’ve removed the following from the list as components that are or should be deprecated in the near term.
 
- `ActionSet` (internal; potential to replace with `ButtonSet`)
- `ComboButton` (deprecated)
- `DataSpreadsheet` (to deprecate)
- `Datagrid` (to deprecate)
- `EditUpdateCards` (to deprecate)
- `FilterPanel` (to deprecate)
- `Nav` (to deprecate)
- `StatusIndicator` (to deprecate)
- `UserProfileImage` (to deprecate after `UserAvatar` release)

We can probably also deprioritize (and remove) the following that are being recategorized as utilities. If they are rewritten, we’ll see the coverage report in the PRs for them.

- `ScrollGradient`
- `StringFormatter`
- `TagOverflow`
- `TruncatedList`

Lastly, `CreateModal`, `StatusIcon` and `EmptyState` I’ve left in place for now since the latter two may have new versions but unclear when those will be delivered. And `CreateModal` we haven’t discussed more directly although I would recommend deprioritizing otherwise since we could rewrite this as pattern code.

**Comment by elycheea** [comment]
Checking with @matthewgallo today and looks like we’ve completed this. 🎉
