### ISSUE TITLE
Document list of components with under 80% test coverage

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#6109]
As part of the test coverage epic, we need to review where our test coverage currently is.

You can review the latest coverage by running
`yarn coverage` followed by `yarn coverage:report` for the full list of coverage.
```[tasklist]
### Tasks
- [x] Run coverage report
- [ ] Playback findings with dev team (engineering huddle or schedule time)
- [x] Create follow up task list
- [ ] Increase ActionSet code coverage
- [ ] Increase AddSelect code coverage
- [ ] Increase BigNumbers code coverage
- [ ] Increase ButtonSetWithOverflow code coverage
- [ ] Increase Carousel code coverage
- [ ] Increase CoachMark code coverage
- [ ] Increase ComboButton code coverage
- [ ] Increase ConditionBuilder code coverage
- [ ] Increase CreateModal code coverage
- [ ] Increase DataspreadSheet code coverage
- [ ] Increase Datagrid code coverage
- [ ] Increase DecoratorBase code coverage
- [ ] Increase EditUpdateCards code coverage
- [ ] Increase EmptyStates code coverage
- [ ] Increase FeatureFlags code coverage
- [ ] Increase FilterPanel code coverage
- [ ] Increase GuideBanner code coverage
- [ ] Increase InlineTip code coverage
- [ ] Increase InterstitialScreen code coverage
- [ ] Increase Nav code coverage
- [ ] Increase NotificationsPanel code coverage
- [ ] Increase OptionsTile code coverage
- [ ] Increase ScrollGradient code coverage
- [ ] Increase SidePanel code coverage
- [ ] Increase StatusIcon code coverage
- [ ] Increase StatusIndicator code coverage
- [ ] Increase SteppedAnimatedMedia code coverage
- [ ] Increase StringFotmatter code coverage
- [ ] Increase TagOverflow code coverage
- [ ] Increase TooltipTrigger code coverage
- [ ] Increase TruncatedList code coverage
- [ ] Increase UserProfileImage code coverage
```

**Comment by davidmenendez** [comment]
there are the components, hooks, or files that failed to meet the 80% coverage mark in one or more areas (statements, branches, functions, and lines).

it should be noted that some of these are getting false positives because storybook assets are being counted in some cases. for these cases we should take a similar approach to other components and include a `preview-components` folder or establish some kind of process for designating certain folders and files that should be excluded from testing and coverage reporting.

- ActionSet
- AddSelect
- BigNumbers
- ButtonSetWithOverflow
- Carousel
- CoachMark
- CoachMark/utils
- CoachMarkFixed
- CoachMarkOverlayElements
- CoachMarkStack
- ComboButton
- ConditionBuilder *
- CreateModal
- DataspreadSheet/hooks
- DataspreadSheet/utils
- pretty much all DataGrid add-ons and utils
- DecoratorBase
- EditUpdateCards
- EmptyStates
- FeatureFlags
- FilterPanel
- FilterSummary
- GuideBanner
- InlineTip
- InterstitialScreen
- Nav
- NotificationsPanel
- OptionsTile
- ScrollGradient
- SidePanel
- StatusIcon
- StatusIndicator
- SteppedAnimatedMedia
- StringFormatter/utils
- TagOverflow
- TooltipTrigger
- TruncatedList
- UserProfileImage
