### ISSUE TITLE
Condition builder initial release review issues

### ISSUE THREAD

**Issue by amal-k-joy** [carbon-design-system/ibm-products#6124]
```[tasklist]
### Tasks
- [x] Flickering while hovering the close Delete Condition button
- [x] In Firefox, when pressing Esc to close the Date Picker, it toggles the fullscreen. (preventDefault)
- [x] Remove console from stories and tests files
- [x] Remove unwanted comments
- [x] Error in console when pressing up and down arrows in the Price field
- [x] None of the descendent elements with "row" role is tabbable
- [x] Verify the <div> element with "treegrid" role has keyboard access
- [x] The element with role "treegrid" owns the child element with the role "grid" that is not one of the allowed role(s): "row, rowgroup"
```
