### ISSUE TITLE
Provide automated migration scripts

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#6126]
## Background

A number of components now have newer recommended versions in our v2 package. For each of these, we’d like to provide an automated migration script (codemod) to accompany those changes and assist in the adoption of these updates.

## Solution

Our solution should be based on the Carbon `upgrade` package but may require some work to support both our libraries’ codemods.

```[tasklist]
### Research and explore
- [ ] https://github.com/carbon-design-system/ibm-products/issues/6155
- [ ] https://github.com/carbon-design-system/ibm-products/issues/6156
```

```[tasklist]
### Integration related tasks
- [ ] Verify all the codemods list `ibm-products-*` in the `list` command in the `@carbon/upgrade` package
- [ ] https://github.com/carbon-design-system/ibm-products/issues/6377
- [ ] https://github.com/carbon-design-system/ibm-products/issues/6564
```

```[tasklist]
### List of codemods that need to be written
- [ ] https://github.com/carbon-design-system/ibm-products/issues/6306
- [ ] https://github.com/carbon-design-system/ibm-products/issues/6307
- [ ] https://github.com/carbon-design-system/ibm-products/issues/6308
```

**Comment by elycheea** [comment]
Shared by Taylor in #carbon-devs for anyone writing codemods soon —
https://codemod.com/studio

> You can add multiple text fixtures to test against all at once.

**Comment by ljcarot** [comment]
@elycheea What is status this work?

**Comment by elycheea** [comment]
@ljcarot I believe that #6306 has been approved but not yet merged. @makafsal can probably check on if there’s anything left on our end there.

I know @sangeethababu9223 was considering taking #6307 to be for the `Slug` to `AILabel` changes (component instead of prop), in which case we may want to move the issue back to refinement to make sure we don’t lose track of it. (I might open a sub-issue to track the work she did originally on `slug` to `aiLabel` prop though.)

@makafsal can you update us on whether we still have integration tasks after or if these have been covered in the initial work you, @sangeethababu9223, and @anamikaanu96 have done? Thanks!
