### ISSUE TITLE
Refactor Tearsheet ☂️ 

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-products#6127]
Epic to track issues regarding refactoring Tearsheet

We want to make Tearsheet more composable and allow for the option to move it into the Carbon core repo. 

#### Carbon for IBM Products
A number of components and/or patterns in Carbon for IBM Products have dependencies on Tearsheet

#### Carbon
- What changes need to be made to move Tearsheet into core, what are the options
   - Consult with Kenny (Tearsheet as dialogue)
 - What level of effort would our adopters face if Tearsheet is moved into core
 - Feature flags usage?

```[tasklist]
### Tasks
- [ ] [Tearsheet] Consult with devs on current `Tearsheet` problems and document what needs to be addressed in order to start design. Note 
- [ ] [Tearsheet] Design exploration to address composability
```

**Comment by RichKummer** [comment]
## Additional considerations
- [ ] `CreateTearsheet` retains a prop for [verticalPosition](https://github.com/orgs/carbon-design-system/projects/65/views/1?filterQuery=verticalposition&pane=issue&itemId=47696295&issue=carbon-design-system%7Cibm-products%7C2980) that determines how far from the top of the window the CreateTearsheet should begin. This was deprecated for `tearsheet` and was intended to be deprecated for `Create`. Verify if this is still valid – should we deprecate in `Create` and use same default spacing? Or, allow both `tearsheet` and `CreateTearsheet` to use this prop again?
- [ ]

**Comment by kingtraceyj** [comment]
@RichKummer jan noticed a discrepancy for padding in tearsheet. there are a few differences:

> Hey, we stumbled upon an inconsistency in the Tearsheet guidelines. In the Create flows guideline the wide CreateTearsheet has a 24px padding on the left and right of the main content. This is also how it’s implemented in code. On the other hand, the general, wide tearsheet guidelines specify that the padding should be 32px.
> https://pages.github.ibm.com/carbon/ibm-products/patterns/create-flows/usage/#wide-tearsheet
> https://pages.github.ibm.com/carbon/ibm-products/components/tearsheet/style/

Wondering if we should update the old one as well as incorporate it into the new one (or however we decided to update the component)

**Comment by RichKummer** [comment]
## Carbon design crit 12/03/24
* TBD

**Comment by RichKummer** [comment]
## Slack notes on tabbing through Tearsheet

A user noticed a tabbing issue when moving through the `teartsheet` header where a `content switcher` they had placed in the description was skipped at first. If we enable a dedicated slot for components like this, it should ideally show up in the tab order.

https://ibm-studios.slack.com/archives/CQGR0HC05/p1733237950971699

![Image](https://github.com/user-attachments/assets/8b7bd41d-ed0c-47a0-bc44-c0a1c068d8f3)

**Comment by RichKummer** [comment]
# Req

## Header

**Comment by RichKummer** [comment]
## Accessibility – tab order 02/17/25

Discussion with @jlongshore 

Currently, the `Tearsheet` has an odd tab order for its interactive elements:
1. The order begins with the close button selected (Carbon's modal does not, it is last in the order).
2. The order also moves from _some_ header elements such as the close button and AI slug/decorator, to the grid influencer and main content area. Only once the user has tabbed past these do they arrive at the other header elements.

Ideally the tab order follows a logical ordering (similar to PageHeader) and prioritizes header interactive elements before moving down into the grid influencer and main area.

### Current tab order 
https://github.com/user-attachments/assets/bab5d739-9935-435f-8fe6-15954a14825b

**Comment by RichKummer** [comment]
# Cameron review 03/06/25

## Resolved
### Header area
* Insetting the close button and header actions might not work across every component that uses these. For now, we should hold off. The lightest touch is shifting the action header and adding some spacing between the decorator and the close button.
* Positioning of slots and spacing are fine.

### Grid influencer
* When it comes to the grid influencer at smaller screen sizes, we should enable teams to define the way they want the grid influencer to appear. In opening up the grid influencer, we cannot have a one-size-fits-all responsive behavior. Instead, we should prompt the teams to think about how they want to handle it.


## Needs exploration/work
* Need a defined `max-width` that presents the main area in the best way considering the grid. Need follow-on guidance.
* Need guidance on working with the grid inside `Tearsheet`. Special attention needs to be paid towards thinking about responsiveness.

**Comment by RichKummer** [comment]
## Accessibility review with Michael Gower 03/20/25

* Of the explored tab ordering, the first in the set seems to have the proper tab order. The close button should be accessible with `Shift + tab` from the start. 
* It is fine if the mobile visuals and tab order are out of sync with desktop if the tab order is the same across breakpoints.
* A scrollbar should appear in Tearsheet – based on the design, the scrollbar should appear across the entire Tearsheet height (the header area is no longer fixed).
* Discussed how the `F6` key should function when the Tearsheet is stacked. Originally, considered that `F6` key should swap between stacked Tearsheets, but these are also linear flows where the user needs to cancel or complete the step in the stack to return to previous Tearsheets. 
* The addition of the collapsed header will be useful as long as the tab order makes sense. Tab ordering should skip areas that are non-interactive (i.e. if an adopter places a notification in the main slot that is non-interactive, this should be skipped in the tab order).
* Guidance needs to show that clicking outside the overlay does not dismiss the Tearsheet (if guidance does not show this currently).


### To do:
* Explore tablet/@md breakpoint more.

## Design crit review with Carbon team 03/20/25

* Team agreed that placing the header action and decorator across from the header was preferable to the flush design when no close button appears.
* Agreed with max-width of `1312px` to mirror xlg screen size.
* On mobile, showing the overlay brings the Tearsheet out of sync with Modal's mobile design. However, team agreed that giving a visual indication of the stack was more important overall, and went with the adaptive height option.
