### ISSUE TITLE
Adoption of web components within `@carbon/ibm-products`

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#6128]
### The problem

To better support teams not using React, we will deliver support for web components _incrementally_. This issue will be used as an umbrella issue to track the steps necessary to achieve initial web component support in our library and to discuss our strategy for this initiative.

### Owner/main maintainer(s)

Our team

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues
```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/ibm-products/issues/6129
- [ ] https://github.com/carbon-design-system/ibm-products/issues/6130
- [x] Move [tearsheet](https://github.com/carbon-design-system/carbon/tree/main/packages/web-components/src/components/tearsheet) web component into new package within our repo
- [x] Move [side panel](https://github.com/carbon-design-system/carbon/tree/main/packages/web-components/src/components/side-panel) web component into new package within our repo
- [ ] https://github.com/carbon-design-system/ibm-products/issues/6333
- [ ] https://github.com/carbon-design-system/ibm-products/issues/6336
- [ ] https://github.com/carbon-design-system/ibm-products/issues/6334
```

**Comment by ljcarot** [comment]
Can we post announcement on or around Nov 25?

**Comment by ljcarot** [comment]
Closing this Epic as it related to moving SidePanel and Tearsheet out from monorepo.  Will open a new issue for Creating Web Components in ibm-products
