### ISSUE TITLE
Setup new web component storybook

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#6130]
Web components Storybook should be separate instance.

**React Netlify:** https://carbon-for-ibm-products.netlify.app/
**Web components:**
- https://ibm-products-web-components.netlify.app/
- https://carbon-for-ibm-products-wc.netlify.app/

Vanity URL: **web-components.products.carbondesignsystem.com** (based on our react storybook eventually moving to **react.products.carbondesignsystem.com**)

```[tasklist]
### Tasks
- [x] Add Storybook under the directory set up in [previous issue](https://github.com/carbon-design-system/ibm-products/issues/6130)
- [x] Add new site in Netlify
- [ ] https://github.com/carbon-design-system/ibm-products/issues/6197
```

**Comment by matthewgallo** [comment]
Complete
