### ISSUE TITLE
[Feature Request]: Possibility to customize primary conditions

### ISSUE THREAD

**Issue by jakubkloc** [carbon-design-system/ibm-products#6136]
### The problem

Since 2.50.0 version to Condition builder component was add 2 new conditions: **unless all** and **unless any**. This forces us to write support for all cases in which we use the condition builder and they are not necessary. 

![image](https://github.com/user-attachments/assets/898f3abb-2856-4fe7-916a-0a073f2c00dc)

### The solution

It will be great if carbon team deliver props passed to ConditionBuilder where we can set which of theses primary conditions (if all, if any, unless all, unless any) want to use, and made possible to switch off others.

### Owner/main maintainer(s)

na

### Business priority

High Priority = pressing release

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues
```[tasklist]
### Tasks
- [ ] Read [Inversion of Control](https://kentcdodds.com/blog/inversion-of-control)
- [ ] Allow consumer to provide their own options
- [ ] Use the 4 current options as a default
```

**Comment by jakubkloc** [comment]
Can you estimate when this issue will be resolved?

**Comment by ljcarot** [comment]
@jakubkloc We will not be able to get to this issue until next year due to full schedule through end of year.

**Comment by amal-k-joy** [comment]
We have introduced a new prop `statementConfigCustom` where you can pass your custom statement configuration. Current 4 options will serve as default. We have added a new story `With Custom statement configuration` for demonstration
eg: const statementConfigCustom =
```
 [
  {
    id: 'if',
    connector: 'and',
    text1: 'if',
  },
  {
    id: 'exclIf',
    connector: 'or',
    text1: 'excl. if',
  },
];
```
