### ISSUE TITLE
PAL Audit of Components 

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-products#6158]
List of everything in the PAL and compare telemetry data, figma inserts, stable or experimental code, bugs or feature requests that are opened against them.

The PAL is mystery. How much of the assets are used and referenced? As we review website content and find ourselves getting confused about the guidance are consumers feeling the same way?

Over half of edit and update components are experimental.

Record all stats in [Airtable here](https://airtable.com/appY30x3q9FcdIcL1/tbl81O5yRLA4gGh1T/viwwBNTFEglFRBZs5?blocks=hide)

- [x] Audit which components are in the v11 Figma all themes kit and record in Airtable
- [x] Record Figma inserts for each component in Airtable. Look at both the All themes and individual theme kits. 
- [x] Record telemetry data in Airtable
- [x] Record bugs and feature requests for stable 
- [ ] Record bugs and feature requests for experimental
