### ISSUE TITLE
[CSP]: Content security policy violations in SVGs

### ISSUE THREAD

**Issue by amal-k-joy** [carbon-design-system/ibm-products#6178]
### Package

Carbon for IBM Products

### Description

Violation throwing from the SVGs used inside the empty state component

### Component(s) impacted

Datagrid, EmptyState, HTTPError

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

v2.49.0

### Suggested Severity

None

### Product/offering

na

### CodeSandbox or Stackblitz example

https://stackblitz.com/edit/github-fenvlt-5kkbmk?file=index.html

### Steps to reproduce the issue (if applicable)

Run the stackblitz and check the console.
This style is being injected dynamically

![Image](https://github.com/user-attachments/assets/c3c8fbfb-88f2-4834-a595-3ad29353246d)

https://github.com/user-attachments/assets/fe8f76a6-a492-4da4-9851-e0680726ad01

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

```[tasklist]
### Tasks
- [x] EmptyStates/assets/NotificationsIllustration.js
- [x] EmptyStates/assets/NoDataIllustration.js
- [ ] ~HTTPErrorSvg403.js~
- [ ] ~HTTPErrorSvg404.js~
- [ ] ~HTTPErrorSvgOther.js~
```

**Comment by AlexanderMelox** [comment]
No need to touch deprecated SVG's
