### ISSUE TITLE
Sunset v1 package

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#6182]
After the next v1 release, we should actually deprecate the package version[^1].

```[tasklist]
### Tasks
- [x] Release ~1.74.0~ 1.73.2
- [x] Turn off v1-specific GitHub actions
- [x] Update to latest Carbon (v10)
- [x] Deprecate the v1 package in npm
```

[^1]: https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions

**Comment by elycheea** [comment]
It’s done. 🥲
https://www.npmjs.com/package/@carbon/ibm-products/v/1.73.6
