### ISSUE TITLE
Sunset `@carbon/ibm-products-community`

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#6186]
Since our team joined the Carbon umbrella in March, the need for a IBM Products-specific community package has been consolidated with @carbon-design-system/carbon-labs.

The `@carbon/ibm-products-community` package still publishes with our releases due to version bumps or dependency updates.

```[tasklist]
### Tasks
- [ ] Remove `ibm-products-community` directory
- [ ] Remove community checks from `ci.yml`
- [ ] Remove `ci-check:test:community` and `test:community` from `package.json`
- [ ] Deprecate package on npm
- [ ] Check for any residual references to `community` via global search and remove them
```

**Comment by davidmenendez** [comment]
[community](https://www.npmjs.com/package/@carbon/ibm-products-community) has been deprecated on NPM
