### ISSUE TITLE
Address CSP issues in onboarding components

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#6188]
- [ ] Include the respective component name in the forbid configuration inside package.json
- [ ] Run yarn lint and fix the errors
- [ ] Replace `style={{}}` usage with classNames where appropriate
- [ ] Set [dynamic styles](https://github.com/carbon-design-system/carbon/blob/main/docs/style.md#authoring-dynamicinline-styles) using `useIsomorphicEffect()`

```[tasklist]
### Tasks
- [ ] Carousel.tsx
- [ ] ChecklistChart.js
- [ ] Coachmark.tsx
- [ ] CoachmarkOverlay.tsx
```
