### ISSUE TITLE
Address CSP in Datagrid subcomponents

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#6189]
DatagridActions.js is negotiable. It’s meant to be an example, but we have heard instances where consumers will try to import this to use anyway.

- [ ] Include the respective component name in the forbid configuration inside package.json
- [ ] Run yarn lint and fix the errors
- [ ] Replace `style={{}}` usage with classNames where appropriate
- [ ] Set [dynamic styles](https://github.com/carbon-design-system/carbon/blob/main/docs/style.md#authoring-dynamicinline-styles) using `useIsomorphicEffect()`

```[tasklist]
### Tasks
- [x] DatagridExpandedRow.tsx
- [ ] DatagridRow.tsx (need forwardRef on Carbon’s `TableCell`)
- [ ] DatagridVirtualBody.tsx (styles breaking currently)
- [ ] DraggableElement.tsx
- [x] DatagridActions.js
```

**Comment by anamikaanu96** [comment]
DatagridRow.tsx  -> For implementing forwardRef in table cell I have raised a [PR](https://github.com/carbon-design-system/carbon/pull/17760) in carbon for [issue](https://github.com/carbon-design-system/carbon/issues/17759)

**Comment by anamikaanu96** [comment]
Two tasks(DatagridExpandedRow.tsx and DatagridActions.js) in this ticket is already merged with [PR](https://github.com/carbon-design-system/ibm-products/pull/6229).

As discussed for below tasks I have opened separate tickets and closing this issue.

- [ ] DatagridRow - [issue-6269](https://github.com/carbon-design-system/ibm-products/issues/6269)
- [ ] DraggableElement and DatagridVirtualBody - [issue-6270](https://github.com/carbon-design-system/ibm-products/issues/6270)
