### ISSUE TITLE
Address CSP issues in notifications, page header, tearsheet

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#6190]
- [ ] Include the respective component name in the forbid configuration inside package.json
- [ ] Run yarn lint and fix the errors
- [ ] Replace `style={{}}` usage with classNames where appropriate
- [ ] Set [dynamic styles](https://github.com/carbon-design-system/carbon/blob/main/docs/style.md#authoring-dynamicinline-styles) using `useIsomorphicEffect()`

```[tasklist]
### Tasks
- [x] NotificationPanel.tsx
- [x] PageHeader.tsx
- [x] TearsheetShell.tsx
```

**Comment by tom-youd** [comment]
Please can `NoDataEmptyState` be added to the list please?
 I've noticed this component has inline style blocks
