### ISSUE TITLE
Test dynamic import of `media` prop

### ISSUE THREAD

**Issue by devadula-nandan** [carbon-design-system/ibm-products#6243]
```[tasklist]
### Tasks
- [ ] test the dynamic import of lottie web package `SteppedAnimatedMedia`
- [ ] can we dynamically import `SteppedAnimatedMedia` to coachmarkOverlayElements
- [ ] create CRA template and test the difference in sizing (not an issue with vite, but is in webpack)
```

**Comment by elycheea** [comment]
CRA template for quick start test app. https://github.com/matthewgallo/cra-template-carbon-ibm-products
