### ISSUE TITLE
Create overflow utilities

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#6274]
`ActionBar`, `DelimitedList`, `StringFormatter`, and `TagOverflow` are all similar in that they help handle overflow of items, using truncation or an other overflow component (e.g. interactive tag, overflow menu, tooltip) to handle additional display.

We should do a deep dive to learn where we might be able to consolidate some of these or reuse overflow logic for these very similar use cases.

### Explore the following features
- [x] Line length or container width
- [x] Number of lines or multiline truncation
- [x] Single line truncation with overflow content
- [x] Max visible items
- [x] Overflow rendering (tooltip, overflow menu, popover)
- [x] **Can this new utility deprecate these 4 separate components**
- [x] Floating UI support

Another thought on delimited list — could this be used _alongside_ “string formatter”? Current version does not show overflow content at all — only truncation, but most likely an accessibility violation if not.

### Acceptance criteria
- [ ] Work with design to determine which features need to be included
- [ ] These should be written agnostically to support both packages (`@carbon/utilities` and `@carbon/utilities-react`)

**Comment by davidmenendez** [comment]
for reference: i touched on this briefly in [#5341](https://github.com/carbon-design-system/ibm-products/issues/5341#issuecomment-2445318757)

**Comment by elycheea** [comment]
Moved the `DelimitedList` and `StringFormatter` evaluation to the umbrella issue so we can close out this epic. :)
