### ISSUE TITLE
Tearsheet design exploration: Influencer and main area

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/ibm-products#6284]
For `Tearsheet`'s composibility, we're looking at how the grid influencer and the main area interact. There are two types of grid influencers: a left version (normally for things like a progress indicator or menu) and a right version (for more detail within the main section). 

By making the `Tearsheet` more composable, we should explore a few ways to handle slotting content into the grid influencer and main area, especially when it comes to spacing.

[Tearsheet v2 file](https://www.figma.com/design/T1aYHUWsUBoaKV0Ywy8Plh/Tearsheet-v2-explo?node-id=402-439548&t=yUEFxV2FYEkqBNtI-1) (I started a section for this)

1. Influencers: should be able to slot in progress/menu/etc instead of relying on props.
     - Show spacing expectations for menus, progress indicator, and open slotted area (questionable).
     - Should we use conditional spacing?
     - Should we support both wide and narrow influencer sizes? (this is currently available for both right and left versions).

2. Spacing/slotting around main area
     - The influencer and main area use unequal spacing around each. Should we use equal spacing instead?
     - Right now the influencers uses `24px` spacing top, and it looks like main area uses `16px` spacing top.
     - Should we consider type alignment (aligning the `Table of contents` in the What's new pattern for example). Should we rely on guidance for teams to accomplish this?

3. Explore influencer and main area responsiveness
     - We should also consider how these elements will behave on smaller screen sizes/increased zoom.

4. For the left influencer, we should see what other components (from Core or Products) that teams might want to embed in the future. For example, the What's New pattern brought in the [Table of contents](https://www.ibm.com/standards/carbon/components/table-of-contents) from Dotcom. Take a look through Carbon core's [component list](https://carbondesignsystem.com/components/overview/components/) and note any that teams might want to make use of (if any)

5.  We also need to consider the Narrow Tearsheet – if we adjust spacing at the top, we should consider it there as well.

6. Another item, which easily could spin off into another story, is how to treat the grid influencer responsively. When the screen is too small, how should we display (or even hide) the influencer? I started a quick exploration [here](https://www.figma.com/design/T1aYHUWsUBoaKV0Ywy8Plh/Tearsheet-v2-explo?node-id=454-519391&t=ZCjYlmmrykrQsSHS-1) but if there's time, I'd love to check out how other products solve for this.
## Tasks
- [x] Briefly explore the documentation on Tearsheet on the website
- [x] Meet with Rich to review ask
- [x] Expand the design exploration in Figma
- [ ] Playback during design crit
- [ ] Craft a POV on handling this in the component and docs
