### ISSUE TITLE
[PageHeader v2] Present current design and incorporate feedback from Design & Dev

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/ibm-products#6482]
After round 2 of design explorations and feedback from design team, we need to present the latest designs to development. With the feedback, we can choose the direction of how we want to structure the component and finalize the design so that we can start specs.

**Tasks**
- [x] Choose & finalize spacing from design crit
- [x] Set up feedback meeting with PAL design & devs
- [x] Incorporate feedback
- [x] Document decisions made

**Open questions**
Should this component go into PAL or Core?
