### ISSUE TITLE
Follow on for ExpressiveCard and ProductiveCard

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/ibm-products#6486]
Follow on from #5805 

**Findings:**
* ProductiveCard can have multiple interactive zones. We need to determine if those require a stroke and visual indicator for Carbon guidance.

**Tasks:**
- [x] Review Thy's [Tiles](https://www.figma.com/design/9ETOwILkTbvUErWUR4PTIg/Tiles?node-id=906-38183&t=9wyymFHIbcfPuxDs-1) audit, the `Research` and `Explorations` pages have some good examples and her thought process
- [x] Consider checking Telemetry and Figma data for usage.
- [x] Reach out to [Johanna Koval](https://w3.ibm.com/#/people/3J3186897) (Data & AI), who worked on ProductiveCard guidance.
- [x] Collect Security example from Cameron.
- [x] Consider posting to [#design-system-adoption-guild](https://ibm.enterprise.slack.com/archives/C076HLZEKCY).
- [x] We should see how Product teams are using the ProductiveCard. How often are multiple interactive zones used?

**Comment by benjamin-kurien** [comment]
Reviewed the [research work](https://www.figma.com/design/Bo0vGQ9lzrCYIdZz97YqII/Cards?node-id=296-11406&t=Q7JLLSxZ2xaPOSym-1) with Rich and Olivia.

- Telemetry data indicates that three-zone productive cards have a 100% relative usage compared to single and two-zone cards.
- A qualitative review of various products (collected from our gallery, and provided by teams) reveals frequent use of three zone productive cards without the supplemental bar.
