### ISSUE TITLE
Review Scrolling docs

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-products#6573]
## The problem:
Review the datagrid documentation on the website to ensure all information is accurate before we move the docs into the Patterns section. You should identify:
1. Things that are not showcased in the Tanstack [React](https://github.com/carbon-design-system/tanstack-carbon/tree/main/react#data-table-extensions-tanstackreact-table) and [Web component](https://github.com/carbon-design-system/tanstack-carbon/blob/main/web-components/README.md) examples (or current storybook)
2. Things that contradict core or accessibility guidance
   - Example: Clickable links section states only to show links on hover, but that was never implemented in code and contradicts core/accessibility
3. Note any place where we could improve documentation:
   - Simplify text
   - Simplify H2s or H3s
   - Consolidate duplicate information 
4. Note any v10 token usage

## Task:

- [ ] Read the page on the website
- [ ] Compare the storybook to Tanstack examples
- [ ] If you find any misleading or incorrect documentation take note
   - Confirm with Matt that Tanstack is capable of a feature if you're unsure
   - Check with the team if you're unsure of a feature 
- [ ] Open a new issue for changes that need to be made in the docs
