### ISSUE TITLE
PageHeader: Remove invalid and unused CSS variables

### ISSUE THREAD

**Issue by wkeese** [carbon-design-system/ibm-products#6575]
### Package

Carbon for IBM Products

### Description

[_page-header.scss](https://github.com/carbon-design-system/ibm-products/blob/5b5e681f7c52c0950419a9081df497cb2033791d/packages/ibm-products-styles/src/components/PageHeader/_page-header.scss#L124) defines some CSS variables, trying to use SCSS variables:

```scss
--#{$block-class}--navigation-buffer-top: $spacing-06;
--#{$block-class}--navigation-buffer-top: $spacing-04;
```

It ends up generating CSS like below, referencing undefined terms like $spacing-06:

```css
--c4p--page-header--navigation-buffer-top: $spacing-06;
--c4p--page-header--navigation-buffer-top: $spacing-04;
```

(That's from index-without-carbon.css in the NPM distribution.)

The SCSS should have been a syntax like this instead:

```scss
--#{$block-class}--navigation-buffer-top: #{$spacing-06};
--#{$block-class}--navigation-buffer-top: #{$spacing-04};
```

But it turns out it doesn't matter anyway because those CSS variables aren't even being used.   So they should just be removed from the SCSS, right?

### Component(s) impacted

PageHeader

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.53

### Suggested Severity

None

### Product/offering

IKC

### CodeSandbox or Stackblitz example

N/A

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### Tasks
- [ ] Remove the unused variables

**Comment by amal-k-joy** [comment]
Looks like we are good to remove these css variables since its not used
