### ISSUE TITLE
Coachmark: UX review

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/ibm-products#6592]
The goal of this step is to get familiar with the component/pattern as it exists today. You'll be reviewing the component across the docs, coded versions, and Figma kit. For this first step, keep in mind the goal of discovering if there are ways to make this component more flexible and composable. You don't need to answer these know, but think about:
* What options are there. Do you think there are any missing?
* If I were to add a Slot component from Figma, would that be useful to switch out other components?
* What existing elements might I want to switch out?

## Tasks
- [x]  Review the existing component’s [documentation](https://pages.github.ibm.com/carbon/ibm-products/components/onboarding/coachmark/usage/)
- [x]  Review the component in [Storybook](https://carbon-for-ibm-products.netlify.app/?path=/docs/experimental-onboarding-coachmark--docs)
- [x]  Review the component and its variants in the [Figma kit](https://www.figma.com/design/0F9dKH2abAd7gSfvnacfWf/(v11)-Carbon-for-IBM-Products?node-id=16728-643619&t=qme8iARFftB1gryu-1)
- [x]  Note areas where the component could be made more flexible but currently is not. Could we update certain existing components in this one? Add any new areas to bring in other components?
- [x]  Search the [backlog](https://github.com/orgs/carbon-design-system/projects/65/views/1) for any issues related to that component. See any themes?
- [x]  Review difference between components and patterns docs on Core.
- [x]  Check out [Product gallery](https://pages.github.ibm.com/carbon/ibm-products/product-gallery/gallery/) in the website. What examples exist for this component? See how adopters are using the component. Would an adopter want it to be more flexible, and how?

**Comment by bndege2** [comment]
# Coachmark: UX Review  


### Areas the Coachmark components could be made more flexible:  

**Additional use case identified in What’s new notification work:**  
- **Coachmark without the beacon**: Designers want to draw users' eye to an element in the UI but do not need the beacon, e.g., coachmark pointing to a button/icon.  
- **Coachmark without beacon open upon page load**  

![Image](https://github.com/user-attachments/assets/fe1cfe79-9fd3-4b8f-961d-79d329730f38)

### Theming:  
- All Figma components should be updated with inverse theming. The contrast draws users' attention. (Refer to v10 components and use v11 theming.)  

![Image](https://github.com/user-attachments/assets/9c20886f-5ccf-4f48-8f5a-de128f0de0d9)

### Sizing:  
- We currently only have one width size for coachmarks. Teams might need wider options. Below is an exploration of where the design needed a wider coachmark to display a gif.  

![Image](https://github.com/user-attachments/assets/8810019d-4f17-4e92-853f-d93fd27e0b9e)

---

### Figma Kit Review:  
See **Figma Onboarding Update: Coachmark #61**  

### Storybook Review:  

**Rework how Coachmark components are coded:**  

Making updates to the coachmark code is not easy to manage due to how it’s built.  

- **Coachmarks are built on Coachmarkoverlay.**  
  - Coachmarkoverlay is:  
    1. Not exposed  
    2. Only being used for the coachmark component  

- **Popovercomponent**, which already exists independently, could be used instead and allow for more flexibility. This is a possible solution but requires further discussion.  

### Hardcoded Icons:  
- The idea icon on the collapsed fixed coachmark and fixed coachmark without image are currently hardcoded and do not allow designers the ability to swap it out for another. The Figma component would need to be updated as well for designers to swap out the icon. 

### Positions:  
- Current Tooltip stepped coachmark is not designed to change position when a user moves between steps. WalkMe allows for this interaction, but we could consider adding this functionality into our Carbon components.  

---

### Documentation Review:  
| Variant                | Purpose                                                                                       |  
|------------------------|-----------------------------------------------------------------------------------------------|  
| **Stacked**            | Provides additional context to the main coachmark message.                                    |  
| **Stacked (correction)** | Specifically for fixed coachmark messages. We do not use a stacked coachmark on a tooltip coachmark or floating coachmark. |  

---

### Re-triggering Coachmark:  
- Currently, teams have no guidance on how to re-trigger a coachmark if they are not using the Assist Me panel.  
- Guide banners are a solution, but is there another approach we could take here?
