### ISSUE TITLE
Interstitial: UX review

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/ibm-products#6609]
The goal of this step is to get familiar with the component/pattern as it exists today. You'll be reviewing the component across the docs, coded versions, and Figma kit. For this first step, keep in mind the goal of discovering if there are ways to make this component more flexible and composable. You don't need to answer these know, but think about:
* What options are there. Do you think there are any missing?
* If I were to add a Slot component from Figma, would that be useful to switch out other components?
* What existing elements might I want to switch out?

## Tasks
- [x]  Review the existing component’s [documentation](https://pages.github.ibm.com/carbon/ibm-products/components/onboarding/interstitial-screen/)
- [x]  Review the component in [Storybook](https://carbon-for-ibm-products.netlify.app/?path=/docs/experimental-onboarding-interstitial-screen-interstitialscreen--docs&globals=viewport:basic)
- [x]  Review the component and its variants in the [Figma kit](https://www.figma.com/design/0F9dKH2abAd7gSfvnacfWf/(v11)-Carbon-for-IBM-Products?node-id=16728-642837&t=n7oLY6RZJOvNZTHt-1)
- [x]  Note areas where the component could be made more flexible but currently is not. Could we update certain existing components in this one? Add any new areas to bring in other components?
- [x]  Search the [backlog](https://github.com/orgs/carbon-design-system/projects/65/views/1) for any issues related to that component. See any themes?
- [x]  Review difference between components and patterns docs on Core.
- [x]  Check out [Product gallery](https://pages.github.ibm.com/carbon/ibm-products/product-gallery/gallery/) in the website. What examples exist for this component? See how adopters are using the component. Would an adopter want it to be more flexible, and how?

**Comment by susanacr2** [comment]
Working [Figma file](https://www.figma.com/design/XDPXSa69ULYQ3BfplOPynQ/Interstitial%3A-UX-review-%236609?node-id=40-4626&t=Vlr84MVpDQnWjxMb-1)

**Comment by susanacr2** [comment]
https://github.com/user-attachments/assets/cb91898a-ccb6-4b1d-8541-9055f830a8bc

**Comment by susanacr2** [comment]
Meeting with Melissa Fernandes and Maksim Halubouski on Tuesday to discuss their experience with the Interstitial on Cloud Pak for Data. 

<img width="1312" alt="Image" src="https://github.com/user-attachments/assets/53c597cb-2c04-44de-965d-fb37e5891ae3" />

**Comment by susanacr2** [comment]
Meeting with Micheal Douglas on Monday to hear about his experience working with the interstitial for Security. 

<img width="1338" alt="Image" src="https://github.com/user-attachments/assets/68b4ec60-d371-4271-b42e-6743ac29ff30" />
<img width="1338" alt="Image" src="https://github.com/user-attachments/assets/47c496f5-7445-432d-a170-18b1d29b0f78" />

**Comment by susanacr2** [comment]
I met with Micheal from GDSC and got some context about his experience with both the Interstitial and the Get started patterns. 

Topic Discussed: How he had to rework the Interstitial as the current pattern isn't transitioning well into the Get started pattern.

Reasoning: The layout of the current Interstitial seems disconnected when the user lands on the product. 

Context: For his use case there are two users, the tenant/admin and the user. He is focused on the tenant experience where a user is mainly setting the permissions, turning things on and off –doing the installing. It should be quick to get the user straight into the product where then, he can do the configurations leveraging something similarly to the get started pattern. (He has made some adjustments to it).

Inspired by Turbonomic's onboarding, Micheal explored how to leverage the interstitial (with some customizations) as it felt more natural. He learned that doing some of the configuring such as adding users, does not belong in this flow as it can get quite long and messy for a user. Therefore, he is an advocate for having quick steps, in his flow, only 2 to get the user set up and then continue the experience on he lands into the product. 

Can the Interstitial still be used as personalization? Yes, the tenant can do what was described above. The user, can still come here and select what they want to do with the product and some might also have access to set up the product as well. 

Get started pattern: There was some feedback received about the Getting started pattern, including having empty states labels such as "No users, no databases" rather than checkboxes. These can be overwhelming for the user and the user can come and do them as they wish. 

Customizations: 
- Vertical progress indicator
- Tiles: adding a stroke to them (user can select one or more)
- Side links 
- Side extra information/support about the use cases
- Loading
- Extension of Progress Indicator in V2.


<img width="1312" alt="Image" src="https://github.com/user-attachments/assets/636c014f-0bde-4558-9e7d-9538461a9635" />

Files shared:

- [Admin onboarding experience v2](https://www.figma.com/design/kKu1IjpL1ozra6tHqih5Q2/Admin-onboarding-experience-v1?node-id=4040-8474&t=HlcDOb4ncVhCdlDC-1): 
- [Admin onboarding experience v2] (https://www.figma.com/design/GjaKGbNJlczG5eSVpAAbV6/Admin-onboarding-experience-v2?node-id=2001-63&t=rQd4uHgNQZUkIrSd-1): Shows how the configuring should not be part of the Interstitial.
- [Admin onboarding experience v3](https://www.figma.com/design/bZProirmRxZyhNMdDSDvHC/Admin-onboarding-experience-v3?node-id=168-24&t=EKR1vCiXjN5FVpZ7-1)

**Comment by susanacr2** [comment]
Met with Melissa Fernandes and Maksim Halubouski to discuss how they have used the Interstitial for Cloud Pak for Data. 

Topic: Usage of the Interstitial as an onboarding for users that represents the value of the product.

Experience: They have discovered the Interstitial on the PAL site, they have used it as a way to show the product's value. However, they want it as a way to help them personalize the experience for a user as the product can get complex and they have multiple personas who do different tasks depending on their experience/role. I presented the personalization work we did with Tracey last year that they can leverage. They were not aware of it. They don't know if the interstitial is instrumented on the product but don't have enough customers to get information if the users are skipping or going through it. 

Pain points of their current experiences:
- The layout can look a little weird. The button on the right is distant from the Skip, looking separate from the rest of the screen. 
- The picture takes over a big space along with the text. When the screen is big, there is a lot of white space, not reasonable empty space.
- On the second step, the screen scrolls when the others don't. 
- Struggled to find images, they just copied them from another team Relationship Advisor.


If they could customize it (without yet seeing the personalization work)
- Checkboxes to make selections
- For personalization, options to be in your face and to be easy as possible
- Their product is very technical, users might come here not knowing anything.
- Questions with radial/buttons
- Select tasks for personalization
- The shorter the steps the better
- Short text - people don't read as much. 

![Image](https://github.com/user-attachments/assets/8ce1c356-f8e7-448e-9c51-c38cdcb4d516)
![Image](https://github.com/user-attachments/assets/7695b604-f0ed-4939-aff2-d82381abb7e3)

**Comment by susanacr2** [comment]
In Summary, the Interstitial is being used by a couple of products. The team members who I met with raised areas for improvement or customization including
- Providing media examples of what works depending on the use case, and step a user is in
- Raise more awareness of the personalization aspect of how the Interstital can be leveraged
- Horizontal vs. Vertical progress indicator to transition smoothly depending on what the landing page looks like
- More guidance on the documentation including, personalization, media, creating animations
- There needs to be a length adjustment to the [Overlay Tile + Steps Figma tookit](https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/69) #69

Met with Rich to go over my work so far. Will be presenting it on Demo day tomorrow, and will continue working on the next sprint.
