### ISSUE TITLE
Cards: UX review

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/ibm-products#6615]
The goal of this step is to get familiar with the component/pattern as it exists today. You'll be reviewing the component across the docs, coded versions, and Figma kit. For this first step, keep in mind the goal of discovering if there are ways to make this component more flexible and composable. You don't need to answer these know, but think about:
* What options are there. Do you think there are any missing?
* If I were to add a Slot component from Figma, would that be useful to switch out other components?
* What existing elements might I want to switch out?

## Tasks
- [x] Start with reviewing Carbon core's [Tile](https://carbondesignsystem.com/components/tile/usage/) component which informs the cards. If you have time, also check out Dotcom's [Cards](https://www.ibm.com/standards/carbon/components/cards)
- [x]  Review the existing component’s [documentation](https://pages.github.ibm.com/carbon/ibm-products/components/card/overview/)
- [x]  Review the component in [Storybook](https://carbon-for-ibm-products.netlify.app/?path=/docs/ibm-products-components-cards-expressivecard)
- [x]  Review the component and its variants in the [Figma kit](https://www.figma.com/design/0F9dKH2abAd7gSfvnacfWf/(v11)-Carbon-for-IBM-Products?node-id=5970-355652&t=n7oLY6RZJOvNZTHt-1)
- [x]  Note areas where the component could be made more flexible but currently is not. Could we update certain existing components in this one? Add any new areas to bring in other components?
- [x]  Search the [backlog](https://github.com/orgs/carbon-design-system/projects/65/views/1) for any issues related to that component. See any themes?
- [x]  Review difference between components and patterns docs on Core.
- [x]  Check out [Product gallery](https://pages.github.ibm.com/carbon/ibm-products/product-gallery/gallery/) in the website. What examples exist for this component? See how adopters are using the component. Would an adopter want it to be more flexible, and how?

**Comment by rachels01** [comment]
**_* Note areas where the component could be made more flexible but currently is not. Could we update certain existing components in this one? Add any new areas to bring in other components?_** 
    * The expanded state in the “With interactive elements” section of https://carbondesignsystem.com/components/tile/usage/ is interesting because it surfaces data without requiring the user to link elsewhere. Perhaps this can be explored more to see what other data formats can be hosted within a card.
    * Perhaps there is a use case for expressive cards with gifs. 
    * For the AI cards, I wonder if it might make sense to add a hover state with an informational tool tip to see what about the card is being informed by AI. 
    * Clarification can be provided around guidance for the width of the cards. https://carbondesignsystem.com/components/tile/usage/ states “In a horizontal masonry layout, tiles can vary in width; different rows of tiles may vary in height, but tiles within a row should be consistent in height.” However,  https://pages.github.ibm.com/carbon/ibm-products/components/card/expressive-card/usage/ states that cards must be one o 4 sizes on the grid. 
    * Feature flags are almost imperceptible on the card designs. Perhaps there is a way to explore making them stand out a bit more. 
**_* Search the [backlog](https://github.com/orgs/carbon-design-system/projects/65/views/1) for any issues related to that component. See any themes?_**
    * Other than the items related to this ticket, the following are backlog issues related to cards: 
        * #42 (Pattern missing in C4IP Figma kit) 
        * #125 (Update card link)- seems to have been resolved already? 
    * Both issues are more process/maintenance related as opposed to pattern related. 
**_* Check out [Product gallery](https://pages.github.ibm.com/carbon/ibm-products/product-gallery/gallery/) in the website. What examples exist for this component? See how adopters are using the component. Would an adopter want it to be more flexible, and how?_**
    * How teams are using cards:
        * Collapsable leadspace within product where cards can be hidden if the user chooses to do so (IBM Software Hub)
        * Expressive cards used to show data roll-ups (IBM Controller Web)
        * Productive cards used to show data tables (App Connect)
        * Cards used to display status of integrations (App Connect)
        * Homepage features cards that show current information about the product, ie. Notifications (Cloud Pay for Data) 
    * Ideas for how adopters may want the pattern to be more flexible are listed in the first bullet point above.

**Comment by rachels01** [comment]
**Conversation with Developers on App Connect:**

Adam Roberts:
"The problems I vaguely recall were to do with lining everything up relative to the header, and then some z-axis related things that were really to do with what we were putting onto the cards, and not the cards themselves. I don't remember anything especially bad that we couldn't overcome."

Jonathan Roberts:
"I've been looking back at previous slack chats we had with the design team about these cards. There had been some questions about what would or wouldn't be allowed it the header of the cards. I think one of our designs had wanted a dropdown to appear in the card header, but we couldn't do that. Now I think about it, we might have wanted to include a help link or other html in the header but not been able to do it (we were limited to a text description only)."

**Comment by rachels01** [comment]
**Conversation with Heather Co (Designer from IBM Controller)**

Questions I asked:

- I see you leveraged expressive cards in the screenshot below. What is generally your reasoning for selecting productive vs expressive?
- Is there anything you would have hoped the card patterns would have allowed you to do that you were unable to because of how the existing pattern was designed/architected?
- Are there any variations of the cards that you could see needing on your future work?

Heather's replies:

- For the first question, I chose the card based on the amount of content I wanted to present in a card and made the needed adjustments.

- Last question, I think it would be helpful to see how these cards adjust when responsive web design is considered.
Regarding your other question, nothing comes to mind right now, it has been a while since I've used a card design.

**Comment by rachels01** [comment]
@RichKummer Please take a look and let me know if you have any feedback. Thanks!

**Comment by rachels01** [comment]
**Conversation with Michael McCurry (Designer from IBM Cloud Pak for Watson AI Ops)**

Questions I asked:

- I noticed in the screenshot below that the cards do not use the typical padding between cards associated with the pattern. Do you recall if this was a decision that was made in order to achieve a particular goal? Can you please let me know more about that?
- Is there anything you would have hoped the card patterns would have allowed you to do that you were unable to because of how the existing pattern was designed/architected?
- Are there any variations of the cards that you could see needing on your future work?

Michael's replies: 

- We use the condensed grid purely for design. We were exploring layouts, and the product team liked this the best.
- It did everything we needed it to do.
- I would really like to see how cards respond to larger screens. For example, NOC (Network Operation Centers) like to put dashboards on large screens in their Centers. That means content in the cards needs to scale up to be viewed at different distances. [Confirm by this he was referring to large screens like TV screens]
